/*
* Araxxor drops list made by Versusik.
*/

AraxxorDrops = [
	{
		"title": "Araxyte arrow",
		"quantity": 80,
		"price": 191,
		"rarity": "Common",
		"droprate": null,
		"type": "Araxyte drop",
		"img": "/img/rs3/araxyte_arrow.png",
		"game": "rs3",
		"boss": "Araxxor",
		"npc": "Araxxor"
	},	
	{
		"title": "Araxyte pheromone",
		"quantity": 1,
		"price": 1974341,
		"rarity": "Rare",
		"droprate": null,
		"type": "Araxyte drop",
		"img": "/img/rs3/araxyte_pheromone.png",
		"game": "rs3",
		"boss": "Araxxor",
		"npc": "Araxxor"
	},
	{
		"title": "Starved ancient effigy",
		"quantity": 1,
		"price": null,
		"rarity": "Very rare",
		"droprate": null,
		"type": "Efiggies",
		"img": "/img/rs3/starved_ancient_effigy.png",
		"game": "rs3",
		"boss": "Araxxor",
		"npc": "Araxxor"
	},
	{   "title": "Rocktail",
		"quantity": 9,
		"price": 1779,
		"rarity": "Common",
		"droprate": null,
		"type": "Food and potions",
		"img": "/img/rs3/rocktail.png",
		"game": "rs3",
		"boss": "Araxxor",
		"npc": "Araxxor"
	},
	{
		"title": "Saradomin brew flask (6)",
		"quantity": 9,
		"price": 18908,
		"rarity": "Common",
		"droprate": null,
		"type": "Food and potions",
		"img": "/img/rs3/saradomin_brew_flask_(6).png",
		"game": "rs3",
		"boss": "Araxxor",
		"npc": "Araxxor"
	},	{
		"title": "Super restore flask (6)",
		"quantity": 4,
		"price": 10315,
		"rarity": "Common",
		"droprate": null,
		"type": "Food and potions",
		"img": "/img/rs3/super_restore_flask_(6).png",
		"game": "rs3",
		"boss": "Araxxor",
		"npc": "Araxxor"
	},
	{
		"title": "Overload flask (6)",
		"quantity": 4,
		"price": null,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "Food and potions",
		"img": "/img/rs3/overload_flask_(6).png",
		"game": "rs3",
		"boss": "Araxxor",
		"npc": "Araxxor"
	},
	{
		"title": "Grimy lantadyme",
		"quantity": 50,
		"price": 5898,
		"rarity": "Common",
		"droprate": null,
		"type": "Main loot",
		"img": "/img/rs3/grimy_lantadyme.png",
		"game": "rs3",
		"boss": "Araxxor",
		"npc": "Araxxor"
	},
	{	"title": "Grimy dwarf weed",
		"quantity": 45,
		"price": 6334,
		"rarity": "Common",
		"droprate": null,
		"type": "Main loot",
		"img": "/img/rs3/grimy_dwarf_weed.png",
		"game": "rs3",
		"boss": "Araxxor",
		"npc": "Araxxor"
	},
	{
		"title": "Grimy avantoe",
		"quantity": 45,
		"price": 4023,
		"rarity": "Common",
		"droprate": null,
		"type": "Main loot",
		"img": "/img/rs3/grimy_avantoe.png",
		"game": "rs3",
		"boss": "Araxxor",
		"npc": "Araxxor"
	},
	{
		"title": "Black dragonhide",
		"quantity": 80,
		"price": 3590,
		"rarity": "Common",
		"droprate": null,
		"type": "Main loot",
		"img": "/img/rs3/black_dragonhide.png",
		"game": "rs3",
		"boss": "Araxxor",
		"npc": "Araxxor"
	},
	{
		"title": "Magic logs",
		"quantity": 250,
		"price": 908,
		"rarity": "Common",
		"droprate": null,
		"type": "Main loot",
		"img": "/img/rs3/magic_logs.png",
		"game": "rs3",
		"boss": "Araxxor",
		"npc": "Araxxor"
	},
	{	"title": "Yew logs",
		"quantity": 600,
		"price": 268,
		"rarity": "Common",
		"droprate": null,
		"type": "Main loot",
		"img": "/img/rs3/yew_logs.png",
		"game": "rs3",
		"boss": "Araxxor",
		"npc": "Araxxor"
	},
	{
		"title": "Rune platebody",
		"quantity": 10,
		"price": 38010,
		"rarity": "Common",
		"droprate": null,
		"type": "Main loot",
		"img": "/img/rs3/rune_platebody.png",
		"game": "rs3",
		"boss": "Araxxor",
		"npc": "Araxxor"
	},
	{
		"title": "Adamantite ore",
		"quantity": 100,
		"price": 1401,
		"rarity": "Common",
		"droprate": null,
		"type": "Main loot",
		"img": "/img/rs3/adamantite_ore.png",
		"game": "rs3",
		"boss": "Araxxor",
		"npc": "Araxxor"
	},
	{
		"title": "Coal",
		"quantity": 600,
		"price": 314,
		"rarity": "Common",
		"droprate": null,
		"type": "Main loot",
		"img": "/img/rs3/coal.png",
		"game": "rs3",
		"boss": "Araxxor",
		"npc": "Araxxor"
	},
	{	"title": "Coins",
		"quantity": 420000,
		"price": 1,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "Main loot",
		"img": "/img/rs3/coins.png",
		"game": "rs3",
		"boss": "Araxxor",
		"npc": "Araxxor"
	},
	{
		"title": "Water talisman",
		"quantity": 50,
		"price": 12282,
		"rarity": "uncommon",
		"droprate": null,
		"type": "Main loot",
		"img": "/img/rs3/water_talisman.png",
		"game": "rs3",
		"boss": "Araxxor",
		"npc": "Araxxor"
	},
	{
		"title": "Runite ore",
		"quantity": 50,
		"price": 11053,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "Main loot",
		"img": "/img/rs3/runite_ore.png",
		"game": "rs3",
		"boss": "Araxxor",
		"npc": "Araxxor"
	},
	{
		"title": "Dwarf weed seed",
		"quantity": 10,
		"price": 15624,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "Main loot",
		"img": "/img/rs3/dwarf_weed_seed.png",
		"game": "rs3",
		"boss": "Araxxor",
		"npc": "Araxxor"
	},
	{	"title": "Magic seed",
		"quantity": 5,
		"price": 148362,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "Main loot",
		"img": "/img/rs3/magic_seed.png",
		"game": "rs3",
		"boss": "Araxxor",
		"npc": "Araxxor"
	},
	{
		"title": "Battlestaff",
		"quantity": 50,
		"price": 7156,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "Main loot",
		"img": "/img/rs3/battlestaff.png",
		"game": "rs3",
		"boss": "Araxxor",
		"npc": "Araxxor"
	},
	{
		"title": "Onyx bolts (e)",
		"quantity": 160,
		"price": 8572,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "Main loot",
		"img": "/img/rs3/onyx_bolts_(e).png",
		"game": "rs3",
		"boss": "Araxxor",
		"npc": "Araxxor"
	},
	{
		"title": "Crystal triskelion fragment 1",
		"quantity": 1,
		"price": null,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "Main loot",
		"img": "/img/rs3/crystal_triskelion_fragment_1.png",
		"game": "rs3",
		"boss": "Araxxor",
		"npc": "Araxxor"
	},
	{	"title": "Crystal triskelion fragment 2",
		"quantity": 1,
		"price": null,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "Main loot",
		"img": "/img/rs3/crystal_triskelion_fragment_2.png",
		"game": "rs3",
		"boss": "Araxxor",
		"npc": "Araxxor"
	},
	{
		"title": "Crystal triskelion fragment 3",
		"quantity": 1,
		"price": null,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "Main loot",
		"img": "/img/rs3/crystal_triskelion_fragment_3.png",
		"game": "rs3",
		"boss": "Araxxor",
		"npc": "Araxxor"
	},
	{
		"title": "Sirenic scale",
		"quantity": 2,
		"price": 271982,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "Main loot",
		"img": "/img/rs3/sirenic_scale.png",
		"game": "rs3",
		"boss": "Araxxor",
		"npc": "Araxxor"
	},
	{
		"title": "Uncut onyx",
		"quantity": 2,
		"price": 1068240,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "Main loot",
		"img": "/img/rs3/uncut_onyx.png",
		"game": "rs3",
		"boss": "Araxxor",
		"npc": "Araxxor"
	},
	{
		"title": "Spider leg top",
		"quantity": 1,
		"price": null,
		"rarity": "Rare",
		"droprate": null,
		"type": "Leg pieces",
		"img": "/img/rs3/spider_leg_top.png",
		"game": "rs3",
		"boss": "Araxxor",
		"npc": "Araxxor"
	},
	{
		"title": "Spider leg middle",
		"quantity": 1,
		"price": null,
		"rarity": "Rare",
		"droprate": null,
		"type": "Leg pieces",
		"img": "/img/rs3/spider_leg_middle.png",
		"game": "rs3",
		"boss": "Araxxor",
		"npc": "Araxxor"
	},
	{
		"title": "Spider leg bottom",
		"quantity": 1,
		"price": null,
		"rarity": "Rare",
		"droprate": null,
		"type": "Leg pieces",
		"img": "/img/rs3/spider_leg_bottom.png",
		"game": "rs3",
		"boss": "Araxxor",
		"npc": "Araxxor"
	},
	{
		"title": "Araxxi's fang",
		"quantity": 1,
		"price": null,
		"rarity": "Rare",
		"droprate": null,
		"type": "Weapon parts",
		"img": "/img/rs3/araxxis_fang.png",
		"game": "rs3",
		"boss": "Araxxor",
		"npc": "Araxxor"
	},
	{
		"title": "Araxxi's web",
		"quantity": 1,
		"price": null,
		"rarity": "Rare",
		"droprate": null,
		"type": "Weapon parts",
		"img": "/img/rs3/araxxis_web.png",
		"game": "rs3",
		"boss": "Araxxor",
		"npc": "Araxxor"
	},
	{
		"title": "Araxxi's eye",
		"quantity": 1,
		"price": null,
		"rarity": "Rare",
		"droprate": null,
		"type": "Weapon parts",
		"img": "/img/rs3/araxxis_eye.png",
		"game": "rs3",
		"boss": "Araxxor",
		"npc": "Araxxor"
	},
	{
		"title": "Araxyte pet",
		"quantity": 1,
		"price": null,
		"rarity": "Very rare",
		"droprate": null,
		"type": "Pets",
		"img": "/img/rs3/araxyte_pet.png",
		"game": "rs3",
		"boss": "Araxxor",
		"npc": "Araxxor"
	},
	{
		"title": "Araxyte egg",
		"quantity": 1,
		"price": null,
		"rarity": "Very rare",
		"droprate": null,
		"type": "Pets",
		"img": "/img/rs3/araxyte_egg.png",
		"game": "rs3",
		"boss": "Araxxor",
		"npc": "Araxxor"
	}
];