/*
* RS3 Armadyl drops list made by Mokuin.
*/

ArmadylDropsRs3 = [
	{
		"title": "Rune crossbow",
		"quantity": 1,
		"price": 8782,
		"rarity": "Common",
		"droprate": null,
		"type": "weapons",
		"img": "/img/rs3/rune_crossbow.png",
		"game": "rs3",
		"boss": "Armadyl",
		"npc": "Kree'arra"
	},
	{
		"title": "Runite bolts",
		"quantity": 20,
		"price": 310,
		"rarity": "Common",
		"droprate": null,
		"type": "weapons",
		"img": "/img/rs3/runite_bolts.png",
		"game": "rs3",
		"boss": "Armadyl",
		"npc": "Kree'arra"
	},
	{
		"title": "Rune arrow",
		"quantity": 103,
		"price": 152,
		"rarity": "Common",
		"droprate": null,
		"type": "weapons",
		"img": "/img/rs3/rune_arrow.png",
		"game": "rs3",
		"boss": "Armadyl",
		"npc": "Kree'arra"
	},
	{
		"title": "Rune longsword",
		"quantity": 1,
		"price": 18372,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "weapons",
		"img": "/img/rs3/rune_longsword.png",
		"game": "rs3",
		"boss": "Armadyl",
		"npc": "Kree'arra"
	},
	{
		"title": "Dragon bolts (e)",
		"quantity": 7,
		"price": 462,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "weapons",
		"img": "/img/rs3/dragon_bolts_e.png",
		"game": "rs3",
		"boss": "Armadyl",
		"npc": "Kree'arra"
	},
	{
		"title": "Black d'hide body",
		"quantity": 1,
		"price": 7713,
		"rarity": "Common",
		"droprate": null,
		"type": "Armour",
		"img": "/img/rs3/black_dhide_body.png",
		"game": "rs3",
		"boss": "Armadyl",
		"npc": "Kree'arra"
	},
	{
		"title": "Armadyl helmet",
		"quantity": 1,
		"price": 336095,
		"rarity": "Rare",
		"droprate": 299,
		"type": "Armour",
		"img": "/img/rs3/armadyl_helmet.png",
		"game": "rs3",
		"boss": "Armadyl",
		"npc": "Kree'arra"
	},
	{
		"title": "Armadyl chestplate",
		"quantity": 1,
		"price": 3303840,
		"rarity": "Rare",
		"droprate": 313,
		"type": "Armour",
		"img": "/img/rs3/armadyl_chestplate.png",
		"game": "rs3",
		"boss": "Armadyl",
		"npc": "Kree'arra"
	},
	{
		"title": "Armadyl chainskirt",
		"quantity": 1,
		"price": 3160146,
		"rarity": "Rare",
		"droprate": 282,
		"type": "Armour",
		"img": "/img/rs3/armadyl_chainskirt.png",
		"game": "rs3",
		"boss": "Armadyl",
		"npc": "Kree'arra"
	},
	{
		"title": "Armadyl boots",
		"quantity": 1,
		"price": 2699364,
		"rarity": "Rare",
		"droprate": null,
		"type": "Armour",
		"img": "/img/rs3/armadyl_boots.png",
		"game": "rs3",
		"boss": "Armadyl",
		"npc": "Kree'arra"
	},
	{
		"title": "Armadyl gloves",
		"quantity": 1,
		"price": 849178,
		"rarity": "Rare",
		"droprate": null,
		"type": "Armour",
		"img": "/img/rs3/armadyl_gloves.png",
		"game": "rs3",
		"boss": "Armadyl",
		"npc": "Kree'arra"
	},
	{
		"title": "Armadyl buckler",
		"quantity": 1,
		"price": 29229,
		"rarity": "Rare",
		"droprate": null,
		"type": "Armour",
		"img": "/img/rs3/armadyl_buckler.png",
		"game": "rs3",
		"boss": "Armadyl",
		"npc": "Kree'arra"
	},
	{
		"title": "Warpriest of Armadyl helm",
		"quantity": 1,
		"price": null,
		"rarity": "Varies",
		"droprate": null,
		"type": "Armour",
		"img": "/img/rs3/warpriest_of_armadyl_helm.png",
		"game": "rs3",
		"boss": "Armadyl",
		"npc": "Kree'arra"
	},
	{
		"title": "Warpriest of Armadyl cuirass",
		"quantity": 1,
		"price": null,
		"rarity": "Varies",
		"droprate": null,
		"type": "Armour",
		"img": "/img/rs3/warpriest_of_armadyl_cuirass.png",
		"game": "rs3",
		"boss": "Armadyl",
		"npc": "Kree'arra"
	},
	{
		"title": "Warpriest of Armadyl greaves",
		"quantity": 1,
		"price": null,
		"rarity": "Varies",
		"droprate": null,
		"type": "Armour",
		"img": "/img/rs3/warpriest_of_armadyl_greaves.png",
		"game": "rs3",
		"boss": "Armadyl",
		"npc": "Kree'arra"
	},
	{
		"title": "Warpriest of Armadyl gauntlets",
		"quantity": 1,
		"price": null,
		"rarity": "Varies",
		"droprate": null,
		"type": "Armour",
		"img": "/img/rs3/warpriest_of_armadyl_gauntlets.png",
		"game": "rs3",
		"boss": "Armadyl",
		"npc": "Kree'arra"
	},
	{
		"title": "Warpriest of Armadyl boots",
		"quantity": 1,
		"price": null,
		"rarity": "Varies",
		"droprate": null,
		"type": "Armour",
		"img": "/img/rs3/warpriest_of_armadyl_boots.png",
		"game": "rs3",
		"boss": "Armadyl",
		"npc": "Kree'arra"
	},
	{
		"title": "Warpriest of Armadyl cape",
		"quantity": 1,
		"price": null,
		"rarity": "Varies",
		"droprate": null,
		"type": "Armour",
		"img": "/img/rs3/warpriest_of_armadyl_cape.png",
		"game": "rs3",
		"boss": "Armadyl",
		"npc": "Kree'arra"
	},
	{
		"title": "Super ranging potion (3)",
		"quantity": 3,
		"price": 8292,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "Potion",
		"img": "/img/rs3/super_ranging_potion_3.png",
		"game": "rs3",
		"boss": "Armadyl",
		"npc": "Kree'arra"
	},
	{
		"title": "Super defence (3)",
		"quantity": 3,
		"price": 3014,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "Potion",
		"img": "/img/rs3/super_defence_3.png",
		"game": "rs3",
		"boss": "Armadyl",
		"npc": "Kree'arra"
	},
	{
		"title": "Coins",
		"quantity": 19500,
		"price": 1,
		"rarity": "Common",
		"droprate": null,
		"type": "Other",
		"img": "/img/rs3/coins.png",
		"game": "rs3",
		"boss": "Armadyl",
		"npc": "Kree'arra"
	},
	{
		"title": "Grimy dwarf weed",
		"quantity": 13,
		"price": 6334,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "Other",
		"img": "/img/rs3/grimy_dwarf_weed.png",
		"game": "rs3",
		"boss": "Armadyl",
		"npc": "Kree'arra"
	},
	{
		"title": "Dwarf weed seed",
		"quantity": 3,
		"price": 15624,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "Other",
		"img": "/img/rs3/dwarf_weed_seed.png",
		"game": "rs3",
		"boss": "Armadyl",
		"npc": "Kree'arra"
	},
	{
		"title": "Curved bone",
		"quantity": 1,
		"price": null,
		"rarity": "Rare",
		"droprate": null,
		"type": "Other",
		"img": "/img/rs3/curved_bone.png",
		"game": "rs3",
		"boss": "Armadyl",
		"npc": "Kree'arra"
	},
	{
		"title": "Long bone",
		"quantity": 1,
		"price": null,
		"rarity": "Rare",
		"droprate": null,
		"type": "Other",
		"img": "/img/rs3/long_bone.png",
		"game": "rs3",
		"boss": "Armadyl",
		"npc": "Kree'arra"
	},
	{
		"title": "Starved ancient effigy",
		"quantity": 1,
		"price": null,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "Other",
		"img": "/img/rs3/starved_ancient_effigy.png",
		"game": "rs3",
		"boss": "Armadyl",
		"npc": "Kree'arra"
	},
	{
		"title": "Yew seed",
		"quantity": 1,
		"price": 67300,
		"rarity": "Rare",
		"droprate": null,
		"type": "Other",
		"img": "/img/rs3/yew_seed.png",
		"game": "rs3",
		"boss": "Armadyl",
		"npc": "Kree'arra"
	},
	{
		"title": "Godsword shard 1",
		"quantity": 1,
		"price": 147141,
		"rarity": "Rare",
		"droprate": "502",
		"type": "Other",
		"img": "/img/rs3/godsword_shard_1.png",
		"game": "rs3",
		"boss": "Armadyl",
		"npc": "Kree'arra"
	},
	{
		"title": "Godsword shard 2",
		"quantity": 1,
		"price": 146960,
		"rarity": "Rare",
		"droprate": 539,
		"type": "Other",
		"img": "/img/rs3/godsword_shard_2.png",
		"game": "rs3",
		"boss": "Armadyl",
		"npc": "Kree'arra"
	},
	{
		"title": "Godsword shard 3",
		"quantity": 1,
		"price": 147075,
		"rarity": "Rare",
		"droprate": 539,
		"type": "Other",
		"img": "/img/rs3/godsword_shard_3.png",
		"game": "rs3",
		"boss": "Armadyl",
		"npc": "Kree'arra"
	},
	{
		"title": "Armadyl hilt",
		"quantity": 1,
		"price": 1099520,
		"rarity": "Rare",
		"droprate": 353,
		"type": "Other",
		"img": "/img/rs3/armadyl_hilt.png",
		"game": "rs3",
		"boss": "Armadyl",
		"npc": "Kree'arra"
	},
	{
		"title": "Armadyl's assault",
		"quantity": 1,
		"price": null,
		"rarity": "Rare",
		"droprate": null,
		"type": "Other",
		"img": "/img/rs3/armadyls_assault.png",
		"game": "rs3",
		"boss": "Armadyl",
		"npc": "Kree'arra"
	},
	{
		"title": "Spirit sapphire",
		"quantity": 1,
		"price": null,
		"rarity": "Rare",
		"droprate": null,
		"type": "Other",
		"img": "/img/rs3/spirit_sapphire.png",
		"game": "rs3",
		"boss": "Armadyl",
		"npc": "Kree'arra"
	},
	{
		"title": "Spirit emerald",
		"quantity": 1,
		"price": null,
		"rarity": "Rare",
		"droprate": null,
		"type": "Other",
		"img": "/img/rs3/spirit_emerald.png",
		"game": "rs3",
		"boss": "Armadyl",
		"npc": "Kree'arra"
	},
	{
		"title": "Spirit ruby",
		"quantity": 1,
		"price": null,
		"rarity": "Rare",
		"droprate": null,
		"type": "Other",
		"img": "/img/rs3/spirit_ruby.png",
		"game": "rs3",
		"boss": "Armadyl",
		"npc": "Kree'arra"
	},
	{
		"title": "Clue scroll (hard)",
		"quantity": 1,
		"price": null,
		"rarity": "Rare",
		"droprate": null,
		"type": "Other",
		"img": "/img/rs3/clue_scroll_hard.png",
		"game": "rs3",
		"boss": "Armadyl",
		"npc": "Kree'arra"
	},
	{
		"title": "Clue scroll (elite)",
		"quantity": 1,
		"price": null,
		"rarity": "Rare",
		"droprate": null,
		"type": "Other",
		"img": "/img/rs3/clue_scroll_elite.png",
		"game": "rs3",
		"boss": "Armadyl",
		"npc": "Kree'arra"
	},
	{
		"title": "Crystal key",
		"quantity": 1,
		"price": 60232,
		"rarity": "Rare",
		"droprate": null,
		"type": "Other",
		"img": "/img/rs3/crystal_key.png",
		"game": "rs3",
		"boss": "Armadyl",
		"npc": "Kree'arra"
	},
	{
		"title": "Giant feather",
		"quantity": 1,
		"price": null,
		"rarity": "Very rare",
		"droprate": 5000,
		"type": "Other",
		"img": "/img/rs3/giant_feather.png",
		"game": "rs3",
		"boss": "Armadyl",
		"npc": "Kree'arra"
	}
];

