/*
* RS3 Bandos drops list made by Richard (Hellworms).
*/

BandosDropsRs3 = [
	{
		"title": "Rune longswod",
		"quantity": 1,
		"price": 18372,
		"rarity": "Common",
		"droprate": null,
		"type": "weapons",
		"img": "/img/rs3/rune_longsword.png",
		"game": "rs3",
		"boss": "Bandos",
		"npc": "General Graardor"
	},
	{
		"title": "Rune 2h sword",
		"quantity": 1,
		"price": 37338,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "weapons",
		"img": "/img/rs3/rune_2h_sword.png",
		"game": "rs3",
		"boss": "Bandos",
		"npc": "General Graardor"
	},
	{
		"title": "Rune pickaxe",
		"quantity": 1,
		"price": 18629,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "weapons",
		"img": "/img/rs3/rune_pickaxe.png",
		"game": "rs3",
		"boss": "Bandos",
		"npc": "General Graardor"
	},
	{
		"title": "Rune platebody",
		"quantity": 1,
		"price": 38171,
		"rarity": "Common",
		"droprate": null,
		"type": "Armour",
		"img": "/img/rs3/rune_platebody.png",
		"game": "rs3",
		"boss": "Bandos",
		"npc": "General Graardor"
	},
	{
		"title": "Bandos chestplate",
		"quantity": 1,
		"price": 1749437,
		"rarity": "Rare",
		"droprate": 282,
		"type": "Armour",
		"img": "/img/rs3/bandos_chestplate.png",
		"game": "rs3",
		"boss": "Bandos",
		"npc": "General Graardor"
	},
	{
		"title": "Bandos tassets",
		"quantity": 1,
		"price": 1384435,
		"rarity": "Rare",
		"droprate": 272,
		"type": "Armour",
		"img": "/img/rs3/bandos_tassets.png",
		"game": "rs3",
		"boss": "Bandos",
		"npc": "General Graardor"
	},
	{
		"title": "Bandos boots",
		"quantity": 1,
		"price": 975049,
		"rarity": "Rare",
		"droprate": 276,
		"type": "Armour",
		"img": "/img/rs3/bandos_boots.png",
		"game": "rs3",
		"boss": "Bandos",
		"npc": "General Graardor"
	},
	{
		"title": "Bandos gloves",
		"quantity": 1,
		"price": 974776,
		"rarity": "Rare",
		"droprate": null,
		"type": "Armour",
		"img": "/img/rs3/bandos_gloves.png",
		"game": "rs3",
		"boss": "Bandos",
		"npc": "General Graardor"
	},
	{
		"title": "Bandos warshield",
		"quantity": 1,
		"price": 28571,
		"rarity": "Rare",
		"droprate": null,
		"type": "Armour",
		"img": "/img/rs3/bandos_warshield.png",
		"game": "rs3",
		"boss": "Bandos",
		"npc": "General Graardor"
	},
	{
		"title": "Bandos helmet",
		"quantity": 1,
		"price": 472564,
		"rarity": "Rare",
		"droprate": null,
		"type": "Armour",
		"img": "/img/rs3/bandos_helmet.png",
		"game": "rs3",
		"boss": "Bandos",
		"npc": "General Graardor"
	},
	{
		"title": "Warpriest of Bandos helm",
		"quantity": 1,
		"price": null,
		"rarity": "Varies",
		"droprate": null,
		"type": "Armour",
		"img": "/img/rs3/warpriest_of_bandos_helm.png",
		"game": "rs3",
		"boss": "Bandos",
		"npc": "General Graardor"
	},
	{
		"title": "Warpriest of Bandos cuirass",
		"quantity": 1,
		"price": null,
		"rarity": "Varies",
		"droprate": null,
		"type": "Aromour",
		"img": "/img/rs3/warpriest_of_bandos_cuirass.png",
		"game": "rs3",
		"boss": "Bandos",
		"npc": "General Graardor"
	},
	{
		"title": "Warpriest of Bandos greaves",
		"quantity": 1,
		"price": null,
		"rarity": "Varies",
		"droprate": null,
		"type": "Armour",
		"img": "/img/rs3/warpriest_of_bandos_greaves.png",
		"game": "rs3",
		"boss": "Bandos",
		"npc": "General Graardor"
	},
	{
		"title": "Warpriest of Bandos gauntlets",
		"quantity": 1,
		"price": null,
		"rarity": "Varies",
		"droprate": null,
		"type": "Armour",
		"img": "/img/rs3/warpriest_of_bandos_gauntlets.png",
		"game": "rs3",
		"boss": "Bandos",
		"npc": "General Graardor"
	},
	{
		"title": "Warpriest of Bandos boots",
		"quantity": 1,
		"price": null,
		"rarity": "Varies",
		"droprate": null,
		"type": "Armour",
		"img": "/img/rs3/warpriest_of_bandos_boots.png",
		"game": "rs3",
		"boss": "Bandos",
		"npc": "General Graardor"
	},
	{
		"title": "Warpriest of Bandos cape",
		"quantity": 1,
		"price": null,
		"rarity": "Varies",
		"droprate": null,
		"type": "Armour",
		"img": "/img/rs3/warpriest_of_bandos_cape.png",
		"game": "rs3",
		"boss": "Bandos",
		"npc": "General Graardor"
	},
	{
		"title": "Runite ore",
		"quantity": 2,
		"price": 11053,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "Runes, gems and ores",
		"img": "/img/rs3/runite_ore.png",
		"game": "rs3",
		"boss": "Bandos",
		"npc": "General Graardor"
	},
	{
		"title": "Coal",
		"quantity": 117,
		"price": 314,
		"rarity": "Common",
		"droprate": null,
		"type": "Runes, gems and ores",
		"img": "/img/rs3/coal.png",
		"game": "rs3",
		"boss": "Bandos",
		"npc": "General Graardor"
	},
	{
		"title": "Adamantite ore",
		"quantity": 17,
		"price": 1401,
		"rarity": "Common",
		"droprate": null,
		"type": "Runes, gems and ores",
		"img": "/img/rs3/adamantite_ore.png",
		"game": "rs3",
		"boss": "Bandos",
		"npc": "General Graardor"
	},
	{
		"title": "Coins",
		"quantity": 20000,
		"price": 1,
		"rarity": "Common",
		"droprate": null,
		"type": "Other",
		"img": "/img/rs3/coins.png",
		"game": "rs3",
		"boss": "Bandos",
		"npc": "General Graardor"
	},
	{
		"title": "Snapdragon seed",
		"quantity": 1,
		"price": 535,
		"rarity": "Common",
		"droprate": null,
		"type": "Other",
		"img": "/img/rs3/snapdragon_seed.png",
		"game": "rs3",
		"boss": "Bandos",
		"npc": "General Graardor"
	},
	{
		"title": "Femur bone",
		"quantity": 1,
		"price": null,
		"rarity": "Common",
		"droprate": null,
		"type": "Other",
		"img": "/img/rs3/femur_bone.png",
		"game": "rs3",
		"boss": "Bandos",
		"npc": "General Graardor"
	},
	{
		"title": "Magic logs",
		"quantity": 17,
		"price": 911,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "Other",
		"img": "/img/rs3/magic_logs.png",
		"game": "rs3",
		"boss": "Bandos",
		"npc": "General Graardor"
	},
	{
		"title": "Super restore (4)",
		"quantity": 3,
		"price": 3449,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "Other",
		"img": "/img/rs3/super_restore_4.png",
		"game": "rs3",
		"boss": "Bandos",
		"npc": "General Graardor"
	},
	{
		"title": "Grimy snapdragon",
		"quantity": 3,
		"price": 3664,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "Other",
		"img": "/img/rs3/grimy_snapdragon.png",
		"game": "rs3",
		"boss": "Bandos",
		"npc": "General Graardor"
	},
	{
		"title": "Long bone",
		"quantity": 1,
		"price": null,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "Other",
		"img": "/img/rs3/long_bone.png",
		"game": "rs3",
		"boss": "Bandos",
		"npc": "General Graardor"
	},
	{
		"title": "Curved bone",
		"quantity": 1,
		"price": null,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "Other",
		"img": "/img/rs3/curved_bone.png",
		"game": "rs3",
		"boss": "Bandos",
		"npc": "General Graardor"
	},
	{
		"title": "Godsword shard 1",
		"quantity": 1,
		"price": 147141,
		"rarity": "Rare",
		"droprate": 508,
		"type": "Other",
		"img": "/img/rs3/godsword_shard_1.png",
		"game": "rs3",
		"boss": "Bandos",
		"npc": "General Graardor"
	},
	{
		"title": "Godsword shard 2",
		"quantity": 1,
		"price": 146960,
		"rarity": "Rare",
		"droprate": 554,
		"type": "Other",
		"img": "/img/rs3/godsword_shard_2.png",
		"game": "rs3",
		"boss": "Bandos",
		"npc": "General Graardor"
	},
	{
		"title": "Godsword shard 3",
		"quantity": 1,
		"price": 147075,
		"rarity": "Rare",
		"droprate": 508,
		"type": "Other",
		"img": "/img/rs3/godsword_shard_3.png",
		"game": "rs3",
		"boss": "Bandos",
		"npc": "General Graardor"
	},
	{
		"title": "Bandos hilt",
		"quantity": 1,
		"price": 299813,
		"rarity": "Rare",
		"droprate": 390,
		"type": "Other",
		"img": "/img/rs3/bandos_hilt.png",
		"game": "rs3",
		"boss": "Bandos",
		"npc": "General Graardor"
	},
	{
		"title": "Clue scroll (hard)",
		"quantity": 1,
		"price": null,
		"rarity": "Rare",
		"droprate": null,
		"type": "Other",
		"img": "/img/rs3/clue_scroll_hard.png",
		"game": "rs3",
		"boss": "Bandos",
		"npc": "General Graardor"
	},
	{
		"title": "Spirit sapphire",
		"quantity": 1,
		"price": null,
		"rarity": "Rare",
		"droprate": null,
		"type": "Other",
		"img": "/img/rs3/spirit_sapphire.png",
		"game": "rs3",
		"boss": "Bandos",
		"npc": "General Graardor"
	},
	{
		"title": "Spirit emerald",
		"quantity": 1,
		"price": null,
		"rarity": "Rare",
		"droprate": null,
		"type": "Other",
		"img": "/img/rs3/spirit_emerald.png",
		"game": "rs3",
		"boss": "Bandos",
		"npc": "General Graardor"
	},
	{
		"title": "Spirit ruby",
		"quantity": 1,
		"price": null,
		"rarity": "Rare",
		"droprate": null,
		"type": "Other",
		"img": "/img/rs3/spirit_ruby.png",
		"game": "rs3",
		"boss": "Bandos",
		"npc": "General Graardor"
	},
	{
		"title": "Starved ancient effigy",
		"quantity": 1,
		"price": null,
		"rarity": "Rare",
		"droprate": null,
		"type": "Other",
		"img": "/img/rs3/starved_ancient_effigy.png",
		"game": "rs3",
		"boss": "Bandos",
		"npc": "General Graardor"
	},
	{
		"title": "The glory of general graardor",
		"quantity": 1,
		"price": null,
		"rarity": "Rare",
		"droprate": null,
		"type": "Other",
		"img": "/img/rs3/the_glory_of_general_graardor.png",
		"game": "rs3",
		"boss": "Bandos",
		"npc": "General Graardor"
	},
	{
		"title": "Clue scroll (elite)",
		"quantity": 1,
		"price": null,
		"rarity": "Rare",
		"droprate": null,
		"type": "Other",
		"img": "/img/rs3/clue_scroll_elite.png",
		"game": "rs3",
		"boss": "Bandos",
		"npc": "General Graardor"
	},
	{
		"title": "Decaying tooth",
		"quantity": 1,
		"price": null,
		"rarity": "Very rare",
		"droprate": null,
		"type": "Other",
		"img": "/img/rs3/decaying_tooth.png",
		"game": "rs3",
		"boss": "Bandos",
		"npc": "General Graardor"
	}
]
