/*
* RS3 Barrows (classic) drops list made by Aimer.
*/

BarrowsDropsRs3 = [
	{
		"title": "Barrows icon",
		"quantity": 1,
		"price": null,
		"rarity": "Always",
		"droprate": null,
		"type": "Drops",
		"img": "/img/rs3/barrows_icon.png",
		"game": "rs3",
		"boss": "Barrows",
		"npc": "Barrows"
	},
	{
		"title": "Coins",
		"quantity": 800,
		"price": 1,
		"rarity": "Common",
		"droprate": null,
		"type": "Drops",
		"img": "/img/rs3/coins.png",
		"game": "rs3",
		"boss": "Barrows",
		"npc": "Barrows"
	},
	{
		"title": "60x Mind rune",
		"quantity": 60,
		"price": 15,
		"rarity": "Common",
		"droprate": null,
		"type": "Drops",
		"img": "/img/rs3/mind_rune.png",
		"game": "rs3",
		"boss": "Barrows",
		"npc": "Barrows"
	},
	{
		"title": "2700x Mind rune",
		"quantity": 2700,
		"price": 15,
		"rarity": "Common",
		"droprate": null,
		"type": "Drops",
		"img": "/img/rs3/mind_rune.png",
		"game": "rs3",
		"boss": "Barrows",
		"npc": "Barrows"
	},
	{
		"title": "Chaos rune",
		"quantity": 1100,
		"price": 44,
		"rarity": "Common",
		"droprate": null,
		"type": "Drops",
		"img": "/img/rs3/chaos_rune.png",
		"game": "rs3",
		"boss": "Barrows",
		"npc": "Barrows"
	},
	{
		"title": "15x Death rune",
		"quantity": 15,
		"price": 348,
		"rarity": "Common",
		"droprate": null,
		"type": "Drops",
		"img": "/img/rs3/death_rune.png",
		"game": "rs3",
		"boss": "Barrows",
		"npc": "Barrows"
	},
	{
		"title": "700x Death rune",
		"quantity": 700,
		"price": 348,
		"rarity": "Common",
		"droprate": null,
		"type": "Drops",
		"img": "/img/rs3/death_rune.png",
		"game": "rs3",
		"boss": "Barrows",
		"npc": "Barrows"
	},
	{
		"title": "Blood rune",
		"quantity": 400,
		"price": 448,
		"rarity": "Common",
		"droprate": null,
		"type": "Drops",
		"img": "/img/rs3/blood_rune.png",
		"game": "rs3",
		"boss": "Barrows",
		"npc": "Barrows"
	},
	{
		"title": "Bolt rack",
		"quantity": 160,
		"price": 508,
		"rarity": "Common",
		"droprate": null,
		"type": "Drops",
		"img": "/img/rs3/bolt_rack.png",
		"game": "rs3",
		"boss": "Barrows",
		"npc": "Barrows"
	},
	{
		"title": "Super defence (2)",
		"quantity": 1,
		"price": 1815,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "Drops",
		"img": "/img/rs3/super_defence_(2).png",
		"game": "rs3",
		"boss": "Barrows",
		"npc": "Barrows"
	},
	{
		"title": "Prayer potion (2)",
		"quantity": 1,
		"price": 1319,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "Drops",
		"img": "/img/rs3/prayer_potion_(2).png",
		"game": "rs3",
		"boss": "Barrows",
		"npc": "Barrows"
	},
	{
		"title": "Restore potion (2)",
		"quantity": 1,
		"price": 17,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "Drops",
		"img": "/img/rs3/restore_potion_(2).png",
		"game": "rs3",
		"boss": "Barrows",
		"npc": "Barrows"
	},
	{
		"title": "Shark",
		"quantity": 4,
		"price": 705,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "Drops",
		"img": "/img/rs3/shark.png",
		"game": "rs3",
		"boss": "Barrows",
		"npc": "Barrows"
	},
	{
		"title": "Barrows totem",
		"quantity": 7,
		"price": 2139,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "Drops",
		"img": "/img/rs3/barrows_totem.png",
		"game": "rs3",
		"boss": "Barrows",
		"npc": "Barrows"
	},
	{
		"title": "Loop half of a key",
		"quantity": 1,
		"price": 18017,
		"rarity": "Rare",
		"droprate": null,
		"type": "Drops",
		"img": "/img/rs3/loop_half_of_a_key.png",
		"game": "rs3",
		"boss": "Barrows",
		"npc": "Barrows"
	},
	{
		"title": "Tooth half of a key",
		"quantity": 1,
		"price": 40714,
		"rarity": "Rare",
		"droprate": null,
		"type": "Drops",
		"img": "/img/rs3/tooth_half_of_a_key.png",
		"game": "rs3",
		"boss": "Barrows",
		"npc": "Barrows"
	},
	{
		"title": "Dragon helm",
		"quantity": 1,
		"price": 59040,
		"rarity": "Rare",
		"droprate": null,
		"type": "Drops",
		"img": "/img/rs3/dragon_helm.png",
		"game": "rs3",
		"boss": "Barrows",
		"npc": "Barrows"
	},
	{
		"title": "Ahrim's hood",
		"quantity": 1,
		"price": 148595,
		"rarity": "Rare",
		"droprate": null,
		"type": "Drops",
		"img": "/img/rs3/ahrim's_hood.png",
		"game": "rs3",
		"boss": "Barrows",
		"npc": "Barrows"
	},
	{
		"title": "Ahrim's robe top",
		"quantity": 1,
		"price": 421778,
		"rarity": "Rare",
		"droprate": null,
		"type": "Drops",
		"img": "/img/rs3/ahrim's_robe_top.png",
		"game": "rs3",
		"boss": "Barrows",
		"npc": "Barrows"
	},
	{
		"title": "Ahrim's robe skirt",
		"quantity": 1,
		"price": 348812,
		"rarity": "Rare",
		"droprate": null,
		"type": "Drops",
		"img": "/img/rs3/ahrim's_robe_skirt.png",
		"game": "rs3",
		"boss": "Barrows",
		"npc": "Barrows"
	},
	{
		"title": "Ahrim's staff",
		"quantity": 1,
		"price": 280963,
		"rarity": "Rare",
		"droprate": null,
		"type": "Drops",
		"img": "/img/rs3/ahrim's_staff.png",
		"game": "rs3",
		"boss": "Barrows",
		"npc": "Barrows"
	},
	{
		"title": "Ahrim's wand",
		"quantity": 1,
		"price": 427922,
		"rarity": "Rare",
		"droprate": null,
		"type": "Drops",
		"img": "/img/rs3/ahrim's_wand.png",
		"game": "rs3",
		"boss": "Barrows",
		"npc": "Barrows"
	},
	{
		"title": "Ahrim's book of magic",
		"quantity": 1,
		"price": 414916,
		"rarity": "Rare",
		"droprate": null,
		"type": "Drops",
		"img": "/img/rs3/ahrim's_book_of_magic.png",
		"game": "rs3",
		"boss": "Barrows",
		"npc": "Barrows"
	},
	{
		"title": "Dharok's helm",
		"quantity": 1,
		"price": 485043,
		"rarity": "Rare",
		"droprate": null,
		"type": "Drops",
		"img": "/img/rs3/dharok's_helm.png",
		"game": "rs3",
		"boss": "Barrows",
		"npc": "Barrows"
	},
	{
		"title": "Dharok's platebody",
		"quantity": 1,
		"price": 375004,
		"rarity": "Rare",
		"droprate": null,
		"type": "Drops",
		"img": "/img/rs3/dharok's_platebody.png",
		"game": "rs3",
		"boss": "Barrows",
		"npc": "Barrows"
	},
	{
		"title": "Dharok's platelegs",
		"quantity": 1,
		"price": 400584,
		"rarity": "Rare",
		"droprate": null,
		"type": "Drops",
		"img": "/img/rs3/dharok's_platelegs.png",
		"game": "rs3",
		"boss": "Barrows",
		"npc": "Barrows"
	},
	{
		"title": "Dharok's greataxe",
		"quantity": 1,
		"price": 555861,
		"rarity": "Rare",
		"droprate": null,
		"type": "Drops",
		"img": "/img/rs3/dharok's_greataxe.png",
		"game": "rs3",
		"boss": "Barrows",
		"npc": "Barrows"
	},
	{
		"title": "Torag's helm",
		"quantity": 1,
		"price": 161262,
		"rarity": "Rare",
		"droprate": null,
		"type": "Drops",
		"img": "/img/rs3/torag's_helm.png",
		"game": "rs3",
		"boss": "Barrows",
		"npc": "Barrows"
	},
	{
		"title": "Torag's platebody",
		"quantity": 1,
		"price": 302661,
		"rarity": "Rare",
		"droprate": null,
		"type": "Drops",
		"img": "/img/rs3/torag's_platebody.png",
		"game": "rs3",
		"boss": "Barrows",
		"npc": "Barrows"
	},
	{
		"title": "Torag's platelegs",
		"quantity": 1,
		"price": 273112,
		"rarity": "Rare",
		"droprate": null,
		"type": "Drops",
		"img": "/img/rs3/torag's_platelegs.png",
		"game": "rs3",
		"boss": "Barrows",
		"npc": "Barrows"
	},
	{
		"title": "Torag's hammer",
		"quantity": 1,
		"price": 146080,
		"rarity": "Rare",
		"droprate": null,
		"type": "Drops",
		"img": "/img/rs3/torag's_hammer.png",
		"game": "rs3",
		"boss": "Barrows",
		"npc": "Barrows"
	},
	{
		"title": "Verac's helm",
		"quantity": 1,
		"price": 178068,
		"rarity": "Rare",
		"droprate": null,
		"type": "Drops",
		"img": "/img/rs3/verac's_helm.png",
		"game": "rs3",
		"boss": "Barrows",
		"npc": "Barrows"
	},
	{
		"title": "Verac's brassard",
		"quantity": 1,
		"price": 340919,
		"rarity": "Rare",
		"droprate": null,
		"type": "Drops",
		"img": "/img/rs3/verac's_brassard.png",
		"game": "rs3",
		"boss": "Barrows",
		"npc": "Barrows"
	},
	{
		"title": "Verac's plateskirt",
		"quantity": 1,
		"price": 288452,
		"rarity": "Rare",
		"droprate": null,
		"type": "Drops",
		"img": "/img/rs3/verac's_plateskirt.png",
		"game": "rs3",
		"boss": "Barrows",
		"npc": "Barrows"
	},
	{
		"title": "Verac's flail",
		"quantity": 1,
		"price": 170400,
		"rarity": "Rare",
		"droprate": null,
		"type": "Drops",
		"img": "/img/rs3/verac's_flail.png",
		"game": "rs3",
		"boss": "Barrows",
		"npc": "Barrows"
	},
	{
		"title": "Guthan's helm",
		"quantity": 1,
		"price": 799368,
		"rarity": "Rare",
		"droprate": null,
		"type": "Drops",
		"img": "/img/rs3/guthan's_helm.png",
		"game": "rs3",
		"boss": "Barrows",
		"npc": "Barrows"
	},
	{
		"title": "Guthan's platebody",
		"quantity": 1,
		"price": 756821,
		"rarity": "Rare",
		"droprate": null,
		"type": "Drops",
		"img": "/img/rs3/guthan's_platebody.png",
		"game": "rs3",
		"boss": "Barrows",
		"npc": "Barrows"
	},
	{
		"title": "Guthan's chainskirt",
		"quantity": 1,
		"price": 813227,
		"rarity": "Rare",
		"droprate": null,
		"type": "Drops",
		"img": "/img/rs3/guthan's_chainskirt.png",
		"game": "rs3",
		"boss": "Barrows",
		"npc": "Barrows"
	},
	{
		"title": "Guthan's warspear",
		"quantity": 1,
		"price": 1200961,
		"rarity": "Rare",
		"droprate": null,
		"type": "Drops",
		"img": "/img/rs3/guthan's_warspear.png",
		"game": "rs3",
		"boss": "Barrows",
		"npc": "Barrows"
	},
	{
		"title": "Karil's coif",
		"quantity": 1,
		"price": 270339,
		"rarity": "Rare",
		"droprate": null,
		"type": "Drops",
		"img": "/img/rs3/karil's_coif.png",
		"game": "rs3",
		"boss": "Barrows",
		"npc": "Barrows"
	},
	{
		"title": "Karil's top",
		"quantity": 1,
		"price": 372082,
		"rarity": "Rare",
		"droprate": null,
		"type": "Drops",
		"img": "/img/rs3/karil's_top.png",
		"game": "rs3",
		"boss": "Barrows",
		"npc": "Barrows"
	},
	{
		"title": "Karil's skirt",
		"quantity": 1,
		"price": 352163,
		"rarity": "Rare",
		"droprate": null,
		"type": "Drops",
		"img": "/img/rs3/karil's_skirt.png",
		"game": "rs3",
		"boss": "Barrows",
		"npc": "Barrows"
	},
	{
		"title": "Karil's crossbow",
		"quantity": 1,
		"price": 188254,
		"rarity": "Rare",
		"droprate": null,
		"type": "Drops",
		"img": "/img/rs3/karil's_crossbow.png",
		"game": "rs3",
		"boss": "Barrows",
		"npc": "Barrows"
	},
	{
		"title": "Karil's pistol crossbow",
		"quantity": 1,
		"price": 1297946,
		"rarity": "Rare",
		"droprate": null,
		"type": "Drops",
		"img": "/img/rs3/karil's_pistol_crossbow.png",
		"game": "rs3",
		"boss": "Barrows",
		"npc": "Barrows"
	},
	{
		"title": "Karil's off-hand pistol crossbow",
		"quantity": 1,
		"price": 780309,
		"rarity": "Rare",
		"droprate": null,
		"type": "Drops",
		"img": "/img/rs3/karil's_off-hand_pistol_crossbow.png",
		"game": "rs3",
		"boss": "Barrows",
		"npc": "Barrows"
	},
	{
		"title": "Akrisae's hood",
		"quantity": 1,
		"price": 82992,
		"rarity": "Rare",
		"droprate": null,
		"type": "Drops",
		"img": "/img/rs3/akrisae's_hood.png",
		"game": "rs3",
		"boss": "Barrows",
		"npc": "Barrows"
	},
	{
		"title": "Akrisae's robe top",
		"quantity": 1,
		"price": 150025,
		"rarity": "Rare",
		"droprate": null,
		"type": "Drops",
		"img": "/img/rs3/akrisae's_robe_top.png",
		"game": "rs3",
		"boss": "Barrows",
		"npc": "Barrows"
	},
	{
		"title": "Akrisae's robe skirt",
		"quantity": 1,
		"price": 107097,
		"rarity": "Rare",
		"droprate": null,
		"type": "Drops",
		"img": "/img/rs3/akrisae's_robe_skirt.png",
		"game": "rs3",
		"boss": "Barrows",
		"npc": "Barrows"
	},
	{
		"title": "Akrisae's war mace",
		"quantity": 1,
		"price": 63142,
		"rarity": "Rare",
		"droprate": null,
		"type": "Drops",
		"img": "/img/rs3/akrisae's_war_mace.png",
		"game": "rs3",
		"boss": "Barrows",
		"npc": "Barrows"
	},
	{
		"title": "Crystal triskelion fragment 1",
		"quantity": 1,
		"price": null,
		"rarity": "Very rare",
		"droprate": null,
		"type": "Drops",
		"img": "/img/rs3/crystal_triskelion_fragment_1.png",
		"game": "rs3",
		"boss": "Barrows",
		"npc": "Barrows"
	},
	{
		"title": "Crystal triskelion fragment 2",
		"quantity": 1,
		"price": null,
		"rarity": "Very rare",
		"droprate": null,
		"type": "Drops",
		"img": "/img/rs3/crystal_triskelion_fragment_2.png",
		"game": "rs3",
		"boss": "Barrows",
		"npc": "Barrows"
	},
	{
		"title": "Crystal triskelion fragment 3",
		"quantity": 1,
		"price": null,
		"rarity": "Very rare",
		"droprate": null,
		"type": "Drops",
		"img": "/img/rs3/crystal_triskelion_fragment_3.png",
		"game": "rs3",
		"boss": "Barrows",
		"npc": "Barrows"
	}
];