/*
* OSRS Calisto drops list made by Mokuin.
*/

CallistoDrops = [
	{
		"title": "Rune pickaxe",
		"quantity": 1,
		"price": 19627,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "weapons",
		"img": "/img/osrs/rune_pickaxe.png",
		"game": "osrs",
		"boss": "Callisto",
		"npc": "Callisto"
	},
	{
		"title": "Rune 2h sword",
		"quantity": 1,
		"price": 41593,
		"rarity": "Rare",
		"droprate": null,
		"type": "weapons",
		"img": "/img/osrs/rune_2h_sword.png",
		"game": "osrs",
		"boss": "Callisto",
		"npc": "Callisto"
	},
	{
		"title": "Dragon pickaxe",
		"quantity": 1,
		"price": 1930220,
		"rarity": "Rare",
		"droprate": 256,
		"type": "weapons",
		"img": "/img/osrs/dragon_pickaxe.png",
		"game": "osrs",
		"boss": "Callisto",
		"npc": "Callisto"
	},
	{
		"title": "Dragon 2h sword",
		"quantity": 1,
		"price": 158534,
		"rarity": "Rare",
		"droprate": 256,
		"type": "weapons",
		"img": "/img/osrs/dragon_2h_sword.png",
		"game": "osrs",
		"boss": "Callisto",
		"npc": "Callisto"
	},
	{
		"title": "Tyrannical ring",
		"quantity": 1,
		"price": 1264023,
		"rarity": "Rare",
		"droprate": 512,
		"type": "weapons",
		"img": "/img/osrs/tyrannical_ring.png",
		"game": "osrs",
		"boss": "Callisto",
		"npc": "Callisto"
	},
	{
		"title": "Soul rune",
		"quantity": 250,
		"price": 168,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "runes",
		"img": "/img/osrs/soul_rune.png",
		"game": "osrs",
		"boss": "Callisto",
		"npc": "Callisto"
	},
	{
		"title": "Death rune",
		"quantity": 300,
		"price": 221,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "runes",
		"img": "/img/osrs/death_rune.png",
		"game": "osrs",
		"boss": "Callisto",
		"npc": "Callisto"
	},
	{
		"title": "Chaos rune",
		"quantity": 400,
		"price": 100,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "runes",
		"img": "/img/osrs/chaos_rune.png",
		"game": "osrs",
		"boss": "Callisto",
		"npc": "Callisto"
	},
	{
		"title": "Blood rune",
		"quantity": 200,
		"price": 316,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "runes",
		"img": "/img/osrs/blood_rune.png",
		"game": "osrs",
		"boss": "Callisto",
		"npc": "Callisto"
	},
	{
		"title": "Snapdragon seed",
		"quantity": 3,
		"price": 21702,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "seeds",
		"img": "/img/osrs/snapdragon_seed.png",
		"game": "osrs",
		"boss": "Callisto",
		"npc": "Callisto"
	},
	{
		"title": "Ranarr seed",
		"quantity": 5,
		"price": 17060,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "seeds",
		"img": "/img/osrs/ranarr_seed.png",
		"game": "osrs",
		"boss": "Callisto",
		"npc": "Callisto"
	},
	{
		"title": "Yew seed",
		"quantity": 1,
		"price": 76784,
		"rarity": "Rare",
		"droprate": null,
		"type": "seeds",
		"img": "/img/osrs/yew_seed.png",
		"game": "osrs",
		"boss": "Callisto",
		"npc": "Callisto"
	},
	{
		"title": "Magic seed",
		"quantity": 1,
		"price": 84581,
		"rarity": "Rare",
		"droprate": null,
		"type": "seeds",
		"img": "/img/osrs/magic_seed.png",
		"game": "osrs",
		"boss": "Callisto",
		"npc": "Callisto"
	},
	{
		"title": "Palm tree seed",
		"quantity": 1,
		"price": 21058,
		"rarity": "Rare",
		"droprate": null,
		"type": "seeds",
		"img": "/img/osrs/palm_tree_seed.png",
		"game": "osrs",
		"boss": "Callisto",
		"npc": "Callisto"
	},
	{
		"title": "Coins",
		"quantity": 16000,
		"price": 1,
		"rarity": "Common",
		"droprate": null,
		"type": "Others",
		"img": "/img/osrs/coins.png",
		"game": "osrs",
		"boss": "Callisto",
		"npc": "Callisto"
	},
	{
		"title": "8 Dark crab + 3 Super restore (4)",
		"quantity": 1,
		"price": 37982,
		"rarity": "Common",
		"droprate": null,
		"type": "Others",
		"img": "/img/osrs/callisto_potion.png",
		"game": "osrs",
		"boss": "Callisto",
		"npc": "Callisto"
	},

	{
		"title": "20 Uncut ruby + 10 Uncut diamond",
		"quantity": 1,
		"price": 62460,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "Others",
		"img": "/img/osrs/callisto_gems.png",
		"game": "osrs",
		"boss": "Callisto",
		"npc": "Callisto"
	},
	{
		"title": "Coconut",
		"quantity": 60,
		"price": 921,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "Others",
		"img": "/img/osrs/coconut.png",
		"game": "osrs",
		"boss": "Callisto",
		"npc": "Callisto"
	},
	{
		"title": "Supercompost",
		"quantity": 100,
		"price": 705,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "Others",
		"img": "/img/osrs/supercompost.png",
		"game": "osrs",
		"boss": "Callisto",
		"npc": "Callisto"
	},
	{
		"title": "Crushed nest",
		"quantity": 75,
		"price": 2248,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "Others",
		"img": "/img/osrs/crushed_nest.png",
		"game": "osrs",
		"boss": "Callisto",
		"npc": "Callisto"
	},
	{
		"title": "Cannonball",
		"quantity": 250,
		"price": 186,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "Others",
		"img": "/img/osrs/cannonball.png",
		"game": "osrs",
		"boss": "Callisto",
		"npc": "Callisto"
	},
	{
		"title": "Magic logs",
		"quantity": 100,
		"price": 1228,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "Others",
		"img": "/img/osrs/magic_logs.png",
		"game": "osrs",
		"boss": "Callisto",
		"npc": "Callisto"
	},
	{
		"title": "Mysterious emblem",
		"quantity": 1,
		"price": null,
		"rarity": "Uncommon",
		"droprate": 12,
		"type": "Others",
		"img": "/img/osrs/mysterious_emblem.png",
		"game": "osrs",
		"boss": "Callisto",
		"npc": "Callisto"
	},
	{
		"title": "Uncut dragonstone",
		"quantity": 1,
		"price": 17401,
		"rarity": "Rare",
		"droprate": null,
		"type": "Others",
		"img": "/img/osrs/uncut_dragonstone.png",
		"game": "osrs",
		"boss": "Callisto",
		"npc": "Callisto"
	},
	{
		"title": "Grimy toadflas",
		"quantity": 100,
		"price": 1824,
		"rarity": "Rare",
		"droprate": null,
		"type": "Others",
		"img": "/img/osrs/grimy_toadflax.png",
		"game": "osrs",
		"boss": "Callisto",
		"npc": "Callisto"
	},
	{
		"title": "Limpwurt root",
		"quantity": 50,
		"price": 1090,
		"rarity": "Rare",
		"droprate": null,
		"type": "Others",
		"img": "/img/osrs/limpwurt_root.png",
		"game": "osrs",
		"boss": "Callisto",
		"npc": "Callisto"
	},
	{
		"title": "Red dragonhide",
		"quantity": 75,
		"price": 2687,
		"rarity": "Rare",
		"droprate": null,
		"type": "Others",
		"img": "/img/osrs/red_dragonhide.png",
		"game": "osrs",
		"boss": "Callisto",
		"npc": "Callisto"
	},
	{
		"title": "Mahogany logs",
		"quantity": 400,
		"price": 71,
		"rarity": "Rare",
		"droprate": null,
		"type": "Others",
		"img": "/img/osrs/mahogany_logs.png",
		"game": "osrs",
		"boss": "Callisto",
		"npc": "Callisto"
	},
	{
		"title": "Dark fishing bait",
		"quantity": 375,
		"price": 53,
		"rarity": "Rare",
		"droprate": null,
		"type": "Others",
		"img": "/img/osrs/dark_fishing_bait.png",
		"game": "osrs",
		"boss": "Callisto",
		"npc": "Callisto"
	},
	{
		"title": "Clue scroll (elite)",
		"quantity": 1,
		"price": null,
		"rarity": "Rare",
		"droprate": 100,
		"type": "Others",
		"img": "/img/osrs/clue_scroll_elite.png",
		"game": "osrs",
		"boss": "Callisto",
		"npc": "Callisto"
	},
	{
		"title": "Callisto cub",
		"quantity": 1,
		"price": null,
		"rarity": "Very rare",
		"droprate": 2000,
		"type": "Others",
		"img": "/img/osrs/callisto_cub.png",
		"game": "osrs",
		"boss": "Callisto",
		"npc": "Callisto"
	}
];

