/*
* OSRS Chaos Fanatic drops list made by Mokuin.
*/

ChaosFanaticDrops = [
	{
		"title": "Zamorak robe (top)",
		"quantity": 1,
		"price": 2528,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "armour",
		"img": "/img/osrs/zamorak_robe_top.png",
		"game": "osrs",
		"boss": "Chaos Fanatic",
		"npc": "Chaos Fanatic"
	},
	{
		"title": "Zamorak robe (botton)",
		"quantity": 1,
		"price": 2368,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "armour",
		"img": "/img/osrs/zamorak_robe_bottom.png",
		"game": "osrs",
		"boss": "Chaos Fanatic",
		"npc": "Chaos Fanatic"
	},
	{
		"title": "Battlestaff",
		"quantity": 5,
		"price": 8235,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "weapons",
		"img": "/img/osrs/battlestaff.png",
		"game": "osrs",
		"boss": "Chaos Fanatic",
		"npc": "Chaos Fanatic"

	},
	{
		"title": "Ring of life",
		"quantity": 1,
		"price": 2018,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "armour",
		"img": "/img/osrs/ring_of_life.png",
		"game": "osrs",
		"boss": "Chaos Fanatic",
		"npc": "Chaos Fanatic"
	},
	{
		"title": "Splitbark body",
		"quantity": 1,
		"price": 37454,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "armour",
		"img": "/img/osrs/splitbark_body.png",
		"game": "osrs",
		"boss": "Chaos Fanatic",
		"npc": "Chaos Fanatic"
	},
	{
		"title": "Splitbark legs",
		"quantity": 1,
		"price": 28119,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "armour",
		"img": "/img/osrs/splitbark_legs.png",
		"game": "osrs",
		"boss": "Chaos Fanatic",
		"npc": "Chaos Fanatic"
	},
	{
		"title": "Ancient staff",
		"quantity": 1,
		"price": 88940,
		"rarity": "Rare",
		"droprate": null,
		"type": "weapons",
		"img": "/img/osrs/ancient_staff.png",
		"game": "osrs",
		"boss": "Chaos Fanatic",
		"npc": "Chaos Fanatic",
	},
	{
		"title": "Fire rune",
		"quantity": 250,
		"price":5,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "runes",
		"img": "/img/osrs/fire_rune.png",
		"game": "osrs",
		"boss": "Chaos Fanatic",
		"npc": "Chaos Fanatic"
	},
	{
		"title": "Chaos rune",
		"quantity": 175,
		"price":101,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "runes",
		"img": "/img/osrs/chaos_rune.png",
		"game": "osrs",
		"boss": "Chaos Fanatic",
		"npc": "Chaos Fanatic"
	},
	{
		"title": "Blood rune",
		"quantity": 50,
		"price":307,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "runes",
		"img": "/img/osrs/blood_rune.png",
		"game": "osrs",
		"boss": "Chaos Fanatic",
		"npc": "Chaos Fanatic"
	},
	{
		"title": "Smoke rune",
		"quantity": 30,
		"price": 11,
		"rarity": "Common",
		"droprate": null,
		"type": "runes",
		"img": "/img/osrs/smoke_rune.png",
		"game": "osrs",
		"boss": "Chaos Fanatic",
		"npc": "Chaos Fanatic"
	},
	{
		"title": "Lantadyme",
		"quantity": 4,
		"price": 953,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "herbs",
		"img": "/img/osrs/lantadyme.png",
		"game": "osrs",
		"boss": "Chaos Fanatic",
		"npc": "Chaos Fanatic"
	},
	{
		"title": "Coins",
		"quantity": 1800,
		"price": 1,
		"rarity": "Common",
		"droprate": null,
		"type": "other",
		"img": "/img/osrs/coins.png",
		"game": "osrs",
		"boss": "Chaos Fanatic",
		"npc": "Chaos Fanatic"
	},
	{
		"title": "Uncut sapphire",
		"quantity": 4,
		"price": 585,
		"rarity": "Common",
		"droprate": null,
		"type": "other",
		"img": "/img/osrs/uncut_sapphire.png",
		"game": "osrs",
		"boss": "Chaos Fanatic",
		"npc": "Chaos Fanatic"
	},
	{
		"title": "Uncut emerald",
		"quantity": 6,
		"price": 1380,
		"rarity": "Common",
		"droprate": null,
		"type": "other",
		"img": "/img/osrs/uncut_emerald.png",
		"game": "osrs",
		"boss": "Chaos Fanatic",
		"npc": "Chaos Fanatic"
	},
	{
		"title": "Anchovy pizza",
		"quantity": 8,
		"price": 853,
		"rarity": "Common",
		"droprate": null,
		"type": "other",
		"img": "/img/osrs/anchovy_pizza.png",
		"game": "osrs",
		"boss": "Chaos Fanatic",
		"npc": "Chaos Fanatic"
	},
	{
		"title": "Monkfish",
		"quantity": 3,
		"price": 591,
		"rarity": "Common",
		"droprate": null,
		"type": "other",
		"img": "/img/osrs/monkfish.png",
		"game": "osrs",
		"boss": "Chaos Fanatic",
		"npc": "Chaos Fanatic"
	},
	{
		"title": "Shark",
		"quantity": 1,
		"price": 906,
		"rarity": "Common",
		"droprate": null,
		"type": "other",
		"img": "/img/osrs/shark.png",
		"game": "osrs",
		"boss": "Chaos Fanatic",
		"npc": "Chaos Fanatic"
	},
	{
		"title": "Chaos talisman",
		"quantity": 1,
		"price": 417,
		"rarity": "Common",
		"droprate": null,
		"type": "other",
		"img": "/img/osrs/chaos_talisman.png",
		"game": "osrs",
		"boss": "Chaos Fanatic",
		"npc": "Chaos Fanatic"
	},
	{
		"title": "Nature talisman",
		"quantity": 1,
		"price": 601,
		"rarity": "Common",
		"droprate": null,
		"type": "other",
		"img": "/img/osrs/nature_talisman.png",
		"game": "osrs",
		"boss": "Chaos Fanatic",
		"npc": "Chaos Fanatic"
	},
	{
		"title": "pure essence",
		"quantity": 250,
		"price": 11,
		"rarity": "Common",
		"droprate": null,
		"type": "other",
		"img": "/img/osrs/pure_essence.png",
		"game": "osrs",
		"boss": "Chaos Fanatic",
		"npc": "Chaos Fanatic"
	},
	{
		"title": "Prayer potion (4)",
		"quantity": 1,
		"price": 7666,
		"rarity": "Common",
		"droprate": null,
		"type": "other",
		"img": "/img/osrs/prayer_potion_4.png",
		"game": "osrs",
		"boss": "Chaos Fanatic",
		"npc": "Chaos Fanatic"
	},
	{
		"title": "Wine of zamorak",
		"quantity": 10,
		"price": 1231,
		"rarity": "Common",
		"droprate": null,
		"type": "other",
		"img": "/img/osrs/wine_of_zamorak.png",
		"game": "osrs",
		"boss": "Chaos Fanatic",
		"npc": "Chaos Fanatic"
	},
	{
		"title": "Sinister key",
		"quantity": 1,
		"price": 26119,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "other",
		"img": "/img/osrs/sinister_key.png",
		"game": "osrs",
		"boss": "Chaos Fanatic",
		"npc": "Chaos Fanatic"
	},
	{
		"title": "Mysterious emblem",
		"quantity": 1,
		"price": null,
		"rarity": "Uncommon",
		"droprate": 50,
		"type": "other",
		"img": "/img/osrs/mysterious_emblem.png",
		"game": "osrs",
		"boss": "Chaos Fanatic",
		"npc": "Chaos Fanatic"
	},
	{
		"title": "Odium shard 1",
		"quantity": 1,
		"price": 471459,
		"rarity": "Rare",
		"droprate": 128,
		"type": "other",
		"img": "/img/osrs/odium_shard_1.png",
		"game": "osrs",
		"boss": "Chaos Fanatic",
		"npc": "Chaos Fanatic"
	},
	{
		"title": "Malediction shard 1",
		"quantity": 1,
		"price": 289976,
		"rarity": "Rare",
		"droprate": 128,
		"type": "other",
		"img": "/img/osrs/malediction_shard_1.png",
		"game": "osrs",
		"boss": "Chaos Fanatic",
		"npc": "Chaos Fanatic"
	},
	{
		"title": "Clue scroll (hard)",
		"quantity": 1,
		"price": null,
		"rarity": "Rare",
		"droprate": null,
		"type": "other",
		"img": "/img/osrs/clue_scroll_hard.png",
		"game": "osrs",
		"boss": "Chaos Fanatic",
		"npc": "Chaos Fanatic"
	},
	{
		"title": "Pet chaos elemental",
		"quantity": 1,
		"price": null,
		"rarity": "Very rare",
		"droprate": 1000,
		"type": "other",
		"img": "/img/osrs/pet_chaos_elemental.png",
		"game": "osrs",
		"boss": "Chaos Fanatic",
		"npc": "Chaos Fanatic"
	}
];

