/*
* RS3 Chaos Elemental drops list made by Richard (Hellworms).
*/

ChaosElementalDropsRs3 = [
	{
		"title": "Rune sword",
		"quantity": 1,
		"price": 12068,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "weapons",
		"img": "/img/rs3/rune_sword.png",
		"game": "rs3",
		"boss": "Chaos elemental",
		"npc": "Chaos elemental"
	},
	{
		"title": "Dragon 2h sword",
		"quantity": 1,
		"price": 134044,
		"rarity": "Rare",
		"droprate": null,
		"type": "weapons",
		"img": "/img/rs3/dragon_2h_sword.png",
		"game": "rs3",
		"boss": "Chaos elemental",
		"npc": "Chaos elemental"
	},
	{
		"title": "Corrupt dragon battleaxe",
		"quantity": 1,
		"price": 279329,
		"rarity": "Very rare",
		"droprate": null,
		"type": "weapons",
		"img": "/img/rs3/corrupt_dragon_battleaxe.png",
		"game": "rs3",
		"boss": "Chaos elemental",
		"npc": "Chaos elemental"
	},
	{
		"title": "Corrupt dragon dagger",
		"quantity": 1,
		"price": 54811,
		"rarity": "Very rare",
		"droprate": null,
		"type": "weapons",
		"img": "/img/rs3/corrupt_dragon_dagger.png",
		"game": "rs3",
		"boss": "Chaos elemental",
		"npc": "Chaos elemental"
	},
	{
		"title": "Corrupt dragon longsword",
		"quantity": 1,
		"price": 197770,
		"rarity": "Very rare",
		"droprate": null,
		"type": "weapons",
		"img": "/img/rs3/corrupt_dragon_longsword.png",
		"game": "rs3",
		"boss": "Chaos elemental",
		"npc": "Chaos elemental"
	},
	{
		"title": "Corrupt dragon mace",
		"quantity": 1,
		"price": 60956,
		"rarity": "Very rare",
		"droprate": null,
		"type": "weapons",
		"img": "/img/rs3/corrupt_dragon_mace.png",
		"game": "rs3",
		"boss": "Chaos elemental",
		"npc": "Chaos elemental"
	},
	{
		"title": "Corrupt dragon scimitar",
		"quantity": 1,
		"price": 255173,
		"rarity": "Very rare",
		"droprate": null,
		"type": "weapons",
		"img": "/img/rs3/corrupt_dragon_scimitar.png",
		"game": "rs3",
		"boss": "Chaos elemental",
		"npc": "Chaos elemental"
	},
	{
		"title": "Corrut dragon spear",
		"quantity": 1,
		"price": 4399782,
		"rarity": "Very rare",
		"droprate": null,
		"type": "weapons",
		"img": "/img/rs3/corrupt_dragon_spear.png",
		"game": "rs3",
		"boss": "Chaos elemental",
		"npc": "Chaos elemental"
	},
	{
		"title": "Statius's warhammer",
		"quantity": 1,
		"price": 2710899,
		"rarity": "Rare",
		"droprate": null,
		"type": "weapons",
		"img": "/img/rs3/statius's_warhammer.png",
		"game": "rs3",
		"boss": "Chaos elemental",
		"npc": "Chaos elemental"
	},
	{
		"title": "Vesta's longsword",
		"quantity": 1,
		"price": 8604357,
		"rarity": "Very rare",
		"droprate": null,
		"type": "weapons",
		"img": "/img/rs3/vesta's_longsword.png",
		"game": "rs3",
		"boss": "Chaos elemental",
		"npc": "Chaos elemental"
	},
	{
		"title": "Vesta's spear",
		"quantity": 1,
		"price": 5241918,
		"rarity": "Very rare",
		"droprate": null,
		"type": "weapons",
		"img": "/img/rs3/vesta's_spear.png",
		"game": "rs3",
		"boss": "Chaos elemental",
		"npc": "Chaos elemental"
	},
	{
		"title": "Zuriel's staff",
		"quantity": 1,
		"price": 3876658,
		"rarity": "Very rare",
		"droprate": null,
		"type": "weapons",
		"img": "/img/rs3/zuriel's_staff.png",
		"game": "rs3",
		"boss": "Chaos elemental",
		"npc": "Chaos elemental"
	},
	{
		"title": "Corrupt statius's warhammer",
		"quantity": 1,
		"price": 1252000,
		"rarity": "Very rare",
		"droprate": null,
		"type": "weapons",
		"img": "/img/rs3/corrupt_statius's_warhammer.png",
		"game": "rs3",
		"boss": "Chaos elemental",
		"npc": "Chaos elemental"
	},
	{
		"title": "Corrupt vesta's longsword",
		"quantity": 1,
		"price": 2468316,
		"rarity": "Very rare",
		"droprate": null,
		"type": "weapons",
		"img": "/img/rs3/corrupt_vesta's_ longsword.png",
		"game": "rs3",
		"boss": "Chaos elemental",
		"npc": "Chaos elemental"
	},
	{
		"title": "Corrupt vesta's spear",
		"quantity": 1,
		"price": 113281,
		"rarity": "Very rare",
		"droprate": null,
		"type": "weapons",
		"img": "/img/rs3/corrupt_vesta's_spear.png",
		"game": "rs3",
		"boss": "Chaos elemental",
		"npc": "Chaos elemental"
	},
	{
		"title": "Corrupt zuriel's staff",
		"quantity": 1,
		"price": null,
		"rarity": "Very rare",
		"droprate": null,
		"type": "weapons",
		"img": "/img/rs3/corrupt_zuriel's_staff.png",
		"game": "rs3",
		"boss": "Chaos elemental",
		"npc": "Chaos elemental"
	},
	{
		"title": "Corrupt dragon chainbody",
		"quantity": 1,
		"price": 223176,
		"rarity": "Very rare",
		"droprate": null,
		"type": "Armour",
		"img": "/img/rs3/corrupt_dragon_chainbody.png",
		"game": "rs3",
		"boss": "Chaos elemental",
		"npc": "Chaos elemental"
	},
	{
		"title": "Corrupt dragon helm",
		"quantity": 1,
		"price": 152373,
		"rarity": "Very rare",
		"droprate": null,
		"type": "Armour",
		"img": "/img/rs3/corrupt_dragon_helm.png",
		"game": "rs3",
		"boss": "Chaos elemental",
		"npc": "Chaos elemental"
	},
	{
		"title": "Corrupt dragon platelegs",
		"quantity": 1,
		"price": 85067,
		"rarity": "Very rare",
		"droprate": null,
		"type": "Armour",
		"img": "/img/rs3/corrupt_dragon_platelegs.png",
		"game": "rs3",
		"boss": "Chaos elemental",
		"npc": "Chaos elemental"
	},
	{
		"title": "Corrupt dragon plateskirt",
		"quantity": 1,
		"price": 71739,
		"rarity": "Very rare",
		"droprate": null,
		"type": "Armour",
		"img": "/img/rs3/corrupt_dragon_plateskirt.png",
		"game": "rs3",
		"boss": "Chaos elemental",
		"npc": "Chaos elemental"
	},
	{
		"title": "Corrupt dragon sq shield",
		"quantity": 1,
		"price": 75611,
		"rarity": "Very rare",
		"droprate": null,
		"type": "Armour",
		"img": "/img/rs3/corrupt_dragon_sq_shield.png",
		"game": "rs3",
		"boss": "Chaos elemental",
		"npc": "Chaos elemental"
	},
	{
		"title": "Statius's full helm",
		"quantity": 1,
		"price": 1726979,
		"rarity": "Very rare",
		"droprate": null,
		"type": "Armour",
		"img": "/img/rs3/statius's_full_helm.png",
		"game": "rs3",
		"boss": "Chaos elemental",
		"npc": "Chaos elemental"
	},
	{
		"title": "Statius's platebody",
		"quantity": 1,
		"price": 1757576,
		"rarity": "Very rare",
		"droprate": null,
		"type": "Armour",
		"img": "/img/rs3/statius's_platebody.png",
		"game": "rs3",
		"boss": "Chaos elemental",
		"npc": "Chaos elemental"
	},
	{
		"title": "Statius's platelegs",
		"quantity": 1,
		"price": 1732520,
		"rarity": "Very rare",
		"droprate": null,
		"type": "Armour",
		"img": "/img/rs3/statius's_platelegs.png",
		"game": "rs3",
		"boss": "Chaos elemental",
		"npc": "Chaos elemental"
	},
	{
		"title": "Vesta's chainbody",
		"quantity": 1,
		"price": 2386540,
		"rarity": "Very rare",
		"droprate": null,
		"type": "Armour",
		"img": "/img/rs3/vesta's_chainbody.png",
		"game": "rs3",
		"boss": "Chaos elemental",
		"npc": "Chaos elemental"
	},
	{
		"title": "Vesta's plateskirt",
		"quantity": 1,
		"price": 2105308,
		"rarity": "Very rare",
		"droprate": null,
		"type": "armour",
		"img": "/img/rs3/vesta's_plateskirt.png",
		"game": "rs3",
		"boss": "Chaos elemental",
		"npc": "Chaos elemental"
	},
	{
		"title": "Zuriel's hood",
		"quantity": 1,
		"price": 442061,
		"rarity": "Very rare",
		"droprate": null,
		"type": "armour",
		"img": "/img/rs3/zuriel's_hood.png",
		"game": "rs3",
		"boss": "Chaos elemental",
		"npc": "Chaos elemental"
	},
	{
		"title": "Zuriel's robe top",
		"quantity": 1,
		"price": 1194634,
		"rarity": "Very rare",
		"droprate": null,
		"type": "armour",
		"img": "/img/rs3/zuriel's_robe_top.png",
		"game": "rs3",
		"boss": "Chaos elemental",
		"npc": "Chaos elemental"
	},
	{
		"title": "Zuriel's robe bottom",
		"quantity": 1,
		"price": 1041604,
		"rarity": "Very rare",
		"droprate": null,
		"type": "armour",
		"img": "/img/rs3/zuriel's_robe_bottom.png",
		"game": "rs3",
		"boss": "Chaos elemental",
		"npc": "Chaos elemental"
	},
	{
		"title": "Morrigan's coif",
		"quantity": 1,
		"price": 291630,
		"rarity": "Very rare",
		"droprate": null,
		"type": "armour",
		"img": "/img/rs3/morrigan's_coif.png",
		"game": "rs3",
		"boss": "Chaos elemental",
		"npc": "Chaos elemental"
	},
	{
		"title": "Morrigan's leather body",
		"quantity": 1,
		"price": 1014791,
		"rarity": "Very rare",
		"droprate": null,
		"type": "armour",
		"img": "/img/rs3/morrigan's_leather_body.png",
		"game": "rs3",
		"boss": "Chaos elemental",
		"npc": "Chaos elemental"
	},
	{
		"title": "Morrigan's leather chaps",
		"quantity": 1,
		"price": 612620,
		"rarity": "Very rare",
		"droprate": null,
		"type": "armour",
		"img": "/img/rs3/morrigan's_leather_chaps.png",
		"game": "rs3",
		"boss": "Chaos elemental",
		"npc": "Chaos elemental"
	},
	{
		"title": "Corrupt statius's full helm",
		"quantity": 1,
		"price": 844133,
		"rarity": "Very rare",
		"droprate": null,
		"type": "armour",
		"img": "/img/rs3/corrupt_statius's_full_helm.png",
		"game": "rs3",
		"boss": "Chaos elemental",
		"npc": "Chaos elemental"
	},
	{
		"title": "Corrupt statius's platebody",
		"quantity": 1,
		"price": 914011,
		"rarity": "Very rare",
		"droprate": null,
		"type": "armour",
		"img": "/img/rs3/corrupt_statius's_platebody.png",
		"game": "rs3",
		"boss": "Chaos elemental",
		"npc": "Chaos elemental"
	},
	{
		"title": "Corrupt statius's platelegs",
		"quantity": 1,
		"price": 1277646,
		"rarity": "Very rare",
		"droprate": null,
		"type": "armour",
		"img": "/img/rs3/corrupt_statius's_platelegs.png",
		"game": "rs3",
		"boss": "Chaos elemental",
		"npc": "Chaos elemental"
	},
	{
		"title": "Corrupt vesta's chainbody",
		"quantity": 1,
		"price": 1233550,
		"rarity": "Very rare",
		"droprate": null,
		"type": "armour",
		"img": "/img/rs3/corrupt_vesta's_chainbody.png",
		"game": "rs3",
		"boss": "Chaos elemental",
		"npc": "Chaos elemental"
	},
	{
		"title": "Corrupt vesta's plateskirt",
		"quantity": 1,
		"price": 1409455,
		"rarity": "Very rare",
		"droprate": null,
		"type": "armour",
		"img": "/img/rs3/corrupt_vesta's_plateskirt.png",
		"game": "rs3",
		"boss": "Chaos elemental",
		"npc": "Chaos elemental"
	},
	{
		"title": "Corrupt zuriel's hood",
		"quantity": 1,
		"price": 43474,
		"rarity": "Very rare",
		"droprate": null,
		"type": "armour",
		"img": "/img/rs3/corrupt_zuriel's_hood.png",
		"game": "rs3",
		"boss": "Chaos elemental",
		"npc": "Chaos elemental"
	},
	{
		"title": "Corrupt zuriel's robe top",
		"quantity": 1,
		"price": 211778,
		"rarity": "Very rare",
		"droprate": null,
		"type": "armour",
		"img": "/img/rs3/corrupt_zuriel's_robe_top.png",
		"game": "rs3",
		"boss": "Chaos elemental",
		"npc": "Chaos elemental"
	},
	{
		"title": "Corrupt zuriel's robe bottom",
		"quantity": 1,
		"price": 112222,
		"rarity": "Very rare",
		"droprate": null,
		"type": "armour",
		"img": "/img/rs3/corrupt_zuriel's_robe_bottom.png",
		"game": "rs3",
		"boss": "Chaos elemental",
		"npc": "Chaos elemental"
	},
	{
		"title": "Corrupt morrigan's coif",
		"quantity": 1,
		"price": 58568,
		"rarity": "Very rare",
		"droprate": null,
		"type": "armour",
		"img": "/img/rs3/corrupt_morrigan's_coif.png",
		"game": "rs3",
		"boss": "Chaos elemental",
		"npc": "Chaos elemental"
	},
	{
		"title": "Corrupt morrigan's leather body",
		"quantity": 1,
		"price": 303719,
		"rarity": "Very rare",
		"droprate": null,
		"type": "armour",
		"img": "/img/rs3/corrupt_morrigan's_leather_body.png",
		"game": "rs3",
		"boss": "Chaos elemental",
		"npc": "Chaos elemental"
	},
	{
		"title": "Corrupt morrigan's leather chaps",
		"quantity": 1,
		"price": 77748,
		"rarity": "Very rare",
		"droprate": null,
		"type": "armour",
		"img": "/img/rs3/corrupt_morrigan's_leather_chaps.png",
		"game": "rs3",
		"boss": "Chaos elemental",
		"npc": "Chaos elemental"
	},
	{
		"title": "Mithril dart",
		"quantity": 400,
		"price": 4,
		"rarity": "Common",
		"droprate": null,
		"type": "Ranged weaponry",
		"img": "/img/rs3/mithril_dart.png",
		"game": "rs3",
		"boss": "Chaos elemental",
		"npc": "Chaos elemental"
	},
	{
		"title": "Morrigan's javelin",
		"quantity": 35,
		"price": 12514,
		"rarity": "Very rare",
		"droprate": null,
		"type": "Ranged weaponry",
		"img": "/img/rs3/morrigan's_javelin.png",
		"game": "rs3",
		"boss": "Chaos elemental",
		"npc": "Chaos elemental"
	},
	{
		"title": "Morrigan's throwing axe",
		"quantity": 25,
		"price": 6193,
		"rarity": "Very rare",
		"droprate": null,
		"type": "Ranged weaponry",
		"img": "/img/rs3/morrigan's_throwing_axe.png",
		"game": "rs3",
		"boss": "Chaos elemental",
		"npc": "Chaos elemental"
	},
	{
		"title": "Corrupt morrigan's javelin",
		"quantity": 25,
		"price": 4606,
		"rarity": "Very rare",
		"droprate": null,
		"type": "Ranged weaponry",
		"img": "/img/rs3/corrupt_morrigan's_javelin.png",
		"game": "rs3",
		"boss": "Chaos elemental",
		"npc": "Chaos elemental"
	},
	{
		"title": "Corrupt morrigan's throwing axe",
		"quantity": 25,
		"price": 3479,
		"rarity": "Very rare",
		"droprate": null,
		"type": "Ranged weaponry",
		"img": "/img/rs3/corrupt_morrigan's_throwing_axe.png",
		"game": "rs3",
		"boss": "Chaos elemental",
		"npc": "Chaos elemental"
	},
	{
		"title": "Ancient psaltery bridge",
		"quantity": 1,
		"price": 5000,
		"rarity": "Very rare",
		"droprate": null,
		"type": "Ancient artefacts",
		"img": "/img/rs3/ancient_psaltery_bridge.png",
		"game": "rs3",
		"boss": "Chaos elemental",
		"npc": "Chaos elemental"
	},
	{
		"title": "Ancient statuette",
		"quantity": 1,
		"price": 5000000,
		"rarity": "Very rare",
		"droprate": null,
		"type": "Ancient artefacts",
		"img": "/img/rs3/ancient_statuette.png",
		"game": "rs3",
		"boss": "Chaos elemental",
		"npc": "Chaos elemental"
	},
	{
		"title": "Armadyl statuette",
		"quantity": 1,
		"price": 750000,
		"rarity": "Very rare",
		"droprate": null,
		"type": "Ancient artefacts",
		"img": "/img/rs3/armadyl_statuette.png",
		"game": "rs3",
		"boss": "Chaos elemental",
		"npc": "Chaos elemental"
	},
	{
		"title": "Armadyl totem",
		"quantity": 1,
		"price": 150000,
		"rarity": "Very rare",
		"droprate": null,
		"type": "Ancient artefacts",
		"img": "/img/rs3/armadyl_totem.png",
		"game": "rs3",
		"boss": "Chaos elemental",
		"npc": "Chaos elemental"
	},
	{
		"title": "Bandos scrimshaw",
		"quantity": 1,
		"price": 50000,
		"rarity": "Very rare",
		"droprate": null,
		"type": "Ancient artefacts",
		"img": "/img/rs3/bandos_scrimshaw.png",
		"game": "rs3",
		"boss": "Chaos elemental",
		"npc": "Chaos elemental"
	},
	{
		"title": "Bandos statuette",
		"quantity": 1,
		"price": 300000,
		"rarity": "Very rare",
		"droprate": null,
		"type": "Ancient artefacts",
		"img": "/img/rs3/bandos_statuette.png",
		"game": "rs3",
		"boss": "Chaos elemental",
		"npc": "Chaos elemental"
	},
	{
		"title": "Broken statue headdress",
		"quantity": 1,
		"price": 5000,
		"rarity": "Very rare",
		"droprate": null,
		"type": "Ancient artefacts",
		"img": "/img/rs3/broken_statue_headdress.png",
		"game": "rs3",
		"boss": "Chaos elemental",
		"npc": "Chaos elemental"
	},
	{
		"title": "Bronzed dragon claw",
		"quantity": 1,
		"price": 20000,
		"rarity": "Very rare",
		"droprate": null,
		"type": "Ancient artefacts",
		"img": "/img/rs3/bronzed_dragon_claw.png",
		"game": "rs3",
		"boss": "Chaos elemental",
		"npc": "Chaos elemental"
	},
	{
		"title": "Guthixian brazier",
		"quantity": 1,
		"price": 200000,
		"rarity": "Very rare",
		"droprate": null,
		"type": "Ancient artefacts",
		"img": "/img/rs3/Guthixian_brazier.png",
		"game": "rs3",
		"boss": "Chaos elemental",
		"npc": "Chaos elemental"
	},
	{
		"title": "Ruby chalice",
		"quantity": 1,
		"price": 250000,
		"rarity": "Very rare",
		"droprate": null,
		"type": "Ancient artefacts",
		"img": "/img/rs3/ruby_chalice.png",
		"game": "rs3",
		"boss": "Chaos elemental",
		"npc": "Chaos elemental"
	},
	{
		"title": "Saradomin amphora",
		"quantity": 1,
		"price": 40000,
		"rarity": "Very rare",
		"droprate": null,
		"type": "Ancient artefacts",
		"img": "/img/rs3/saradomin_amphora.png",
		"game": "rs3",
		"boss": "Chaos elemental",
		"npc": "Chaos elemental"
	},
	{
		"title": "Saradomin carving",
		"quantity": 1,
		"price": 75000,
		"rarity": "Very rare",
		"droprate": null,
		"type": "Ancient artefacts",
		"img": "/img/rs3/saradomin_carving.png",
		"game": "rs3",
		"boss": "Chaos elemental",
		"npc": "Chaos elemental"
	},
	{
		"title": "Saradomin statuette",
		"quantity": 1,
		"price": 400000,
		"rarity": "Very rare",
		"droprate": null,
		"type": "Ancient artefacts",
		"img": "/img/rs3/saradomin_statuette.png",
		"game": "rs3",
		"boss": "Chaos elemental",
		"npc": "Chaos elemental"
	},
	{
		"title": "Seren statuette",
		"quantity": 1,
		"price": 1000000,
		"rarity": "Very rare",
		"droprate": null,
		"type": "Ancient artefacts",
		"img": "/img/rs3/seren_statuette.png",
		"game": "rs3",
		"boss": "Chaos elemental",
		"npc": "Chaos elemental"
	},
	{
		"title": "Third age carafe",
		"quantity": 1,
		"price": 10000,
		"rarity": "Very rare",
		"droprate": null,
		"type": "Ancient artefacts",
		"img": "/img/rs3/third_age_carafe.png",
		"game": "rs3",
		"boss": "Chaos elemental",
		"npc": "Chaos elemental"
	},
	{
		"title": "Zamorak medallion",
		"quantity": 1,
		"price": 100000,
		"rarity": "Very rare",
		"droprate": null,
		"type": "Ancient artefacts",
		"img": "/img/rs3/zamorak_medallion.png",
		"game": "rs3",
		"boss": "Chaos elemental",
		"npc": "Chaos elemental"
	},
	{
		"title": "Brawling gloves (Melee)",
		"quantity": 1,
		"price": null,
		"rarity": "Very rare",
		"droprate": null,
		"type": "Brawling Gloves",
		"img": "/img/rs3/brawling_gloves_melee.png",
		"game": "rs3",
		"boss": "Chaos elemental",
		"npc": "Chaos elemental"
	},
	{
		"title": "Brawling gloves (Magic)",
		"quantity": 1,
		"price": null,
		"rarity": "Very rare",
		"droprate": null,
		"type": "Brawling Gloves",
		"img": "/img/rs3/brawling_gloves_magic.png",
		"game": "rs3",
		"boss": "Chaos elemental",
		"npc": "Chaos elemental"
	},
	{
		"title": "Brawling gloves (Ranged)",
		"quantity": 1,
		"price": null,
		"rarity": "Very rare",
		"droprate": null,
		"type": "Brawling Gloves",
		"img": "/img/rs3/brawling_gloves_ranged.png",
		"game": "rs3",
		"boss": "Chaos elemental",
		"npc": "Chaos elemental"
	},
	{
		"title": "Brawling gloves (Agility)",
		"quantity": 1,
		"price": null,
		"rarity": "Very rare",
		"droprate": null,
		"type": "Brawling Gloves",
		"img": "/img/rs3/brawling_gloves_agility.png",
		"game": "rs3",
		"boss": "Chaos elemental",
		"npc": "Chaos elemental"
	},
	{
		"title": "Brawling gloves (Cooking)",
		"quantity": 1,
		"price": null,
		"rarity": "Very rare",
		"droprate": null,
		"type": "Brawling Gloves",
		"img": "/img/rs3/brawling_gloves_cooking.png",
		"game": "rs3",
		"boss": "Chaos elemental",
		"npc": "Chaos elemental"
	},
	{
		"title": "Brawling gloves (FM)",
		"quantity": 1,
		"price": null,
		"rarity": "Very rare",
		"droprate": null,
		"type": "Brawling Gloves",
		"img": "/img/rs3/brawling_gloves_fm.png",
		"game": "rs3",
		"boss": "Chaos elemental",
		"npc": "Chaos elemental"
	},
	{
		"title": "Brawling gloves (Fishing)",
		"quantity": 1,
		"price": null,
		"rarity": "Very rare",
		"droprate": null,
		"type": "Brawling Gloves",
		"img": "/img/rs3/brawling_gloves_fishing.png",
		"game": "rs3",
		"boss": "Chaos elemental",
		"npc": "Chaos elemental"
	},
	{
		"title": "Brawling gloves (Hunter)",
		"quantity": 1,
		"price": null,
		"rarity": "Very rare",
		"droprate": null,
		"type": "Brawling Gloves",
		"img": "/img/rs3/brawling_gloves_hunter.png",
		"game": "rs3",
		"boss": "Chaos elemental",
		"npc": "Chaos elemental"
	},
	{
		"title": "Brawling gloves (Mining)",
		"quantity": 1,
		"price": null,
		"rarity": "Very rare",
		"droprate": null,
		"type": "Brawling Gloves",
		"img": "/img/rs3/brawling_gloves_mining.png",
		"game": "rs3",
		"boss": "Chaos elemental",
		"npc": "Chaos elemental"
	},
	{
		"title": "Brawling gloves (Prayer)",
		"quantity": 1,
		"price": null,
		"rarity": "Very rare",
		"droprate": null,
		"type": "Brawling Gloves",
		"img": "/img/rs3/brawling_gloves_prayer.png",
		"game": "rs3",
		"boss": "Chaos elemental",
		"npc": "Chaos elemental"
	},
	{
		"title": "Brawling gloves (Smithing)",
		"quantity": 1,
		"price": null,
		"rarity": "Very rare",
		"droprate": null,
		"type": "Brawling Gloves",
		"img": "/img/rs3/brawling_gloves_smithing.png",
		"game": "rs3",
		"boss": "Chaos elemental",
		"npc": "Chaos elemental"
	},
	{
		"title": "Brawling gloves (Thieving)",
		"quantity": 1,
		"price": null,
		"rarity": "Very rare",
		"droprate": null,
		"type": "Brawling Gloves",
		"img": "/img/rs3/brawling_gloves_thieving.png",
		"game": "rs3",
		"boss": "Chaos elemental",
		"npc": "Chaos elemental"
	},
	{
		"title": "Brawling gloves (WC)",
		"quantity": 1,
		"price": null,
		"rarity": "Very rare",
		"droprate": null,
		"type": "Brawling Gloves",
		"img": "/img/rs3/brawling_gloves_wc.png",
		"game": "rs3",
		"boss": "Chaos elemental",
		"npc": "Chaos elemental"
	},
	{
		"title": "Grimy guam",
		"quantity": 2,
		"price": 340,
		"rarity": "Common",
		"droprate": null,
		"type": "Herbs",
		"img": "/img/rs3/grimy_guam.png",
		"game": "rs3",
		"boss": "Chaos elemental",
		"npc": "Chaos elemental"
	},
	{
		"title": "Grimy marrentill",
		"quantity": 1,
		"price": 180,
		"rarity": "common",
		"droprate": null,
		"type": "Herbs",
		"img": "/img/rs3/grimy_marrentill.png",
		"game": "rs3",
		"boss": "Chaos elemental",
		"npc": "Chaos elemental"
	},
	{
		"title": "Chaos rune",
		"quantity": 247,
		"price": 44,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "Runes",
		"img": "/img/rs3/chaos_rune.png",
		"game": "rs3",
		"boss": "Chaos elemental",
		"npc": "Chaos elemental"
	},
	{
		"title": "Blood rune",
		"quantity": 150,
		"price": 448,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "Runes",
		"img": "/img/rs3/blood_rune.png",
		"game": "rs3",
		"boss": "Chaos elemental",
		"npc": "Chaos elemental"
	},
	{
		"title": "Death rune",
		"quantity": 163,
		"price": 348,
		"rarity": "Rare",
		"droprate": null,
		"type": "Runes",
		"img": "/img/rs3/death_rune.png",
		"game": "rs3",
		"boss": "Chaos elemental",
		"npc": "Chaos elemental"
	},
	{
		"title": "Grimy tarromin",
		"quantity": 1,
		"price": 32,
		"rarity": "common",
		"droprate": null,
		"type": "Herbs",
		"img": "/img/rs3/grimy_tarromin.png",
		"game": "rs3",
		"boss": "Chaos elemental",
		"npc": "Chaos elemental"
	},
	{
		"title": "Grimy ranarr",
		"quantity": 1,
		"price": 2270,
		"rarity": "uncommon",
		"droprate": null,
		"type": "Herbs",
		"img": "/img/rs3/grimy_ranarr.png",
		"game": "rs3",
		"boss": "Chaos elemental",
		"npc": "Chaos elemental"
	},
	{
		"title": "Grimy avantoe",
		"quantity": 1,
		"price": 3984,
		"rarity": "uncommon",
		"droprate": null,
		"type": "Herbs",
		"img": "/img/rs3/grimy_avantoe.png",
		"game": "rs3",
		"boss": "Chaos elemental",
		"npc": "Chaos elemental"
	},
	{
		"title": "Strength potion (1)",
		"quantity": 1,
		"price": 195,
		"rarity": "Common",
		"droprate": null,
		"type": "Potions/Food",
		"img": "/img/rs3/strength_potion_1.png",
		"game": "rs3",
		"boss": "Chaos elemental",
		"npc": "Chaos elemental"
	},
	{
		"title": "Attack potion (1)",
		"quantity": 1,
		"price": 106,
		"rarity": "Common",
		"droprate": null,
		"type": "Potions/Food",
		"img": "/img/rs3/attack_potion_1.png",
		"game": "rs3",
		"boss": "Chaos elemental",
		"npc": "Chaos elemental"
	},
	{
		"title": "Defence potion (1)",
		"quantity": 1,
		"price": 141,
		"rarity": "Common",
		"droprate": null,
		"type": "Potions/Food",
		"img": "/img/rs3/defence_potion_1.png",
		"game": "rs3",
		"boss": "Chaos elemental",
		"npc": "Chaos elemental"
	},
	{
		"title": "Plain pizza",
		"quantity": 3,
		"price": 412,
		"rarity": "Common",
		"droprate": null,
		"type": "Potions/Food",
		"img": "/img/rs3/plain_pizza.png",
		"game": "rs3",
		"boss": "Chaos elemental",
		"npc": "Chaos elemental"
	},
	{
		"title": "Tuna",
		"quantity": 5,
		"price": 199,
		"rarity": "Common",
		"droprate": null,
		"type": "Potions/Food",
		"img": "/img/rs3/tuna.png",
		"game": "rs3",
		"boss": "Chaos elemental",
		"npc": "Chaos elemental"
	},
	{
		"title": "Strange fruit",
		"quantity": 3,
		"price": 369,
		"rarity": "Common",
		"droprate": null,
		"type": "Potions/Food",
		"img": "/img/rs3/strange_fruit.png",
		"game": "rs3",
		"boss": "Chaos elemental",
		"npc": "Chaos elemental"
	},
	{
		"title": "Shark",
		"quantity": 10,
		"price": 705,
		"rarity": "Common",
		"droprate": null,
		"type": "Potions/Food",
		"img": "/img/rs3/shark.png",
		"game": "rs3",
		"boss": "Chaos elemental",
		"npc": "Chaos elemental"
	},
	{
		"title": "Stew",
		"quantity": 10,
		"price": 1117,
		"rarity": "uncommon",
		"droprate": null,
		"type": "Potions/Food",
		"img": "/img/rs3/stew.png",
		"game": "rs3",
		"boss": "Chaos elemental",
		"npc": "Chaos elemental"
	},
	{
		"title": "Saradomin brew (2)",
		"quantity": 5,
		"price": 4353,
		"rarity": "Very rare",
		"droprate": null,
		"type": "Potions/Food",
		"img": "/img/rs3/saradomin_brew_2.png",
		"game": "rs3",
		"boss": "Chaos elemental",
		"npc": "Chaos elemental"
	},
	{
		"title": "Strawberry seed",
		"quantity": 2,
		"price": 344,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "Seeds",
		"img": "/img/rs3/strawberry_seed.png",
		"game": "rs3",
		"boss": "Chaos elemental",
		"npc": "Chaos elemental"
	},
	{
		"title": "Watermelon seed",
		"quantity": 2,
		"price": 1922,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "Seeds",
		"img": "/img/rs3/watermelon_seed.png",
		"game": "rs3",
		"boss": "Chaos elemental",
		"npc": "Chaos elemental"
	},
	{
		"title": "Limpwurt seed",
		"quantity": 2,
		"price": 400000,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "Seeds",
		"img": "/img/rs3/limpwurt_seed.png",
		"game": "rs3",
		"boss": "Chaos elemental",
		"npc": "Chaos elemental"
	},
	{
		"title": "Spirit weed seed",
		"quantity": 2,
		"price": 532,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "Seeds",
		"img": "/img/rs3/spirit_weed_seed.png",
		"game": "rs3",
		"boss": "Chaos elemental",
		"npc": "Chaos elemental"
	},
	{
		"title": "Marrentill seed",
		"quantity": 2,
		"price": 10,
		"rarity": "common",
		"droprate": null,
		"type": "Seeds",
		"img": "/img/rs3/herb_seed.png",
		"game": "rs3",
		"boss": "Chaos elemental",
		"npc": "Chaos elemental"
	},
	{
		"title": "Tarromin seed",
		"quantity": 2,
		"price": 12,
		"rarity": "common",
		"droprate": null,
		"type": "Seeds",
		"img": "/img/rs3/herb_seed.png",
		"game": "rs3",
		"boss": "Chaos elemental",
		"npc": "Chaos elemental"
	},
	{
		"title": "Harralander seed",
		"quantity": 2,
		"price": 9,
		"rarity": "common",
		"droprate": null,
		"type": "Seeds",
		"img": "/img/rs3/herb_seed.png",
		"game": "rs3",
		"boss": "Chaos elemental",
		"npc": "Chaos elemental"
	},
	{
		"title": "Ranarr seed",
		"quantity": 2,
		"price": 796,
		"rarity": "rare",
		"droprate": null,
		"type": "Seeds",
		"img": "/img/rs3/herb_seed.png",
		"game": "rs3",
		"boss": "Chaos elemental",
		"npc": "Chaos elemental"
	},
	{
		"title": "Toadflax seed",
		"quantity": 2,
		"price": 1025,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "Seeds",
		"img": "/img/rs3/herb_seed.png",
		"game": "rs3",
		"boss": "Chaos elemental",
		"npc": "Chaos elemental"
	},
	{
		"title": "Irit seed",
		"quantity": 2,
		"price": 107,
		"rarity": "uncommon",
		"droprate": null,
		"type": "Seeds",
		"img": "/img/rs3/herb_seed.png",
		"game": "rs3",
		"boss": "Chaos elemental",
		"npc": "Chaos elemental"
	},
	{
		"title": "Avantoe seed",
		"quantity": 2,
		"price": 434,
		"rarity": "rare",
		"droprate": null,
		"type": "Seeds",
		"img": "/img/rs3/herb_seed.png",
		"game": "rs3",
		"boss": "Chaos elemental",
		"npc": "Chaos elemental"
	},
	{
		"title": "Kwuarm seed",
		"quantity": 2,
		"price": 767,
		"rarity": "rare",
		"droprate": null,
		"type": "Seeds",
		"img": "/img/rs3/herb_seed.png",
		"game": "rs3",
		"boss": "Chaos elemental",
		"npc": "Chaos elemental"
	},
	{
		"title": "Snapdragon seed",
		"quantity": 1,
		"price": 514,
		"rarity": "rare",
		"droprate": null,
		"type": "Seeds",
		"img": "/img/rs3/herb_seed.png",
		"game": "rs3",
		"boss": "Chaos elemental",
		"npc": "Chaos elemental"
	},
	{
		"title": "Cadantine seed",
		"quantity": 2,
		"price": 472,
		"rarity": "rare",
		"droprate": null,
		"type": "Seeds",
		"img": "/img/rs3/herb_seed.png",
		"game": "rs3",
		"boss": "Chaos elemental",
		"npc": "Chaos elemental"
	},
	{
		"title": "Lantadyme seed",
		"quantity": 1,
		"price": 9431,
		"rarity": "rare",
		"droprate": null,
		"type": "Seeds",
		"img": "/img/rs3/herb_seed.png",
		"game": "rs3",
		"boss": "Chaos elemental",
		"npc": "Chaos elemental"
	},
	{
		"title": "Torstol seed",
		"quantity": 1,
		"price": 8505,
		"rarity": "rare",
		"droprate": null,
		"type": "Seeds",
		"img": "/img/rs3/herb_seed.png",
		"game": "rs3",
		"boss": "Chaos elemental",
		"npc": "Chaos elemental"
	},
	{
		"title": "Wildblood seed",
		"quantity": 2,
		"price": 96,
		"rarity": "common",
		"droprate": null,
		"type": "Seeds",
		"img": "/img/rs3/wildblood_seed.png",
		"game": "rs3",
		"boss": "Chaos elemental",
		"npc": "Chaos elemental"
	},
	{
		"title": "Jangerberry seed",
		"quantity": 2,
		"price": 1,
		"rarity": "common",
		"droprate": null,
		"type": "Seeds",
		"img": "/img/rs3/jangerberry_seed.png",
		"game": "rs3",
		"boss": "Chaos elemental",
		"npc": "Chaos elemental"
	},
	{
		"title": "Whiteberry seed",
		"quantity": 2,
		"price": 12,
		"rarity": "common",
		"droprate": null,
		"type": "Seeds",
		"img": "/img/rs3/whiteberry_seed.png",
		"game": "rs3",
		"boss": "Chaos elemental",
		"npc": "Chaos elemental"
	},
	{
		"title": "Poison ivy seed",
		"quantity": 2,
		"price": 11,
		"rarity": "uncommon",
		"droprate": null,
		"type": "Seeds",
		"img": "/img/rs3/poison_ivy_seed.png",
		"game": "rs3",
		"boss": "Chaos elemental",
		"npc": "Chaos elemental"
	},
	{
		"title": "Cactus seed",
		"quantity": 2,
		"price": 93,
		"rarity": "uncommon",
		"droprate": null,
		"type": "Seeds",
		"img": "/img/rs3/cactus_seed.png",
		"game": "rs3",
		"boss": "Chaos elemental",
		"npc": "Chaos elemental"
	},
	{
		"title": "Belladonna seed",
		"quantity": 2,
		"price": 104,
		"rarity": "common",
		"droprate": null,
		"type": "Seeds",
		"img": "/img/rs3/belladonna_seed.png",
		"game": "rs3",
		"boss": "Chaos elemental",
		"npc": "Chaos elemental"
	},
	{
		"title": "Coins",
		"quantity": 7500,
		"price": 1,
		"rarity": "uncommon",
		"droprate": null,
		"type": "Other",
		"img": "/img/rs3/coins.png",
		"game": "rs3",
		"boss": "Chaos elemental",
		"npc": "Chaos elemental"
	},
	{
		"title": "Bones",
		"quantity": 4,
		"price": 192,
		"rarity": "Common",
		"droprate": null,
		"type": "Other",
		"img": "/img/rs3/bones.png",
		"game": "rs3",
		"boss": "Chaos elemental",
		"npc": "Chaos elemental"
	},
	{
		"title": "Bat bones",
		"quantity": 5,
		"price": 270,
		"rarity": "common",
		"droprate": null,
		"type": "Other",
		"img": "/img/rs3/bat_bones.png",
		"game": "rs3",
		"boss": "Chaos elemental",
		"npc": "Chaos elemental"
	},
	{
		"title": "Big bones",
		"quantity": 3,
		"price": 412,
		"rarity": "common",
		"droprate": null,
		"type": "Other",
		"img": "/img/rs3/big_bones.png",
		"game": "rs3",
		"boss": "Chaos elemental",
		"npc": "Chaos elemental",
	},
	{
		"title": "Uncut sapphire",
		"quantity": 1,
		"price": 750,
		"rarity": "common",
		"droprate": null,
		"type": "Other",
		"img": "/img/rs3/uncut_sapphire.png",
		"game": "rs3",
		"boss": "Chaos elemental",
		"npc": "Chaos elemental",
	},
	{
		"title": "Uncut emerald",
		"quantity": 1,
		"price": 1424,
		"rarity": "common",
		"droprate": null,
		"type": "Other",
		"img": "/img/rs3/uncut_emerald.png",
		"game": "rs3",
		"boss": "Chaos elemental",
		"npc": "Chaos elemental",
	},
	{
		"title": "Uncut ruby",
		"quantity": 1,
		"price": 2187,
		"rarity": "uncommon",
		"droprate": null,
		"type": "Other",
		"img": "/img/rs3/uncut_ruby.png",
		"game": "rs3",
		"boss": "Chaos elemental",
		"npc": "Chaos elemental",
	},
	{
		"title": "Uncut diamond",
		"quantity": 1,
		"price": 3724,
		"rarity": "uncommon",
		"droprate": null,
		"type": "Other",
		"img": "/img/rs3/uncut_diamond.png",
		"game": "rs3",
		"boss": "Chaos elemental",
		"npc": "Chaos elemental",
	},
	{
		"title": "Dragon bones",
		"quantity": 1,
		"price": 1891,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "Other",
		"img": "/img/rs3/dragon_bones.png",
		"game": "rs3",
		"boss": "Chaos elemental",
		"npc": "Chaos elemental",
	},
	{
		"title": "Babydragon bones",
		"quantity": 1,
		"price": 926,
		"rarity": "uncommon",
		"droprate": null,
		"type": "Other",
		"img": "/img/rs3/babydragon_bones.png",
		"game": "rs3",
		"boss": "Chaos elemental",
		"npc": "Chaos elemental",
	},
	{
		"title": "Clue scroll (hard)",
		"quantity": 1,
		"price": null,
		"rarity": "rare",
		"droprate": null,
		"type": "Other",
		"img": "/img/rs3/clue_scroll_hard.png",
		"game": "rs3",
		"boss": "Chaos elemental",
		"npc": "Chaos elemental",
	},
	{
		"title": "Clue scroll (elite)",
		"quantity": 1,
		"price": null,
		"rarity": "rare",
		"droprate": null,
		"type": "Other",
		"img": "/img/rs3/clue_scroll_elite.png",
		"game": "rs3",
		"boss": "Chaos elemental",
		"npc": "Chaos elemental",
	},
	{
		"title": "Court summons",
		"quantity": 1,
		"price": null,
		"rarity": "Very rare",
		"droprate": null,
		"type": "Other",
		"img": "/img/rs3/court_summons.png",
		"game": "rs3",
		"boss": "Chaos elemental",
		"npc": "Chaos elemental",
	},
	{
		"title": "Ribs of chaos",
		"quantity": 1,
		"price": null,
		"rarity": "Very rare",
		"droprate": 2500,
		"type": "Other",
		"img": "/img/rs3/saradomin_statuette.png",
		"game": "rs3",
		"boss": "Chaos elemental",
		"npc": "Chaos elemental",
	}
];