/*
* RS3 Corporeal Beast drops list made by Alex.
*/

CorpDropsRs3 = [
	{
		"title": "Spectral sigil",
		"quantity": 1,
		"price": 758299,
		"rarity": "Very Rare",
		"droprate": 512,
		"type": "Sigils",
		"img": "/img/rs3/spectral_sigil.png",
		"game": "rs3",
		"boss": "Corporeal Beast",
		"npc": "Corporeal Beast"
	},
		{
		"title": "Arcane sigil",
		"quantity": 1,
		"price": 7025470,
		"rarity": "Very Rare",
		"droprate": 512,
		"type": "Sigils",
		"img": "/img/rs3/arcane_sigil.png",
		"game": "rs3",
		"boss": "Corporeal Beast",
		"npc": "Corporeal Beast"
	},
		{
		"title": "Elysian sigil",
		"quantity": 1,
		"price": 13465124,
		"rarity": "Very Rare",
		"droprate": 512,
		"type": "Sigils",
		"img": "/img/rs3/elysian_sigil.png",
		"game": "rs3",
		"boss": "Corporeal Beast",
		"npc": "Corporeal Beast"
	},
		{
		"title": "Divine sigil",
		"quantity": 1,
		"price": 15607602,
		"rarity": "Very Rare",
		"droprate": 512,
		"type": "Sigils",
		"img": "/img/rs3/divine_sigil.png",
		"game": "rs3",
		"boss": "Corporeal Beast",
		"npc": "Corporeal Beast"
	},
		{
		"title": "Adamant arrow",
		"quantity": 750,
		"price": 50,
		"rarity": "Common",
		"droprate": null,
		"type": "Equipment",
		"img": "/img/rs3/adamant_arrow_5.png",
		"game": "rs3",
		"boss": "Corporeal Beast",
		"npc": "Corporeal Beast"
	},
	{
		"title": "Runite bolts",
		"quantity": 250,
		"price": 306,
		"rarity": "Common",
		"droprate": null,
		"type": "Equipment",
		"img": "/img/rs3/runite_bolts_5.png",
		"game": "rs3",
		"boss": "Corporeal Beast",
		"npc": "Corporeal Beast"
	},
	{
		"title": "Cannonball",
		"quantity": 2000,
		"price": 293,
		"rarity": "Common",
		"droprate": null,
		"type": "Equipment",
		"img": "/img/rs3/cannonball.png",
		"game": "rs3",
		"boss": "Corporeal Beast",
		"npc": "Corporeal Beast"
	},
	{
		"title": "Mystic air staff",
		"quantity": 1,
		"price": 24566,
		"rarity": "Common",
		"droprate": null,
		"type": "Equipment",
		"img": "/img/rs3/mystic_air_staff.png",
		"game": "rs3",
		"boss": "Corporeal Beast",
		"npc": "Corporeal Beast"
	},
	{
		"title": "Mystic water staff",
		"quantity": 1,
		"price": 24630,
		"rarity": "Common",
		"droprate": null,
		"type": "Equipment",
		"img": "/img/rs3/mystic_water_staff.png",
		"game": "rs3",
		"boss": "Corporeal Beast",
		"npc": "Corporeal Beast"
	},
	{
		"title": "Mystic earth staff",
		"quantity": 1,
		"price": 24162,
		"rarity": "Common",
		"droprate": null,
		"type": "Equipment",
		"img": "/img/rs3/mystic_earth_staff.png",
		"game": "rs3",
		"boss": "Corporeal Beast",
		"npc": "Corporeal Beast"
	},
	{
		"title": "Mystic fire staff",
		"quantity": 1,
		"price": 24536,
		"rarity": "Common",
		"droprate": null,
		"type": "Equipment",
		"img": "/img/rs3/mystic_fire_staff.png",
		"game": "rs3",
		"boss": "Corporeal Beast",
		"npc": "Corporeal Beast"
	},
	{
		"title": "Mystic robe top (blue)",
		"quantity": 1,
		"price": 71015,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "Equipment",
		"img": "/img/rs3/mystic_robe_top_(blue).png",
		"game": "rs3",
		"boss": "Corporeal Beast",
		"npc": "Corporeal Beast"
	},
	{
		"title": "Mystic robe bottom (blue)",
		"quantity": 1,
		"price": 46871,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "Equipment",
		"img": "/img/rs3/mystic_robe_bottom_(blue).png",
		"game": "rs3",
		"boss": "Corporeal Beast",
		"npc": "Corporeal Beast"
	},
	{
		"title": "Spirit shield",
		"quantity": 1,
		"price": 38524,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "Equipment",
		"img": "/img/rs3/spirit_shield.png",
		"game": "rs3",
		"boss": "Corporeal Beast",
		"npc": "Corporeal Beast"
	},
	{
		"title": "Regen bracelet",
		"quantity": 1,
		"price": 119803,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "Equipment",
		"img": "/img/rs3/regen_bracelet.png",
		"game": "rs3",
		"boss": "Corporeal Beast",
		"npc": "Corporeal Beast"
	},
	{
		"title": "Onyx bolts (e)",
		"quantity": 175,
		"price": 8572,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "Equipment",
		"img": "/img/rs3/onyx_bolts_(e)_5.png",
		"game": "rs3",
		"boss": "Corporeal Beast",
		"npc": "Corporeal Beast"
	},
	{
		"title": "Adamantite ore",
		"quantity": 125,
		"price": 1401,
		"rarity": "Common",
		"droprate": null,
		"type": "Materials",
		"img": "/img/rs3/adamantite_ore.png",
		"game": "rs3",
		"boss": "Corporeal Beast",
		"npc": "Corporeal Beast"
	},
	{
		"title": "Runite ore",
		"quantity": 20,
		"price": 11053,
		"rarity": "Common",
		"droprate": null,
		"type": "Materials",
		"img": "/img/rs3/runite_ore.png",
		"game": "rs3",
		"boss": "Corporeal Beast",
		"npc": "Corporeal Beast"
	},
	{
		"title": "Adamant bar",
		"quantity": 35,
		"price": 3150,
		"rarity": "Common",
		"droprate": null,
		"type": "Materials",
		"img": "/img/rs3/adamant_bar.png",
		"game": "rs3",
		"boss": "Corporeal Beast",
		"npc": "Corporeal Beast"
	},
	{
		"title": "Teak plank",
		"quantity": 100,
		"price": 722,
		"rarity": "Common",
		"droprate": null,
		"type": "Materials",
		"img": "/img/rs3/teak_plank.png",
		"game": "rs3",
		"boss": "Corporeal Beast",
		"npc": "Corporeal Beast"
	},
	{
		"title": "Mahogany logs",
		"quantity": 150,
		"price": 693,
		"rarity": "Common",
		"droprate": null,
		"type": "Materials",
		"img": "/img/rs3/mahogany_logs.png",
		"game": "rs3",
		"boss": "Corporeal Beast",
		"npc": "Corporeal Beast"
	},
	{
		"title": "Magic logs",
		"quantity": 75,
		"price": 908,
		"rarity": "Common",
		"droprate": null,
		"type": "Materials",
		"img": "/img/rs3/magic_logs.png",
		"game": "rs3",
		"boss": "Corporeal Beast",
		"npc": "Corporeal Beast"
	},
	{
		"title": "Green dragonhide",
		"quantity": 100,
		"price": 1498,
		"rarity": "Common",
		"droprate": null,
		"type": "Materials",
		"img": "/img/rs3/green_dragonhide.png",
		"game": "rs3",
		"boss": "Corporeal Beast",
		"npc": "Corporeal Beast"
	},
	{
		"title": "Raw shark",
		"quantity": 70,
		"price": 753,
		"rarity": "Common",
		"droprate": null,
		"type": "Other",
		"img": "/img/rs3/raw_shark.png",
		"game": "rs3",
		"boss": "Corporeal Beast",
		"npc": "Corporeal Beast"
	},
	{
		"title": "White berries",
		"quantity": 120,
		"price": 848,
		"rarity": "Common",
		"droprate": null,
		"type": "Other",
		"img": "/img/rs3/white_berries.png",
		"game": "rs3",
		"boss": "Corporeal Beast",
		"npc": "Corporeal Beast"
	},
	{
		"title": "Limpwurt root",
		"quantity": 20,
		"price": 987,
		"rarity": "Common",
		"droprate": null,
		"type": "Other",
		"img": "/img/rs3/limpwurt_root.png",
		"game": "rs3",
		"boss": "Corporeal Beast",
		"npc": "Corporeal Beast"
	},
	{
		"title": "Desert goat horn",
		"quantity": 120,
		"price": 554,
		"rarity": "Common",
		"droprate": null,
		"type": "Other",
		"img": "/img/rs3/desert_goat_horn.png",
		"game": "rs3",
		"boss": "Corporeal Beast",
		"npc": "Corporeal Beast"
	},
	{
		"title": "Uncut diamond (other)",
		"quantity": 15,
		"price": 3724,
		"rarity": "Common",
		"droprate": null,
		"type": "Other",
		"img": "/img/rs3/uncut_diamond.png",
		"game": "rs3",
		"boss": "Corporeal Beast",
		"npc": "Corporeal Beast"
	},
	{
		"title": "Watermelon seed",
		"quantity": 24,
		"price": 1922,
		"rarity": "Common",
		"droprate": null,
		"type": "Other",
		"img": "/img/rs3/watermelon_seed_5.png",
		"game": "rs3",
		"boss": "Corporeal Beast",
		"npc": "Corporeal Beast"
	},
	{
		"title": "Law rune",
		"quantity": 100,
		"price": 232,
		"rarity": "Common",
		"droprate": null,
		"type": "Other",
		"img": "/img/rs3/law_rune.png",
		"game": "rs3",
		"boss": "Corporeal Beast",
		"npc": "Corporeal Beast"
	},
	{
		"title": "Tuna potato",
		"quantity": 30,
		"price": 1141,
		"rarity": "Common",
		"droprate": null,
		"type": "Other",
		"img": "/img/rs3/tuna_potato.png",
		"game": "rs3",
		"boss": "Corporeal Beast",
		"npc": "Corporeal Beast"
	},
	{
		"title": "Yew seed",
		"quantity": 1,
		"price": 63943,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "Other",
		"img": "/img/rs3/yew_seed_1.png",
		"game": "rs3",
		"boss": "Corporeal Beast",
		"npc": "Corporeal Beast"
	},
	{
		"title": "Ranarr seed",
		"quantity": 13,
		"price": 796,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "Other",
		"img": "/img/rs3/herb_seed_5.png",
		"game": "rs3",
		"boss": "Corporeal Beast",
		"npc": "Corporeal Beast"
	},
	{
		"title": "Toadflax seed",
		"quantity": 10,
		"price": 1025,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "Other",
		"img": "/img/rs3/herb_seed_5.png",
		"game": "rs3",
		"boss": "Corporeal Beast",
		"npc": "Corporeal Beast"
	},
	{
		"title": "Antipoison++ (4)",
		"quantity": 40,
		"price": 815,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "Other",
		"img": "/img/rs3/antipoison++_(4).png",
		"game": "rs3",
		"boss": "Corporeal Beast",
		"npc": "Corporeal Beast"
	},
	{
		"title": "Clue scroll (hard)",
		"quantity": 1,
		"price": null,
		"rarity": "Rare",
		"droprate": null,
		"type": "Other",
		"img": "/img/rs3/clue_scroll_(hard).png",
		"game": "rs3",
		"boss": "Corporeal Beast",
		"npc": "Corporeal Beast"
	},
	{
		"title": "Clue scroll (elite)",
		"quantity": 1,
		"price": null,
		"rarity": "Rare",
		"droprate": null,
		"type": "Other",
		"img": "/img/rs3/clue_scroll_(elite).png",
		"game": "rs3",
		"boss": "Corporeal Beast",
		"npc": "Corporeal Beast"
	},
	{
		"title": "Holy elixir",
		"quantity": 1,
		"price": 761861,
		"rarity": "Common",
		"droprate": null,
		"type": "Rare",
		"img": "/img/rs3/holy_elixir.png",
		"game": "rs3",
		"boss": "Corporeal Beast",
		"npc": "Corporeal Beast"
	},
	{
		"title": "Crystal key",
		"quantity": 1,
		"price": 60232,
		"rarity": "Common",
		"droprate": null,
		"type": "Very rare",
		"img": "/img/rs3/crystal_key.png",
		"game": "rs3",
		"boss": "Corporeal Beast",
		"npc": "Corporeal Beast"
	},
	{
		"title": "Corporeal bone",
		"quantity": 1,
		"price": null,
		"rarity": "Very rare",
		"droprate": null,
		"type": "Other",
		"img": "/img/rs3/corporeal_bone.png",
		"game": "rs3",
		"boss": "Corporeal Beast",
		"npc": "Corporeal Beast"
	},
	{
		"title": "Coins",
		"quantity": 23500,
		"price": 1,
		"rarity": "Common",
		"droprate": null,
		"type": "Uncuts",
		"img": "/img/rs3/coins_10000.png",
		"game": "rs3",
		"boss": "Corporeal Beast",
		"npc": "Corporeal Beast"
	},
	{
		"title": "Uncut sapphire",
		"quantity": 4,
		"price": 750,
		"rarity": "Common",
		"droprate": null,
		"type": "Uncuts",
		"img": "/img/rs3/uncut_sapphire.png",
		"game": "rs3",
		"boss": "Corporeal Beast",
		"npc": "Corporeal Beast"
	},
	{
		"title": "Uncut emerald",
		"quantity": 4,
		"price": 1424,
		"rarity": "Common",
		"droprate": null,
		"type": "Uncuts",
		"img": "/img/rs3/uncut_emerald.png",
		"game": "rs3",
		"boss": "Corporeal Beast",
		"npc": "Corporeal Beast"
	},
	{
		"title": "Uncut ruby",
		"quantity": 2,
		"price": 2187,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "Uncuts",
		"img": "/img/rs3/uncut_ruby.png",
		"game": "rs3",
		"boss": "Corporeal Beast",
		"npc": "Corporeal Beast"
	},
	{
		"title": "Uncut diamond",
		"quantity": 2,
		"price": 3724,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "Uncuts",
		"img": "/img/rs3/uncut_diamond.png",
		"game": "rs3",
		"boss": "Corporeal Beast",
		"npc": "Corporeal Beast"
	},
	{
		"title": "Uncut dragonstone",
		"quantity": 2,
		"price": 12768,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "Uncuts",
		"img": "/img/rs3/uncut_dragonstone.png",
		"game": "rs3",
		"boss": "Corporeal Beast",
		"npc": "Corporeal Beast"
	},
	{
		"title": "Nature talisman",
		"quantity": 2,
		"price": 210,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "Uncuts",
		"img": "/img/rs3/nature_talisman.png",
		"game": "rs3",
		"boss": "Corporeal Beast",
		"npc": "Corporeal Beast"
	}	
];