/*
* OSRS Corporeal Beast drops list made by Alex.
*/

CorpDropsOsrs = [
	{
		"title": "Spectral sigil",
		"quantity": 1,
		"price": null,
		"rarity": "Very Rare",
		"droprate": 1365,
		"type": "Sigils",
		"img": "/img/osrs/spectral_sigil.png",
		"game": "rs3",
		"boss": "Corporeal Beast",
		"npc": "Corporeal Beast"
	},
		{
		"title": "Arcane sigil",
		"quantity": 1,
		"price": null,
		"rarity": "Very Rare",
		"droprate": 1365,
		"type": "Sigils",
		"img": "/img/osrs/arcane_sigil.png",
		"game": "rs3",
		"boss": "Corporeal Beast",
		"npc": "Corporeal Beast"
	},
		{
		"title": "Elysian sigil",
		"quantity": 1,
		"price": null,
		"rarity": "Very Rare",
		"droprate": 4095,
		"type": "Sigils",
		"img": "/img/osrs/elysian_sigil.png",
		"game": "rs3",
		"boss": "Corporeal Beast",
		"npc": "Corporeal Beast"
	},
		{
		"title": "Adamant arrow",
		"quantity": 750,
		"price": null,
		"rarity": "Common",
		"droprate": null,
		"type": "Equipment",
		"img": "/img/osrs/adamant_arrow_5.png",
		"game": "rs3",
		"boss": "Corporeal Beast",
		"npc": "Corporeal Beast"
	},
	{
		"title": "Runite bolts",
		"quantity": 250,
		"price": null,
		"rarity": "Common",
		"droprate": null,
		"type": "Equipment",
		"img": "/img/osrs/runite_bolts_5.png",
		"game": "rs3",
		"boss": "Corporeal Beast",
		"npc": "Corporeal Beast"
	},
	{
		"title": "Cannonball",
		"quantity": 2000,
		"price": null,
		"rarity": "Common",
		"droprate": null,
		"type": "Equipment",
		"img": "/img/osrs/cannonball.png",
		"game": "rs3",
		"boss": "Corporeal Beast",
		"npc": "Corporeal Beast"
	},
	{
		"title": "Mystic air staff",
		"quantity": 1,
		"price": null,
		"rarity": "Common",
		"droprate": null,
		"type": "Equipment",
		"img": "/img/osrs/mystic_air_staff.png",
		"game": "rs3",
		"boss": "Corporeal Beast",
		"npc": "Corporeal Beast"
	},
	{
		"title": "Mystic water staff",
		"quantity": 1,
		"price": null,
		"rarity": "Common",
		"droprate": null,
		"type": "Equipment",
		"img": "/img/osrs/mystic_water_staff.png",
		"game": "rs3",
		"boss": "Corporeal Beast",
		"npc": "Corporeal Beast"
	},
	{
		"title": "Mystic earth staff",
		"quantity": 1,
		"price": null,
		"rarity": "Common",
		"droprate": null,
		"type": "Equipment",
		"img": "/img/osrs/mystic_earth_staff.png",
		"game": "rs3",
		"boss": "Corporeal Beast",
		"npc": "Corporeal Beast"
	},
	{
		"title": "Mystic fire staff",
		"quantity": 1,
		"price": null,
		"rarity": "Common",
		"droprate": null,
		"type": "Equipment",
		"img": "/img/osrs/mystic_fire_staff.png",
		"game": "rs3",
		"boss": "Corporeal Beast",
		"npc": "Corporeal Beast"
	},
	{
		"title": "Mystic robe top (blue)",
		"quantity": 1,
		"price": null,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "Equipment",
		"img": "/img/osrs/mystic_robe_top_(blue).png",
		"game": "rs3",
		"boss": "Corporeal Beast",
		"npc": "Corporeal Beast"
	},
	{
		"title": "Mystic robe bottom (blue)",
		"quantity": 1,
		"price": null,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "Equipment",
		"img": "/img/osrs/mystic_robe_bottom_(blue).png",
		"game": "rs3",
		"boss": "Corporeal Beast",
		"npc": "Corporeal Beast"
	},
	{
		"title": "Spirit shield",
		"quantity": 1,
		"price": null,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "Equipment",
		"img": "/img/osrs/spirit_shield.png",
		"game": "rs3",
		"boss": "Corporeal Beast",
		"npc": "Corporeal Beast"
	},
	{
		"title": "Onyx bolts (e)",
		"quantity": 175,
		"price": null,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "Equipment",
		"img": "/img/osrs/onyx_bolts_(e)_5.png",
		"game": "rs3",
		"boss": "Corporeal Beast",
		"npc": "Corporeal Beast"
	},
	{
		"title": "Adamantite ore",
		"quantity": 125,
		"price": null,
		"rarity": "Common",
		"droprate": null,
		"type": "Materials",
		"img": "/img/osrs/adamantite_ore.png",
		"game": "rs3",
		"boss": "Corporeal Beast",
		"npc": "Corporeal Beast"
	},
	{
		"title": "Runite ore",
		"quantity": 20,
		"price": null,
		"rarity": "Common",
		"droprate": null,
		"type": "Materials",
		"img": "/img/osrs/runite_ore.png",
		"game": "rs3",
		"boss": "Corporeal Beast",
		"npc": "Corporeal Beast"
	},
	{
		"title": "Adamant bar",
		"quantity": 35,
		"price": null,
		"rarity": "Common",
		"droprate": null,
		"type": "Materials",
		"img": "/img/osrs/adamant_bar.png",
		"game": "rs3",
		"boss": "Corporeal Beast",
		"npc": "Corporeal Beast"
	},
	{
		"title": "Teak plank",
		"quantity": 100,
		"price": null,
		"rarity": "Common",
		"droprate": null,
		"type": "Materials",
		"img": "/img/osrs/teak_plank.png",
		"game": "rs3",
		"boss": "Corporeal Beast",
		"npc": "Corporeal Beast"
	},
	{
		"title": "Mahogany logs",
		"quantity": 150,
		"price": null,
		"rarity": "Common",
		"droprate": null,
		"type": "Materials",
		"img": "/img/osrs/mahogany_logs.png",
		"game": "rs3",
		"boss": "Corporeal Beast",
		"npc": "Corporeal Beast"
	},
	{
		"title": "Magic logs",
		"quantity": 75,
		"price": null,
		"rarity": "Common",
		"droprate": null,
		"type": "Materials",
		"img": "/img/osrs/magic_logs.png",
		"game": "rs3",
		"boss": "Corporeal Beast",
		"npc": "Corporeal Beast"
	},
	{
		"title": "Green dragonhide",
		"quantity": 100,
		"price": null,
		"rarity": "Common",
		"droprate": null,
		"type": "Materials",
		"img": "/img/osrs/green_dragonhide.png",
		"game": "rs3",
		"boss": "Corporeal Beast",
		"npc": "Corporeal Beast"
	},
	{
		"title": "Raw shark",
		"quantity": 70,
		"price": null,
		"rarity": "Common",
		"droprate": null,
		"type": "Other",
		"img": "/img/osrs/raw_shark.png",
		"game": "rs3",
		"boss": "Corporeal Beast",
		"npc": "Corporeal Beast"
	},
	{
		"title": "White berries",
		"quantity": 120,
		"price": null,
		"rarity": "Common",
		"droprate": null,
		"type": "Other",
		"img": "/img/osrs/white_berries.png",
		"game": "rs3",
		"boss": "Corporeal Beast",
		"npc": "Corporeal Beast"
	},
	{
		"title": "Desert goat horn",
		"quantity": 120,
		"price": null,
		"rarity": "Common",
		"droprate": null,
		"type": "Other",
		"img": "/img/osrs/desert_goat_horn.png",
		"game": "rs3",
		"boss": "Corporeal Beast",
		"npc": "Corporeal Beast"
	},
	{
		"title": "Watermelon seed",
		"quantity": 24,
		"price": 1922,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "Other",
		"img": "/img/osrs/watermelon_seed_1.png",
		"game": "rs3",
		"boss": "Corporeal Beast",
		"npc": "Corporeal Beast"
	},
	{
		"title": "Tuna potato",
		"quantity": 30,
		"price": null,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "Other",
		"img": "/img/osrs/tuna_potato.png",
		"game": "rs3",
		"boss": "Corporeal Beast",
		"npc": "Corporeal Beast"
	},
	{
		"title": "Ranarr seed",
		"quantity": 10,
		"price": null,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "Other",
		"img": "/img/osrs/herb_seed_1.png",
		"game": "rs3",
		"boss": "Corporeal Beast",
		"npc": "Corporeal Beast"
	},
	{
		"title": "Antipoison++ (4)",
		"quantity": 40,
		"price": null,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "Other",
		"img": "/img/osrs/antipoison++_(4).png",
		"game": "rs3",
		"boss": "Corporeal Beast",
		"npc": "Corporeal Beast"
	},
	{
		"title": "Clue scroll (elite)",
		"quantity": 1,
		"price": null,
		"rarity": "Rare",
		"droprate": null,
		"type": "Other",
		"img": "/img/osrs/clue_scroll_(elite).png",
		"game": "rs3",
		"boss": "Corporeal Beast",
		"npc": "Corporeal Beast"
	},
	{
		"title": "Holy elixir",
		"quantity": 1,
		"price": 761861,
		"rarity": "Common",
		"droprate": null,
		"type": "Rare",
		"img": "/img/osrs/holy_elixir.png",
		"game": "rs3",
		"boss": "Corporeal Beast",
		"npc": "Corporeal Beast"
	},
	{
		"title": "Pet dark core",
		"quantity": 1,
		"price": null,
		"rarity": "Very rare",
		"droprate": 5000,
		"type": "Other",
		"img": "/img/osrs/pet_dark_core.png",
		"game": "rs3",
		"boss": "Corporeal Beast",
		"npc": "Corporeal Beast"
	},
	{
		"title": "Coins",
		"quantity": 35000,
		"price": 1,
		"rarity": "Common",
		"droprate": null,
		"type": "Uncuts",
		"img": "/img/osrs/coins_10000.png",
		"game": "rs3",
		"boss": "Corporeal Beast",
		"npc": "Corporeal Beast"
	},
	{
		"title": "Uncut sapphire",
		"quantity": 6,
		"price": null,
		"rarity": "Common",
		"droprate": null,
		"type": "Uncuts",
		"img": "/img/osrs/uncut_sapphire.png",
		"game": "rs3",
		"boss": "Corporeal Beast",
		"npc": "Corporeal Beast"
	},
	{
		"title": "Uncut emerald",
		"quantity": 5,
		"price": null,
		"rarity": "Common",
		"droprate": null,
		"type": "Uncuts",
		"img": "/img/osrs/uncut_emerald.png",
		"game": "rs3",
		"boss": "Corporeal Beast",
		"npc": "Corporeal Beast"
	},
	{
		"title": "Uncut ruby",
		"quantity": 4,
		"price": null,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "Uncuts",
		"img": "/img/osrs/uncut_ruby.png",
		"game": "rs3",
		"boss": "Corporeal Beast",
		"npc": "Corporeal Beast"
	},
	{
		"title": "Uncut diamond",
		"quantity": 4,
		"price": null,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "Uncuts",
		"img": "/img/osrs/uncut_diamond.png",
		"game": "rs3",
		"boss": "Corporeal Beast",
		"npc": "Corporeal Beast"
	},
	{
		"title": "Shield left half",
		"quantity": 1,
		"price": null,
		"rarity": "Very rare",
		"droprate": null,
		"type": "Uncuts",
		"img": "/img/osrs/shield_left_half.png",
		"game": "rs3",
		"boss": "Corporeal Beast",
		"npc": "Corporeal Beast"
	},
	{
		"title": "Dragon spear",
		"quantity": 1,
		"price": null,
		"rarity": "Very rare",
		"droprate": null,
		"type": "Uncuts",
		"img": "/img/osrs/dragon_spear.png",
		"game": "rs3",
		"boss": "Corporeal Beast",
		"npc": "Corporeal Beast"
	},
	{
		"title": "Nature talisman",
		"quantity": 4,
		"price": null,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "Uncuts",
		"img": "/img/osrs/nature_talisman.png",
		"game": "rs3",
		"boss": "Corporeal Beast",
		"npc": "Corporeal Beast"
	},
	{
		"title": "Law rune",
		"quantity": 100,
		"price": 232,
		"rarity": "Common",
		"droprate": null,
		"type": "Essence and runes",
		"img": "/img/osrs/law_rune.png",
		"game": "rs3",
		"boss": "Corporeal Beast",
		"npc": "Corporeal Beast"
	},
	{
		"title": "Pure essence",
		"quantity": 2500,
		"price": null,
		"rarity": "Common",
		"droprate": null,
		"type": "Essence and runes",
		"img": "/img/osrs/pure_essence.png",
		"game": "rs3",
		"boss": "Corporeal Beast",
		"npc": "Corporeal Beast"
	},
	{
		"title": "Death rune",
		"quantity": 300,
		"price": 1,
		"rarity": "Common",
		"droprate": null,
		"type": "Essence and runes",
		"img": "/img/osrs/death_rune.png",
		"game": "rs3",
		"boss": "Corporeal Beast",
		"npc": "Corporeal Beast"
	},
	{
		"title": "Soul rune",
		"quantity": 250,
		"price": null,
		"rarity": "Common",
		"droprate": null,
		"type": "Essence and runes",
		"img": "/img/osrs/soul_rune.png",
		"game": "rs3",
		"boss": "Corporeal Beast",
		"npc": "Corporeal Beast"
	},
	{
		"title": "Cosmic rune",
		"quantity": 500,
		"price": null,
		"rarity": "Common",
		"droprate": null,
		"type": "Essence and runes",
		"img": "/img/osrs/cosmic_rune.png",
		"game": "rs3",
		"boss": "Corporeal Beast",
		"npc": "Corporeal Beast"
	}	
];