/*
* OSRS Crazy archaeologist drops list made by Mokuin.
*/

CrazyArcheologistDrops = [
	{
		"title": "Amulet of power",
		"quantity": 1,
		"price": 2646,
		"rarity": "Common",
		"droprate": null,
		"type": "armour",
		"img": "/img/osrs/amulet_of_power.png",
		"game": "osrs",
		"boss": "Crazy archaeologist",
		"npc": "Crazy archaeologist"
	},
	{
		"title": "Red d'hide body",
		"quantity": 1,
		"price": 6661,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "armour",
		"img": "/img/osrs/red_dhide_body.png",
		"game": "osrs",
		"boss": "Crazy archaeologist",
		"npc": "Crazy archaeologist"
	},
	{
		"title": "Rune knife",
		"quantity": 10,
		"price": 1361,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "armour",
		"img": "/img/osrs/rune_knife.png",
		"game": "osrs",
		"boss": "Crazy archaeologist",
		"npc": "Crazy archaeologist"
	},
	{
		"title": "Rune crossbow",
		"quantity": 2,
		"price": 10642,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "weapons",
		"img": "/img/osrs/rune_crossbow.png",
		"game": "osrs",
		"boss": "Crazy archaeologist",
		"npc": "Crazy archaeologist"
	},
	{
		"title": "Rune battleaxe",
		"quantity": 1,
		"price": 26312,
		"rarity": "Rare",
		"droprate": null,
		"type": "weapons",
		"img": "/img/osrs/rune_battleaxe.png",
		"game": "osrs",
		"boss": "Crazy archaeologist",
		"npc": "Crazy archaeologist"
	},
	{
		"title": "Dragon arrow",
		"quantity": 75,
		"price": 1354,
		"rarity": "Rare",
		"droprate": null,
		"type": "weapons",
		"img": "/img/osrs/dragon_arrow.png",
		"game": "osrs",
		"boss": "Crazy archaeologist",
		"npc": "Crazy archaeologist"
	},
	{
		"title": "Mud rune",
		"quantity": 30,
		"price": 239,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "weapons",
		"img": "/img/osrs/mud_rune.png",
		"game": "osrs",
		"boss": "Crazy archaeologist",
		"npc": "Crazy archaeologist"
	},
	{
		"title": "Death rune",
		"quantity": 50,
		"price": 219,
		"rarity": "Rare",
		"droprate": null,
		"type": "runes",
		"img": "/img/osrs/death_rune.png",
		"game": "osrs",
		"boss": "Crazy archaeologist",
		"npc": "Crazy archaeologist"
	},
	{
		"title": "Dwarf weed",
		"quantity": 4,
		"price": 1646,
		"rarity": "Common",
		"droprate": null,
		"type": "herbs",
		"img": "/img/osrs/dwarf_weed.png",
		"game": "osrs",
		"boss": "Crazy archaeologist",
		"npc": "Crazy archaeologist"
	},
	{
		"title": "Coins",
		"quantity": 2000,
		"price": 1,
		"rarity": "Common",
		"droprate": null,
		"type": "other",
		"img": "/img/osrs/coins.png",
		"game": "osrs",
		"boss": "Crazy archaeologist",
		"npc": "Crazy archaeologist"
	},
	{
		"title": "Muddy key",
		"quantity": 1,
		"price": 20441,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "other",
		"img": "/img/osrs/muddy_key.png",
		"game": "osrs",
		"boss": "Crazy archaeologist",
		"npc": "Crazy archaeologist"
	},
	{
		"title": "Anchovy pizza",
		"quantity": 8,
		"price": 853,
		"rarity": "Common",
		"droprate": null,
		"type": "other",
		"img": "/img/osrs/anchovy_pizza.png",
		"game": "osrs",
		"boss": "Crazy archaeologist",
		"npc": "Crazy archaeologist"
	},
	{
		"title": "Silver ore",
		"quantity": 40,
		"price": 75,
		"rarity": "Common",
		"droprate": null,
		"type": "other",
		"img": "/img/osrs/silver_ore.png",
		"game": "osrs",
		"boss": "Crazy archaeologist",
		"npc": "Crazy archaeologist"
	},
	{
		"title": "Cannonball",
		"quantity": 150,
		"price": 185,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "other",
		"img": "/img/osrs/cannonball.png",
		"game": "osrs",
		"boss": "Crazy archaeologist",
		"npc": "Crazy archaeologist"
	},
	{
		"title": "Prayer potion (4)",
		"quantity": 1,
		"price": 7666,
		"rarity": "Common",
		"droprate": null,
		"type": "other",
		"img": "/img/osrs/prayer_potion_4.png",
		"game": "osrs",
		"boss": "Crazy archaeologist",
		"npc": "Crazy archaeologist"
	},
	{
		"title": "Shark",
		"quantity": 1,
		"price": 906,
		"rarity": "Common",
		"droprate": null,
		"type": "other",
		"img": "/img/osrs/shark.png",
		"game": "osrs",
		"boss": "Crazy archaeologist",
		"npc": "Crazy archaeologist"
	},
	{
		"title": "Uncut sapphire",
		"quantity": 4,
		"price": 585,
		"rarity": "Common",
		"droprate": null,
		"type": "other",
		"img": "/img/osrs/uncut_sapphire.png",
		"game": "osrs",
		"boss": "Crazy archaeologist",
		"npc": "Crazy archaeologist"
	},
	{
		"title": "Uncut emerald",
		"quantity": 6,
		"price": 1380,
		"rarity": "Common",
		"droprate": null,
		"type": "other",
		"img": "/img/osrs/uncut_emerald.png",
		"game": "osrs",
		"boss": "Crazy archaeologist",
		"npc": "Crazy archaeologist"
	},
	{
		"title": "Red dragonhide",
		"quantity": 10,
		"price": 2687,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "other",
		"img": "/img/osrs/red_dragonhide.png",
		"game": "osrs",
		"boss": "Crazy archaeologist",
		"npc": "Crazy archaeologist"
	},
	{
		"title": "White berries",
		"quantity": 10,
		"price": 1046,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "other",
		"img": "/img/osrs/white_berries.png",
		"game": "osrs",
		"boss": "Crazy archaeologist",
		"npc": "Crazy archaeologist"
	},
	{
		"title": "Potato with cheese",
		"quantity": 3,
		"price": 565,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "other",
		"img": "/img/osrs/potato_with_cheese.png",
		"game": "osrs",
		"boss": "Crazy archaeologist",
		"npc": "Crazy archaeologist"
	},
	{
		"title": "Onyx bolt tips",
		"quantity": 12,
		"price": 8415,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "other",
		"img": "/img/osrs/onyx_bolt_tips.png",
		"game": "osrs",
		"boss": "Crazy archaeologist",
		"npc": "Crazy archaeologist"
	},
	{
		"title": "Mysterious emblem",
		"quantity": 1,
		"price": null,
		"rarity": "Uncommon",
		"droprate": 50,
		"type": "other",
		"img": "/img/osrs/mysterious_emblem.png",
		"game": "osrs",
		"boss": "Crazy archaeologist",
		"npc": "Crazy archaeologist"
	},
	{
		"title": "Odium shard 2",
		"quantity": 1,
		"price": 493452,
		"rarity": "Rare",
		"droprate": null,
		"type": "other",
		"img": "/img/osrs/odium_shard_2.png",
		"game": "osrs",
		"boss": "Crazy archaeologist",
		"npc": "Crazy archaeologist"
	},
	{
		"title": "Malediction shard 2",
		"quantity": 1,
		"price": 354331,
		"rarity": "Rare",
		"droprate": null,
		"type": "other",
		"img": "/img/osrs/malediction_shard_2.png",
		"game": "osrs",
		"boss": "Crazy archaeologist",
		"npc": "Crazy archaeologist"
	},
	{
		"title": "Clue scroll (hard)",
		"quantity": 1,
		"price": null,
		"rarity": "Rare",
		"droprate": null,
		"type": "other",
		"img": "/img/osrs/clue_scroll_hard.png",
		"game": "osrs",
		"boss": "Crazy archaeologist",
		"npc": "Crazy archaeologist"
	},
	{
		"title": "Long bone",
		"quantity": 1,
		"price": null,
		"rarity": "Rare",
		"droprate": null,
		"type": "other",
		"img": "/img/osrs/long_bone.png",
		"game": "osrs",
		"boss": "Crazy archaeologist",
		"npc": "Crazy archaeologist"
	},
	{
		"title": "Fedora",
		"quantity": 1,
		"price": 53415,
		"rarity": "Rare",
		"droprate": 128,
		"type": "other",
		"img": "/img/osrs/fedora.png",
		"game": "osrs",
		"boss": "Crazy archaeologist",
		"npc": "Crazy archaeologist"
	}
];

