/*
* RS3 Giant Mole drops list made by Aimer.
*/

GiantMoleDropsRs3 = [
	{
		"title": "Mole claw",
		"quantity": 1,
		"price": 5035,
		"rarity": "Always",
		"droprate": null,
		"type": "100% drops",
		"img": "/img/rs3/mole_claw.png",
		"game": "rs3",
		"boss": "Giant mole",
		"npc": "Giant mole"
	},
	{
		"title": "Mole skin",
		"quantity": 3,
		"price": 5439,
		"rarity": "Always",
		"droprate": null,
		"type": "100% drops",
		"img": "/img/rs3/mole_skin.png",
		"game": "rs3",
		"boss": "Giant mole",
		"npc": "Giant mole"
	},
	{
		"title": "Mole nose",
		"quantity": 1,
		"price": null,
		"rarity": "Always",
		"droprate": null,
		"type": "100% drops",
		"img": "/img/rs3/mole_nose.png",
		"game": "rs3",
		"boss": "Giant mole",
		"npc": "Giant mole"
	},
	{
		"title": "Numbing root",
		"quantity": 4,
		"price": 5012,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "Special drops",
		"img": "/img/rs3/numbing_root.png",
		"game": "rs3",
		"boss": "Giant mole",
		"npc": "Giant mole"
	},
	{
		"title": "Clingy mole",
		"quantity": 1,
		"price": 12183,
		"rarity": "Rare",
		"droprate": null,
		"type": "Special drops",
		"img": "/img/rs3/clingy_mole.png",
		"game": "rs3",
		"boss": "Giant mole",
		"npc": "Giant mole"
	},
	{
		"title": "Dragon 2h sword",
		"quantity": 1,
		"price": 133263,
		"rarity": "Rare",
		"droprate": null,
		"type": "Special drops",
		"img": "/img/rs3/dragon_2h_sword.png",
		"game": "rs3",
		"boss": "Giant mole",
		"npc": "Giant mole"
	},
	{
		"title": "Grimy irit",
		"quantity": 6,
		"price": 2114,
		"rarity": "Common",
		"droprate": null,
		"type": "Herbs",
		"img": "/img/rs3/grimy_irit.png",
		"game": "rs3",
		"boss": "Giant mole",
		"npc": "Giant mole"
	},
	{
		"title": "Grimy ranarr",
		"quantity": 6,
		"price": 2270,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "Herbs",
		"img": "/img/rs3/grimy_ranarr.png",
		"game": "rs3",
		"boss": "Giant mole",
		"npc": "Giant mole"
	},
	{
		"title": "Long, sharp claws",
		"quantity": 1,
		"price": null,
		"rarity": "Common",
		"droprate": null,
		"type": "Other",
		"img": "/img/rs3/long,_sharp_claws.png",
		"game": "rs3",
		"boss": "Giant mole",
		"npc": "Giant mole"
	},
	{
		"title": "Coins",
		"quantity": 19000,
		"price": 1,
		"rarity": "Uncmmon",
		"droprate": null,
		"type": "Other",
		"img": "/img/rs3/coins.png",
		"game": "rs3",
		"boss": "Giant mole",
		"npc": "Giant mole"
	},
	{
		"title": "Yew logs",
		"quantity": 25,
		"price": 268,
		"rarity": "Uncmmon",
		"droprate": null,
		"type": "Other",
		"img": "/img/rs3/yew_logs.png",
		"game": "rs3",
		"boss": "Giant mole",
		"npc": "Giant mole"
	},
	{
		"title": "Adamant bar",
		"quantity": 2,
		"price": 3051,
		"rarity": "Uncmmon",
		"droprate": null,
		"type": "Other",
		"img": "/img/rs3/adamant_bar.png",
		"game": "rs3",
		"boss": "Giant mole",
		"npc": "Giant mole"
	},
	{
		"title": "Iron ore",
		"quantity": 48,
		"price": 194,
		"rarity": "Uncmmon",
		"droprate": null,
		"type": "Other",
		"img": "/img/rs3/iron_ore.png",
		"game": "rs3",
		"boss": "Giant mole",
		"npc": "Giant mole"
	},
	{
		"title": "Red dragonhide",
		"quantity": 3,
		"price": 2570,
		"rarity": "Uncmmon",
		"droprate": null,
		"type": "Other",
		"img": "/img/rs3/red_dragonhide.png",
		"game": "rs3",
		"boss": "Giant mole",
		"npc": "Giant mole"
	},
	{
		"title": "Pure essence",
		"quantity": 500,
		"price": 21,
		"rarity": "Uncmmon",
		"droprate": null,
		"type": "Other",
		"img": "/img/rs3/pure_essence.png",
		"game": "rs3",
		"boss": "Giant mole",
		"npc": "Giant mole"
	},
	{
		"title": "Blood rune",
		"quantity": 60,
		"price": 448,
		"rarity": "Uncmmon",
		"droprate": null,
		"type": "Other",
		"img": "/img/rs3/blood_rune.png",
		"game": "rs3",
		"boss": "Giant mole",
		"npc": "Giant mole"
	},
	{
		"title": "Clue scroll (hard)",
		"quantity": 1,
		"price": null,
		"rarity": "Rare",
		"droprate": null,
		"type": "Other",
		"img": "/img/rs3/clue_scroll_(hard).png",
		"game": "rs3",
		"boss": "Giant mole",
		"npc": "Giant mole"
	},
	{
		"title": "Clue scroll (elite)",
		"quantity": 1,
		"price": null,
		"rarity": "Rare",
		"droprate": null,
		"type": "Other",
		"img": "/img/rs3/clue_scroll_(elite).png",
		"game": "rs3",
		"boss": "Giant mole",
		"npc": "Giant mole"
	},
	{
		"title": "Long bone",
		"quantity": 1,
		"price": null,
		"rarity": "Rare",
		"droprate": null,
		"type": "Other",
		"img": "/img/rs3/long_bone.png",
		"game": "rs3",
		"boss": "Giant mole",
		"npc": "Giant mole"
	},
	{
		"title": "Curved bone",
		"quantity": 1,
		"price": null,
		"rarity": "Rare",
		"droprate": null,
		"type": "Other",
		"img": "/img/rs3/curved_bone.png",
		"game": "rs3",
		"boss": "Giant mole",
		"npc": "Giant mole"
	},
	{
		"title": "Starved ancient effigy",
		"quantity": 1,
		"price": null,
		"rarity": "Rare",
		"droprate": null,
		"type": "Other",
		"img": "/img/rs3/starved_ancient_effigy.png",
		"game": "rs3",
		"boss": "Giant mole",
		"npc": "Giant mole"
	},
	{
		"title": "Rotten fang",
		"quantity": 1,
		"price": null,
		"rarity": "Very rare",
		"droprate": null,
		"type": "Other",
		"img": "/img/rs3/rotten_fang.png",
		"game": "rs3",
		"boss": "Giant mole",
		"npc": "Giant mole"
	}
];