/*
* RS3 Kalphite King drops list made by Richard (Hellworms).
*/

KalphiteKingDrops = [
	{
		"title": "Drygore rapier",
		"quantity": 1,
		"price": 26368933,
		"rarity": "Rare",
		"droprate": null,
		"type": "Weapons",
		"img": "/img/rs3/drygore_rapier.png",
		"game": "rs3",
		"boss": "Kalphite King",
		"npc": "Kalphite King"
	},
	{
		"title": "Drygore longsword",
		"quantity": 1,
		"price": 30523731,
		"rarity": "Rare",
		"droprate": null,
		"type": "Weapons",
		"img": "/img/rs3/drygore_longsword.png",
		"game": "rs3",
		"boss": "Kalphite King",
		"npc": "Kalphite King"
	},
	{
		"title": "Drygore mace",
		"quantity": 1,
		"price": 25385297,
		"rarity": "Rare",
		"droprate": null,
		"type": "Weapons",
		"img": "/img/rs3/drygore_mace.png",
		"game": "rs3",
		"boss": "Kalphite King",
		"npc": "Kalphite King"
	},
	{
		"title": "Off-hand drygore longsword",
		"quantity": 1,
		"price": 24467732,
		"rarity": "Rare",
		"droprate": null,
		"type": "Weapons",
		"img": "/img/rs3/off-hand_drygore_longsword.png",
		"game": "rs3",
		"boss": "Kalphite King",
		"npc": "Kalphite King"
	},
	{
		"title": "Off-hand drygore rapier",
		"quantity": 1,
		"price": 24539887,
		"rarity": "Rare",
		"droprate": null,
		"type": "Weapons",
		"img": "/img/rs3/off-hand_drygore_rapier.png",
		"game": "rs3",
		"boss": "Kalphite King",
		"npc": "Kalphite King"
	},
	{
		"title": "Off-hand drygore mace",
		"quantity": 1,
		"price": 15109319,
		"rarity": "Rare",
		"droprate": null,
		"type": "Weapons",
		"img": "/img/rs3/off-hand_drygore_mace.png",
		"game": "rs3",
		"boss": "Kalphite King",
		"npc": "Kalphite King"
	},
	{
		"title": "Grimy torstol",
		"quantity": 30,
		"price": 5354,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "Herbs and seed",
		"img": "/img/rs3/grimy_torstol.png",
		"game": "rs3",
		"boss": "Kalphite King",
		"npc": "Kalphite King"
	},
	{
		"title": "Grimy dwarf weed",
		"quantity": 30,
		"price": 6334,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "Herbs and seed",
		"img": "/img/rs3/grimy_dwarf_weed.png",
		"game": "rs3",
		"boss": "Kalphite King",
		"npc": "Kalphite King"
	},
	{
		"title": "Grimy lantadyme",
		"quantity": 30,
		"price": 5898,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "Herbs and seed",
		"img": "/img/rs3/grimy_lantadyme.png",
		"game": "rs3",
		"boss": "Kalphite King",
		"npc": "Kalphite King"
	},
	{
		"title": "Grimy snapdragon",
		"quantity": 30,
		"price": 3664,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "Herbs and seed",
		"img": "/img/rs3/grimy_snapdragon.png",
		"game": "rs3",
		"boss": "Kalphite King",
		"npc": "Kalphite King"
	},
	{
		"title": "Grimy kwuarm",
		"quantity": 30,
		"price": 4903,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "Herbs and seed",
		"img": "/img/rs3/grimy_kwuarm.png",
		"game": "rs3",
		"boss": "Kalphite King",
		"npc": "Kalphite King"
	},
	{
		"title": "Torstol seed",
		"quantity": 10,
		"price": 8505,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "Herbs and seed",
		"img": "/img/rs3/torstol_seed.png",
		"game": "rs3",
		"boss": "Kalphite King",
		"npc": "Kalphite King"
	},
	{
		"title": "Lantadyme seed",
		"quantity": 10,
		"price": 9786,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "Herbs and seed",
		"img": "/img/rs3/lantadyme_seed.png",
		"game": "rs3",
		"boss": "Kalphite King",
		"npc": "Kalphite King"
	},
	{
		"title": "Dwarf weed seed",
		"quantity": 10,
		"price": 15624,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "Herbs and seed",
		"img": "/img/rs3/dwarf_weed_seed.png",
		"game": "rs3",
		"boss": "Kalphite King",
		"npc": "Kalphite King"
	},
	{
		"title": "Snapdragon seed",
		"quantity": 10,
		"price": 514,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "Herbs and seed",
		"img": "/img/rs3/snapdragon_seed.png",
		"game": "rs3",
		"boss": "Kalphite King",
		"npc": "Kalphite King"
	},
	{
		"title": "Magic seed",
		"quantity": 5,
		"price": 148382,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "Herbs and seed",
		"img": "/img/rs3/magic_seed.png",
		"game": "rs3",
		"boss": "Kalphite King",
		"npc": "Kalphite King"
	},
	{
		"title": "Palm tree seed",
		"quantity": 5,
		"price": 174416,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "Herbs and seed",
		"img": "/img/rs3/palm_tree_seed.png",
		"game": "rs3",
		"boss": "Kalphite King",
		"npc": "Kalphite King"
	},
	{
		"title": "Yew seed",
		"quantity": 10,
		"price": 63943,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "Herbs and seed",
		"img": "/img/rs3/yew_seed.png",
		"game": "rs3",
		"boss": "Kalphite King",
		"npc": "Kalphite King"
	},
	{
		"title": "Shark",
		"quantity": 50,
		"price": 705,
		"rarity": "Common",
		"droprate": null,
		"type": "Other",
		"img": "/img/rs3/shark.png",
		"game": "rs3",
		"boss": "Kalphite King",
		"npc": "Kalphite King"
	},
	{
		"title": "Rune bar",
		"quantity": 40,
		"price": 14460,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "Other",
		"img": "/img/rs3/rune_bar.png",
		"game": "rs3",
		"boss": "Kalphite King",
		"npc": "Kalphite King"
	},
	{
		"title": "Onyx bolts (e)",
		"quantity": 200,
		"price": 8572,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "Other",
		"img": "/img/rs3/onyx_bolts_e.png",
		"game": "rs3",
		"boss": "Kalphite King",
		"npc": "Kalphite King"
	},
	{
		"title": "Black dragonhide",
		"quantity": 100,
		"price": 3590,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "Other",
		"img": "/img/rs3/black_dragonhide.png",
		"game": "rs3",
		"boss": "Kalphite King",
		"npc": "Kalphite King"
	},
	{
		"title": "Super restore (4)",
		"quantity": 40,
		"price": 3476,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "Other",
		"img": "/img/rs3/super_restore_4.png",
		"game": "rs3",
		"boss": "Kalphite King",
		"npc": "Kalphite King"
	},
	{
		"title": "Earth talisman",
		"quantity": 50,
		"price": 3154,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "Other",
		"img": "/img/rs3/earth_talisman.png",
		"game": "rs3",
		"boss": "Kalphite King",
		"npc": "Kalphite King"
	},
	{
		"title": "Clue scroll (elite)",
		"quantity": 1,
		"price": null,
		"rarity": "Rare",
		"droprate": null,
		"type": "Other",
		"img": "/img/rs3/clue_scroll_elite.png",
		"game": "rs3",
		"boss": "Kalphite King",
		"npc": "Kalphite King"
	},
	{
		"title": "Starved ancient effigy",
		"quantity": 1,
		"price": null,
		"rarity": "Very rare",
		"droprate": null,
		"type": "Other",
		"img": "/img/rs3/starved_ancient_effigy.png",
		"game": "rs3",
		"boss": "Kalphite King",
		"npc": "Kalphite King"
	},
	{
		"title": "Kalphite claw",
		"quantity": 1,
		"price": null,
		"rarity": "Very rare",
		"droprate": 2000,
		"type": "Other",
		"img": "/img/rs3/kalphite_claw.png",
		"game": "rs3",
		"boss": "Kalphite King",
		"npc": "Kalphite King"
	}
]
	