/*
* OSRS King Black Dragon drops list made by Mokuin.
*/

KbdDropsOsrs = [
	{
		"title": "Rune longsword",
		"quantity": 1,
		"price": 19726,
		"rarity": "Common",
		"droprate": null,
		"type": "weapons",
		"img": "/img/osrs/rune_longsword.png",
		"game": "osrs",
		"boss": "King Black Dragon",
		"npc": "King Black Dragon"
	},
	{
		"title": "Adamant platebody",
		"quantity": 1,
		"price": 9734,
		"rarity": "Common",
		"droprate": null,
		"type": "armour",
		"img": "/img/osrs/adamant_platebody.png",
		"game": "osrs",
		"boss": "King Black Dragon",
		"npc": "King Black Dragon"
	},
	{
		"title": "Adamant kiteshield",
		"quantity": 1,
		"price": 3699,
		"rarity": "Common",
		"droprate": null,
		"type": "armour",
		"img": "/img/osrs/adamant_kiteshield.png",
		"game": "osrs",
		"boss": "King Black Dragon",
		"npc": "King Black Dragon"
	},
	{
		"title": "Dragon med helm",
		"quantity": 1,
		"price": 63735,
		"rarity": "Rare",
		"droprate": null,
		"type": "armour",
		"img": "/img/osrs/dragon_med_helm.png",
		"game": "osrs",
		"boss": "King Black Dragon",
		"npc": "King Black Dragon"
	},
	{
		"title": "Dragon pickaxe",
		"quantity": 1,
		"price": 1849313,
		"rarity": "Very rare",
		"droprate": 1500,
		"type": "weapons",
		"img": "/img/osrs/dragon_pickaxe.png",
		"game": "osrs",
		"boss": "King Black Dragon",
		"npc": "King Black Dragon",
	},
	{
		"title": "Fire rune",
		"quantity": 300,
		"price":5,
		"rarity": "Common",
		"droprate": null,
		"type": "runes",
		"img": "/img/osrs/fire_rune.png",
		"game": "osrs",
		"boss": "King Black Dragon",
		"npc": "King Black Dragon"
	},
	{
		"title": "Air rune",
		"quantity": 300,
		"price":5,
		"rarity": "Common",
		"droprate": null,
		"type": "runes",
		"img": "/img/osrs/air_rune.png",
		"game": "osrs",
		"boss": "King Black Dragon",
		"npc": "King Black Dragon"
	},
	{
		"title": "Blood rune",
		"quantity": 30,
		"price":307,
		"rarity": "Common",
		"droprate": null,
		"type": "runes",
		"img": "/img/osrs/blood_rune.png",
		"game": "osrs",
		"boss": "King Black Dragon",
		"npc": "King Black Dragon"
	},
	{
		"title": "Iron arrow",
		"quantity": 690,
		"price":12,
		"rarity": "Common",
		"droprate": null,
		"type": "weapons",
		"img": "/img/osrs/iron_arrow.png",
		"game": "osrs",
		"boss": "King Black Dragon",
		"npc": "King Black Dragon"
	},
	{
		"title": "Law rune",
		"quantity": 30,
		"price":222,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "runes",
		"img": "/img/osrs/law_rune.png",
		"game": "osrs",
		"boss": "King Black Dragon",
		"npc": "King Black Dragon"
	},
	{
		"title": "Runite bolts",
		"quantity": 18,
		"price": 197,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "weapons",
		"img": "/img/osrs/runite_bolts.png",
		"game": "osrs",
		"boss": "King Black Dragon",
		"npc": "King Black Dragon"
	},
	
	{
		"title": "Dragon dart tip",
		"quantity": 9,
		"price": 2849,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "weapons",
		"img": "/img/osrs/dragon_dart_tip.png",
		"game": "osrs",
		"boss": "King Black Dragon",
		"npc": "King Black Dragon"
	},
	{
		"title": "Dragon arrowtips",
		"quantity": 9,
		"price": 1233,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "weapons",
		"img": "/img/osrs/dragon_arrowtips.png",
		"game": "osrs",
		"boss": "King Black Dragon",
		"npc": "King Black Dragon"
	},
	{
		"title": "Amulet of power",
		"quantity": 1,
		"price": 2646,
		"rarity": "Common",
		"droprate": null,
		"type": "other",
		"img": "/img/osrs/amulet_of_power.png",
		"game": "osrs",
		"boss": "King Black Dragon",
		"npc": "King Black Dragon"
	},
	{
		"title": "Yew logs",
		"quantity": 150,
		"price": 463,
		"rarity": "Common",
		"droprate": null,
		"type": "other",
		"img": "/img/osrs/yew_logs.png",
		"game": "osrs",
		"boss": "King Black Dragon",
		"npc": "King Black Dragon"
	},
	{
		"title": "Shark",
		"quantity": 4,
		"price": 906,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "other",
		"img": "/img/osrs/shark.png",
		"game": "osrs",
		"boss": "King Black Dragon",
		"npc": "King Black Dragon"
	},
	{
		"title": "Gold ore",
		"quantity": 100,
		"price": 265,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "other",
		"img": "/img/osrs/gold_ore.png",
		"game": "osrs",
		"boss": "King Black Dragon",
		"npc": "King Black Dragon"
	},
	{
		"title": "Runite limbs",
		"quantity": 1,
		"price": 9449,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "other",
		"img": "/img/osrs/runite_limbs.png",
		"game": "osrs",
		"boss": "King Black Dragon",
		"npc": "King Black Dragon"
	},
	{
		"title": "Adamantite bar",
		"quantity": 3,
		"price": 2286,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "other",
		"img": "/img/osrs/adamantite_bar.png",
		"game": "osrs",
		"boss": "King Black Dragon",
		"npc": "King Black Dragon"
	},
		{
		"title": "Clue scroll (elite)",
		"quantity": 1,
		"price": null,
		"rarity": "Rare",
		"droprate": null,
		"type": "other",
		"img": "/img/osrs/clue_scroll_elite.png",
		"game": "osrs",
		"boss": "King Black Dragon",
		"npc": "King Black Dragon"
	},
		{
		"title": "Kbd head",
		"quantity": 1,
		"price": null,
		"rarity": "Rare",
		"droprate": null,
		"type": "other",
		"img": "/img/osrs/kbd_head.png",
		"game": "osrs",
		"boss": "King Black Dragon",
		"npc": "King Black Dragon"
	},
		{
		"title": "Prince black dragon",
		"quantity": 1,
		"price": null,
		"rarity": "Very rare",
		"droprate": null,
		"type": "other",
		"img": "/img/osrs/prince_black_dragon.png",
		"game": "osrs",
		"boss": "King Black Dragon",
		"npc": "King Black Dragon"
	},
		{
		"title": "Draconic visage",
		"quantity": 1,
		"price": 17228095,
		"rarity": "Very rare",
		"droprate": null,
		"type": "other",
		"img": "/img/osrs/draconic_visage.png",
		"game": "osrs",
		"boss": "King Black Dragon",
		"npc": "King Black Dragon"
	}
];

