/*
* RS3 King Black Dragon drops list made by Mokuin.
*/

KbdDropsRs3 = [
	{
		"title": "Rune longsword",
		"quantity": 1,
		"price": 18375,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "weapons",
		"img": "/img/rs3/rune_longsword.png",
		"game": "rs3",
		"boss": "King Black Dragon",
		"npc": "King Black Dragon"
	},
	{
		"title": "Rune battleaxe",
		"quantity": 1,
		"price": 24356,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "weapons",
		"img": "/img/rs3/rune_battleaxe.png",
		"game": "rs3",
		"boss": "King Black Dragon",
		"npc": "King Black Dragon"
	},
	{
		"title": "Rune 2h sword",
		"quantity": 1,
		"price": 37354,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "weapons",
		"img": "/img/rs3/rune_2h_sword.png",
		"game": "rs3",
		"boss": "King Black Dragon",
		"npc": "King Black Dragon"
	},
	{
		"title": "Blood rune",
		"quantity": 40,
		"price": 456,
		"rarity": "Common",
		"droprate": null,
		"type": "runes",
		"img": "/img/rs3/blood_rune.png",
		"game": "rs3",
		"boss": "King Black Dragon",
		"npc": "King Black Dragon"
	},
	{
		"title": "Death rune",
		"quantity": 50,
		"price": 351,
		"rarity": "Common",
		"droprate": null,
		"type": "runes",
		"img": "/img/rs3/death_rune.png",
		"game": "rs3",
		"boss": "King Black Dragon",
		"npc": "King Black Dragon"
	},
	{
		"title": "Law rune",
		"quantity": 50,
		"price": 232,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "runes",
		"img": "/img/rs3/law_rune.png",
		"game": "rs3",
		"boss": "King Black Dragon",
		"npc": "King Black Dragon"
	},
	{
		"title": "Mithril arrow",
		"quantity": 250,
		"price": 24,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "weapons",
		"img": "/img/rs3/mithril_arrow.png",
		"game": "rs3",
		"boss": "King Black Dragon",
		"npc": "King Black Dragon"
	},
	{
		"title": "Rune arrow",
		"quantity": 50,
		"price": 152,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "weapons",
		"img": "/img/rs3/rune_arrow.png",
		"game": "rs3",
		"boss": "King Black Dragon",
		"npc": "King Black Dragon"
	},
	{
		"title": "Runite bolts",
		"quantity": 25,
		"price": 306,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "weapons",
		"img": "/img/rs3/runite_bolts.png",
		"game": "rs3",
		"boss": "King Black Dragon",
		"npc": "King Black Dragon"
	},
	{
		"title": "Rune sq shield",
		"quantity": 1,
		"price": 21982,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "armour",
		"img": "/img/rs3/rune_sq_shield.png",
		"game": "rs3",
		"boss": "King Black Dragon",
		"npc": "King Black Dragon"
	},
	{
		"title": "Rune platebody",
		"quantity": 1,
		"price": 38010,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "armour",
		"img": "/img/rs3/rune_platebody.png",
		"game": "rs3",
		"boss": "King Black Dragon",
		"npc": "King Black Dragon"
	},
	{
		"title": "Dragon helm",
		"quantity": 1,
		"price": 58973,
		"rarity": "Rare",
		"droprate": null,
		"type": "armour",
		"img": "/img/rs3/dragon_helm.png",
		"game": "rs3",
		"boss": "King Black Dragon",
		"npc": "King Black Dragon"
	},
	{
		"title": "Dragon rider boots",
		"quantity": 1,
		"price": 2846607,
		"rarity": "Very rare",
		"droprate": null,
		"type": "armour",
		"img": "/img/rs3/dragon_rider_boots.png",
		"game": "rs3",
		"boss": "King Black Dragon",
		"npc": "King Black Dragon"
	},
	{
		"title": "Dragon rider gloves",
		"quantity": 1,
		"price": 2880161,
		"rarity": "Very rare",
		"droprate": null,
		"type": "armour",
		"img": "/img/rs3/dragon_rider_gloves.png",
		"game": "rs3",
		"boss": "King Black Dragon",
		"npc": "King Black Dragon"
	},
	{
		"title": "Adamant bar",
		"quantity": 3,
		"price": 3150,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "material",
		"img": "/img/rs3/adamant_bar.png",
		"game": "rs3",
		"boss": "King Black Dragon",
		"npc": "King Black Dragon"
	},
	{
		"title": "Rune bar",
		"quantity": 2,
		"price": 14460,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "material",
		"img": "/img/rs3/rune_bar.png",
		"game": "rs3",
		"boss": "King Black Dragon",
		"npc": "King Black Dragon"
	},
	{
		"title": "Silver ore",
		"quantity": 100,
		"price": 77,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "material",
		"img": "/img/rs3/silver_ore.png",
		"game": "rs3",
		"boss": "King Black Dragon",
		"npc": "King Black Dragon"
	},
	{
		"title": "Gold ore",
		"quantity": 50,
		"price": 179,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "material",
		"img": "/img/rs3/gold_ore.png",
		"game": "rs3",
		"boss": "King Black Dragon",
		"npc": "King Black Dragon"
	},
	{
		"title": "Runite ore",
		"quantity": 3,
		"price": 11053,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "material",
		"img": "/img/rs3/runite_ore.png",
		"game": "rs3",
		"boss": "King Black Dragon",
		"npc": "King Black Dragon"
	},
	{
		"title": "Coins",
		"quantity": 2000,
		"price": 1,
		"rarity": "Common",
		"droprate": null,
		"type": "other",
		"img": "/img/rs3/coins.png",
		"game": "rs3",
		"boss": "King Black Dragon",
		"npc": "King Black Dragon"
	},
	{
		"title": "Yew logs",
		"quantity": 50,
		"price": 268,
		"rarity": "Common",
		"droprate": null,
		"type": "other",
		"img": "/img/rs3/yew_logs.png",
		"game": "rs3",
		"boss": "King Black Dragon",
		"npc": "King Black Dragon"
	},
	{
		"title": "Magic logs",
		"quantity": 10,
		"price": 908,
		"rarity": "common",
		"droprate": null,
		"type": "other",
		"img": "/img/rs3/magic_logs.png",
		"game": "rs3",
		"boss": "King Black Dragon",
		"npc": "King Black Dragon"
	},
	{
		"title": "Draconic visage",
		"quantity": 1,
		"price": 1290985,
		"rarity": "Very rare",
		"droprate": 4754,
		"type": "other",
		"img": "/img/rs3/draconic_visage.png",
		"game": "rs3",
		"boss": "King Black Dragon",
		"npc": "King Black Dragon"
	},
	{
		"title": "Dragon kite ornament kit (or)",
		"quantity": 1,
		"price": 15105,
		"rarity": "Very rare",
		"droprate": null,
		"type": "other",
		"img": "/img/rs3/dragon_kite_ornament_kit_or.png",
		"game": "rs3",
		"boss": "King Black Dragon",
		"npc": "King Black Dragon"
	},
	{
		"title": "Dragon kite ornament kit (sp)",
		"quantity": 1,
		"price": 6022,
		"rarity": "Very rare",
		"droprate": null,
		"type": "other",
		"img": "/img/rs3/dragon_kite_ornament_kit_sp.png",
		"game": "rs3",
		"boss": "King Black Dragon",
		"npc": "King Black Dragon"
	},
	{
		"title": "Clue scroll (hard)",
		"quantity": 1,
		"price": null,
		"rarity": "Rare",
		"droprate": null,
		"type": "Other",
		"img": "/img/rs3/clue_scroll_hard.png",
		"game": "rs3",
		"boss": "King Black Dragon",
		"npc": "King Black Dragon"
	},
	{
		"title": "Clue scroll (elite)",
		"quantity": 1,
		"price": null,
		"rarity": "Very rare",
		"droprate": null,
		"type": "Other",
		"img": "/img/rs3/clue_scroll_elite.png",
		"game": "rs3",
		"boss": "King Black Dragon",
		"npc": "King Black Dragon"
	},
	{
		"title": "Starved ancient effigy",
		"quantity": 1,
		"price": null,
		"rarity": "Rare",
		"droprate": null,
		"type": "Other",
		"img": "/img/rs3/starved_ancient_effigy.png",
		"game": "rs3",
		"boss": "King Black Dragon",
		"npc": "King Black Dragon"
	},
	{
		"title": "King black dragon scale",
		"quantity": 1,
		"price": null,
		"rarity": "Very rare",
		"droprate": 2500,
		"type": "Other",
		"img": "/img/rs3/king_black_dragon_scale.png",
		"game": "rs3",
		"boss": "King Black Dragon",
		"npc": "King Black Dragon"
	},
	{
		"title": "Kbd head",
		"quantity": 1,
		"price": null,
		"rarity": "Rare",
		"droprate": null,
		"type": "Other",
		"img": "/img/rs3/kbd_head.png",
		"game": "rs3",
		"boss": "King Black Dragon",
		"npc": "King Black Dragon"
	}
];

