/*
* OSRS Kraken drops list made by Richard (Hellworms).
*/

KrakenDrops = [
	{
		"title": "Battlestaff",
		"quantity": 10,
		"price": 8235,
		"rarity": "common",
		"droprate": null,
		"type": "Weapons/armour",
		"img": "/img/osrs/battlestaff.png",
		"game": "osrs",
		"boss": "Kraken",
		"npc": "Kraken"
	},
	{
		"title": "Mystic water staff",
		"quantity": 1,
		"price": 25610,
		"rarity": "common",
		"droprate": null,
		"type": "wapons/armour",
		"img": "/img/osrs/mystic_water_staff.png",
		"game": "osrs",
		"boss": "Kraken",
		"npc": "Kraken"
	},
	{
		"title": "Rune warhammer",
		"quantity": 1,
		"price": 26565,
		"rarity": "Common",
		"droprate": null,
		"type": "weapons/armour",
		"img": "/img/osrs/rune_warhammer.png",
		"game": "osrs",
		"boss": "Kraken",
		"npc": "Kraken"
	},
	{
		"title": "Pirate boots",
		"quantity": 1,
		"price": 3495,
		"rarity": "Common",
		"droprate": null,
		"type": "weapons/armour",
		"img": "/img/osrs/pirate_boots.png",
		"game": "osrs",
		"boss": "Kraken",
		"npc": "Kraken"
	},
	{
		"title": "Rune longsword",
		"quantity": 1,
		"price": 19726,
		"rarity": "uncommon",
		"droprate": null,
		"type": "weapons/armour",
		"img": "/img/osrs/rune_longsword.png",
		"game": "osrs",
		"boss": "Kraken",
		"npc": "Kraken"
	},
	{
		"title": "Mystic robe top (blue)",
		"quantity": 1,
		"price": 81419,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "weapons/armour",
		"img": "/img/osrs/mystic_robe_top_blue.png",
		"game": "osrs",
		"boss": "Kraken",
		"npc": "Kraken"
	},
	{
		"title": "Mystic robe bottom (blue)",
		"quantity": 1,
		"price": 54897,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "weapons/armour",
		"img": "/img/osrs/mystic_robe_bottom_blue.png",
		"game": "osrs",
		"boss": "Kraken",
		"npc": "Kraken"
	},
	{
		"title": "Dragonstone ring",
		"quantity": 1,
		"price": 16109,
		"rarity": "rare",
		"droprate": null,
		"type": "weapons/armour",
		"img": "/img/osrs/dragonstone_ring.png",
		"game": "osrs",
		"boss": "Kraken",
		"npc": "Kraken"
	},
	{
		"title": "Trident of the seas",
		"quantity": 1,
		"price": 1793294,
		"rarity": "Rare",
		"droprate": 512,
		"type": "weapons/armour",
		"img": "/img/osrs/trident_of_the_seas.png",
		"game": "osrs",
		"boss": "Kraken",
		"npc": "Kraken"
	},
	{
		"title": "water rune",
		"quantity": 400,
		"price": 5,
		"rarity": "common",
		"droprate": null,
		"type": "runes",
		"img": "/img/osrs/water_rune.png",
		"game": "osrs",
		"boss": "Kraken",
		"npc": "Kraken"
	},
	{
		"title": "Mist rune",
		"quantity": 100,
		"price": 332,
		"rarity": "common",
		"droprate": null,
		"type": "runes",
		"img": "/img/osrs/mist_rune.png",
		"game": "osrs",
		"boss": "Kraken",
		"npc": "Kraken"
	},
	{
		"title": "Chaos rune",
		"quantity": 250,
		"price": 101,
		"rarity": "common",
		"droprate": null,
		"type": "runes",
		"img": "/img/osrs/chaos_rune.png",
		"game": "osrs",
		"boss": "Kraken",
		"npc": "Kraken"
	},
	{
		"title": "Death rune",
		"quantity": 150,
		"price": 219,
		"rarity": "uncommon",
		"droprate": null,
		"type": "runes",
		"img": "/img/osrs/death_rune.png",
		"game": "osrs",
		"boss": "Kraken",
		"npc": "Kraken"
	},
	{
		"title": "Blood rune",
		"quantity": 60,
		"price": 307,
		"rarity": "uncommon",
		"droprate": null,
		"type": "runes",
		"img": "/img/osrs/blood_rune.png",
		"game": "osrs",
		"boss": "Kraken",
		"npc": "Kraken"
	},
	{
		"title": "Soul rune",
		"quantity": 50,
		"price": 176,
		"rarity": "uncommon",
		"droprate": null,
		"type": "runes",
		"img": "/img/osrs/soul_rune.png",
		"game": "osrs",
		"boss": "Kraken",
		"npc": "Kraken"
	},
	{
		"title": "Watermelon seed",
		"quantity": 24,
		"price": 1363,
		"rarity": "common",
		"droprate": null,
		"type": "seeds",
		"img": "/img/osrs/watermelon_seed.png",
		"game": "osrs",
		"boss": "Kraken",
		"npc": "Kraken"
	},
	{
		"title": "Torstol seed",
		"quantity": 2,
		"price": 25957,
		"rarity": "uncommon",
		"droprate": null,
		"type": "seeds",
		"img": "/img/osrs/torstol_seed.png",
		"game": "osrs",
		"boss": "Kraken",
		"npc": "Kraken"
	},
	{
		"title": "Magic seed",
		"quantity": 1,
		"price": 85112,
		"rarity": "rare",
		"droprate": 128,
		"type": "seeds",
		"img": "/img/osrs/magic_seed.png",
		"game": "osrs",
		"boss": "Kraken",
		"npc": "Kraken"
	},
	{
		"title": "coins",
		"quantity": 15000,
		"price": 1,
		"rarity": "common",
		"droprate": null,
		"type": "other",
		"img": "/img/osrs/coins.png",
		"game": "osrs",
		"boss": "Kraken",
		"npc": "Kraken"
	},
	{
		"title": "Shark",
		"quantity": 5,
		"price": 906,
		"rarity": "common",
		"droprate": null,
		"type": "other",
		"img": "/img/osrs/shark.png",
		"game": "osrs",
		"boss": "Kraken",
		"npc": "Kraken"
	},
	{
		"title": "Edible seaweed)",
		"quantity": 5,
		"price": 59,
		"rarity": "common",
		"droprate": null,
		"type": "other",
		"img": "/img/osrs/edible_seaweed.png",
		"game": "osrs",
		"boss": "Kraken",
		"npc": "Kraken"
	},
	{
		"title": "Seaweed",
		"quantity": 125,
		"price": 44,
		"rarity": "common",
		"droprate": null,
		"type": "other",
		"img": "/img/osrs/seaweed.png",
		"game": "osrs",
		"boss": "Kraken",
		"npc": "Kraken"
	},
	{
		"title": "Harpoon",
		"quantity": 1,
		"price": 121,
		"rarity": "uncommon",
		"droprate": null,
		"type": "Other",
		"img": "/img/osrs/harpoon.png",
		"game": "osrs",
		"boss": "Kraken",
		"npc": "Kraken"
	},
	{
		"title": "Bucket",
		"quantity": 1,
		"price": 38,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "Other",
		"img": "/img/osrs/bucket.png",
		"game": "osrs",
		"boss": "Kraken",
		"npc": "Kraken"
	},
	{
		"title": "Sanfew serum (4)",
		"quantity": 2,
		"price": 12122,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "Other",
		"img": "/img/osrs/sanfew_serum_4.png",
		"game": "osrs",
		"boss": "Kraken",
		"npc": "Kraken"
	},
	{
		"title": "Raw monkfish",
		"quantity": 100,
		"price": 498,
		"rarity": "uncommon",
		"droprate": null,
		"type": "Other",
		"img": "/img/osrs/raw_monkfish.png",
		"game": "osrs",
		"boss": "Kraken",
		"npc": "Kraken"
	},
	{
		"title": "Raw shark",
		"quantity": 50,
		"price": 794,
		"rarity": "uncommon",
		"droprate": null,
		"type": "Other",
		"img": "/img/osrs/raw_shark.png",
		"game": "osrs",
		"boss": "Kraken",
		"npc": "Kraken"
	},
	{
		"title": "Unpowered orb",
		"quantity":50,
		"price": 20,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "Other",
		"img": "/img/osrs/unpowered_orb.png",
		"game": "osrs",
		"boss": "Kraken",
		"npc": "Kraken"
	},
	{
		"title": "Crystal key",
		"quantity": 1,
		"price": 24045,
		"rarity": "uncommon",
		"droprate": null,
		"type": "Other",
		"img": "/img/osrs/crystal_key.png",
		"game": "osrs",
		"boss": "Kraken",
		"npc": "Kraken"
	},
	{
		"title": "Oak plank",
		"quantity": 60,
		"price": 438,
		"rarity": "uncommon",
		"droprate": null,
		"type": "Other",
		"img": "/img/osrs/oak_plank.png",
		"game": "osrs",
		"boss": "Kraken",
		"npc": "Kraken"
	},
	{
		"title": "Runite bar",
		"quantity": 2,
		"price": 14002,
		"rarity": "uncommon",
		"droprate": null,
		"type": "Other",
		"img": "/img/osrs/runite_bar.png",
		"game": "osrs",
		"boss": "Kraken",
		"npc": "Kraken"
	},
	{
		"title": "Grimy snapdragon",
		"quantity": 6,
		"price": 5917,
		"rarity": "uncommon",
		"droprate": 539,
		"type": "Other",
		"img": "/img/osrs/grimy_snapdragon.png",
		"game": "osrs",
		"boss": "Kraken",
		"npc": "Kraken"
	},
	{
		"title": "Diamond",
		"quantity": 8,
		"price": 2182,
		"rarity": "úncommon",
		"droprate": null,
		"type": "Other",
		"img": "/img/osrs/diamond.png",
		"game": "osrs",
		"boss": "Kraken",
		"npc": "Kraken"
	},
	{
		"title": "Rusty sword",
		"quantity": 1,
		"price": null,
		"rarity": "uncommon",
		"droprate": null,
		"type": "Other",
		"img": "/img/osrs/rusty_sword.png",
		"game": "osrs",
		"boss": "Kraken",
		"npc": "Kraken"
	},
	{
		"title": "Antidote++ (4)",
		"quantity": 2,
		"price": 927,
		"rarity": "uncommon",
		"droprate": null,
		"type": "Other",
		"img": "/img/osrs/antidote_pp_4.png",
		"game": "osrs",
		"boss": "Kraken",
		"npc": "Kraken"
	},
	{
		"title": "Kraken tentacle",
		"quantity": 1,
		"price": 686321,
		"rarity": "Rare",
		"droprate": 400,
		"type": "Other",
		"img": "/img/osrs/kraken_tentacle.png",
		"game": "osrs",
		"boss": "Kraken",
		"npc": "Kraken"
	},
	{
		"title": "Clue scroll (elite)",
		"quantity": 1,
		"price": null,
		"rarity": "rare",
		"droprate": 500,
		"type": "Other",
		"img": "/img/osrs/clue_scroll.png",
		"game": "osrs",
		"boss": "Kraken",
		"npc": "Kraken"
	},
	{
		"title": "Jar of dirt",
		"quantity": 1,
		"price": 444113,
		"rarity": "Rare",
		"droprate": 1000,
		"type": "Other",
		"img": "/img/osrs/jar_of_dirt.png",
		"game": "osrs",
		"boss": "Kraken",
		"npc": "Kraken"
	},
	{
		"title": "Pet kraken",
		"quantity": 1,
		"price": null,
		"rarity": "very rare",
		"droprate": 3000,
		"type": "Other",
		"img": "/img/osrs/pet_kraken.png",
		"game": "osrs",
		"boss": "Kraken",
		"npc": "Kraken"
	}
];