/*
* Nex drops list made by Mokuin.
*/

NexDrops = [
	{
		"title": "Torva full helm",
		"quantity": 1,
		"price": 8089512,
		"rarity": "Rare",
		"droprate": 277,
		"type": "Armour",
		"img": "/img/rs3/torva_full_helm.png",
		"game": "rs3",
		"boss": "Nex",
		"npc": "Nex"
	},
	{
		"title": "Torva platebody",
		"quantity": 1,
		"price": 20491614,
		"rarity": "Rare",
		"droprate": 277,
		"type": "Armour",
		"img": "/img/rs3/torva_platebody.png",
		"game": "rs3",
		"boss": "Nex",
		"npc": "Nex"
	},
	{
		"title": "Torva boots",
		"quantity": 1,
		"price": 17672465,
		"rarity": "Rare",
		"droprate": null,
		"type": "Armour",
		"img": "/img/rs3/torva_boots.png",
		"game": "rs3",
		"boss": "Nex",
		"npc": "Nex"
	},
	{
		"title": "Torva gloves",
		"quantity": 1,
		"price": 7509197,
		"rarity": "Rare",
		"droprate": null,
		"type": "Armour",
		"img": "/img/rs3/torva_gloves.png",
		"game": "rs3",
		"boss": "Nex",
		"npc": "Nex"
	},
	{
		"title": "Pernix cowl",
		"quantity": 1,
		"price": 4315199,
		"rarity": "Rare",
		"droprate": 277,
		"type": "Armour",
		"img": "/img/rs3/pernix_cowl.png",
		"game": "rs3",
		"boss": "Nex",
		"npc": "Nex"
	},
	{
		"title": "Pernix body",
		"quantity": 1,
		"price": 13891203,
		"rarity": "Rare",
		"droprate": 277,
		"type": "Armour",
		"img": "/img/rs3/pernix_body.png",
		"game": "rs3",
		"boss": "Nex",
		"npc": "Nex"
	},
	{
		"title": "Pernix chaps",
		"quantity": 1,
		"price": 15803064,
		"rarity": "Rare",
		"droprate": 277,
		"type": "Armour",
		"img": "/img/rs3/pernix_chaps.png",
		"game": "rs3",
		"boss": "Nex",
		"npc": "Nex"
	},
	{
		"title": "Pernix boots",
		"quantity": 1,
		"price": 15010062,
		"rarity": "Rare",
		"droprate": null,
		"type": "Armour",
		"img": "/img/rs3/pernix_boots.png",
		"game": "rs3",
		"boss": "Nex",
		"npc": "Nex"
	},
	{
		"title": "Pernix gloves",
		"quantity": 1,
		"price": 6263268,
		"rarity": "Rare",
		"droprate": null,
		"type": "Armour",
		"img": "/img/rs3/pernix_gloves.png",
		"game": "rs3",
		"boss": "Nex",
		"npc": "Nex"
	},
	{
		"title": "Virtus mask",
		"quantity": 1,
		"price": 2107641,
		"rarity": "Rare",
		"droprate": 277,
		"type": "Armour",
		"img": "/img/rs3/virtus_mask.png",
		"game": "rs3",
		"boss": "Nex",
		"npc": "Nex"
	},
	{
		"title": "Virtus robe top",
		"quantity": 1,
		"price": 6533950,
		"rarity": "Rare",
		"droprate": 277,
		"type": "Armour",
		"img": "/img/rs3/virtus_robe_top.png",
		"game": "rs3",
		"boss": "Nex",
		"npc": "Nex"
	},
	{
		"title": "Virtus robe legs",
		"quantity": 1,
		"price": 9153351,
		"rarity": "Rare",
		"droprate": 277,
		"type": "Armour",
		"img": "/img/rs3/virtus_robe_legs.png",
		"game": "rs3",
		"boss": "Nex",
		"npc": "Nex"
	},
	{
		"title": "Virtus boots",
		"quantity": 1,
		"price": 14188932,
		"rarity": "Rare",
		"droprate": null,
		"type": "Armour",
		"img": "/img/rs3/virtus_boots.png",
		"game": "rs3",
		"boss": "Nex",
		"npc": "Nex"
	},
	{
		"title": "Virtus gloves",
		"quantity": 1,
		"price": 3673156,
		"rarity": "Rare",
		"droprate": null,
		"type": "Armour",
		"img": "/img/rs3/virtus_gloves.png",
		"game": "rs3",
		"boss": "Nex",
		"npc": "Nex"
	},
	{
		"title": "Onyx bolts (e)",
		"quantity": 375,
		"price": 3214500,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "weapons",
		"img": "/img/rs3/onyx_bolts_e.png",
		"game": "rs3",
		"boss": "Nex",
		"npc": "Nex"
	},
	{
		"title": "Virtus wand",
		"quantity": 1,
		"price": 11986474,
		"rarity": "Rare",
		"droprate": null,
		"type": "weapons",
		"img": "/img/rs3/virtus_wand.png",
		"game": "rs3",
		"boss": "Nex",
		"npc": "Nex"
	},
	{
		"title": "Virtus book",
		"quantity": 1,
		"price": 4769213,
		"rarity": "Rare",
		"droprate": null,
		"type": "weapons",
		"img": "/img/rs3/virtus_book.png",
		"game": "rs3",
		"boss": "Nex",
		"npc": "Nex"
	},
	{
		"title": "Zaryte bow",
		"quantity": 1,
		"price": 35463127,
		"rarity": "Rare",
		"droprate": 277,
		"type": "weapons",
		"img": "/img/rs3/zaryte_bow.png",
		"game": "rs3",
		"boss": "Nex",
		"npc": "Nex"
	},
	{
		"title": "Grimy avantoe",
		"quantity": 75,
		"price": 4023,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "herbs",
		"img": "/img/rs3/grimy_avantoe.png",
		"game": "rs3",
		"boss": "Nex",
		"npc": "Nex"
	},
	{
		"title": "Grimy dwarf weed ",
		"quantity": 75,
		"price": 6334,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "herbs",
		"img": "/img/rs3/grimy_dwarf_weed.png",
		"game": "rs3",
		"boss": "Nex",
		"npc": "Nex"
	},
	{
		"title": "Grimy torstol",
		"quantity": 40,
		"price": 5354,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "herbs",
		"img": "/img/rs3/grimy_torstol.png",
		"game": "rs3",
		"boss": "Nex",
		"npc": "Nex"
	},
	{
		"title": "Magic seed",
		"quantity": 5,
		"price": 148382,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "seed",
		"img": "/img/rs3/magic_seed.png",
		"game": "rs3",
		"boss": "Nex",
		"npc": "Nex"
	},
	{
		"title": "Magic logs",
		"quantity": 375,
		"price": 908,
		"rarity": "Common",
		"droprate": null,
		"type": "materials",
		"img": "/img/rs3/magic_logs.png",
		"game": "rs3",
		"boss": "Nex",
		"npc": "Nex"
	},
	{
		"title": "Coal",
		"quantity": 2400,
		"price": 314,
		"rarity": "Common",
		"droprate": null,
		"type": "materials",
		"img": "/img/rs3/coal.png",
		"game": "rs3",
		"boss": "Nex",
		"npc": "Nex"
	},
	{
		"title": "Runite ore",
		"quantity": 80,
		"price": 11053,
		"rarity": "Common",
		"droprate": null,
		"type": "materials",
		"img": "/img/rs3/runite_ore.png",
		"game": "rs3",
		"boss": "Nex",
		"npc": "Nex"
	},
	{
		"title": "Green dragonhide",
		"quantity": 400,
		"price": 1498,
		"rarity": "Common",
		"droprate": null,
		"type": "materials",
		"img": "/img/rs3/green_dragonhide.png",
		"game": "rs3",
		"boss": "Nex",
		"npc": "Nex"
	},
	{
		"title": "Uncut dragonstone",
		"quantity": 20,
		"price": 12768,
		"rarity": "Common",
		"droprate": null,
		"type": "materials",
		"img": "/img/rs3/uncut_dragonstone.png",
		"game": "rs3",
		"boss": "Nex",
		"npc": "Nex"
	},
	{
		"title": "30 Super restores + 10 Saradomin brews",
		"quantity": 1,
		"price": null,
		"rarity": "Common",
		"droprate": null,
		"type": "potions",
		"img": "/img/rs3/nex_rests_brews.png",
		"game": "rs3",
		"boss": "Nex",
		"npc": "Nex"
	},
	{
		"title": "30 Saradomin brews + 10 Super restores",
		"quantity": 1,
		"price": null,
		"rarity": "Common",
		"droprate": null,
		"type": "potions",
		"img": "/img/rs3/nex_brews_rests.png",
		"game": "rs3",
		"boss": "Nex",
		"npc": "Nex"
	},
	{
		"title": "Clue scroll (hard)",
		"quantity": 1,
		"price": null,
		"rarity": "Rare",
		"droprate": null,
		"type": "Other",
		"img": "/img/rs3/clue_scroll_hard.png",
		"game": "rs3",
		"boss": "Nex",
		"npc": "Nex"
	},
	{
		"title": "Clue scroll (elite)",
		"quantity": 1,
		"price": null,
		"rarity": "Rare",
		"droprate": null,
		"type": "Other",
		"img": "/img/rs3/clue_scroll_elite.png",
		"game": "rs3",
		"boss": "Nex",
		"npc": "Nex"
	},
	{
		"title": "Starved ancient effigy",
		"quantity": 1,
		"price": null,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "Other",
		"img": "/img/rs3/starved_ancient_effigy.png",
		"game": "rs3",
		"boss": "Nex",
		"npc": "Nex"
	},
	{
		"title": "Court summons",
		"quantity": 1,
		"price": null,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "Other",
		"img": "/img/rs3/court_summons.png",
		"game": "rs3",
		"boss": "Nex",
		"npc": "Nex"
	},
	{
		"title": "Blood-soaked feather",
		"quantity": 1,
		"price": null,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "Other",
		"img": "/img/rs3/blood_soaked_feather.png",
		"game": "rs3",
		"boss": "Nex",
		"npc": "Nex"
	}
];

