/*
* Queen Black Dragon drops list made by Alex.
*/

QbdDrops = [
	{
		"title": "Dragon bones",
		"quantity": 8,
		"price": 1913,
		"rarity": "Always",
		"droprate": null,
		"type": "100% drops",
		"img": "/img/rs3/dragon_bones.png",
		"game": "rs3",
		"boss": "Queen Black Dragon",
		"npc": "Queen Black Dragon"
	},
	{
		"title": "Royal dragonhide",
		"quantity": 6,
		"price": 4880,
		"rarity": "Always",
		"droprate": null,
		"type": "100% drops",
		"img": "/img/rs3/royal_dragonhide.png",
		"game": "rs3",
		"boss": "Queen Black Dragon",
		"npc": "Queen Black Dragon"
	},
	{
		"title": "Royal bolts",
		"quantity": 85,
		"price": 42,
		"rarity": "Always",
		"droprate": null,
		"type": "100% drops",
		"img": "/img/rs3/royal_bolts_5.png",
		"game": "rs3",
		"boss": "Queen Black Dragon",
		"npc": "Queen Black Dragon"
	},
	{
		"title": "First dragonkin journal",
		"quantity": 1,
		"price": null,
		"rarity": "Always",
		"droprate": null,
		"type": "Journals",
		"img": "/img/rs3/first_dragonkin_journal.png",
		"game": "rs3",
		"boss": "Queen Black Dragon",
		"npc": "Queen Black Dragon"
	},
	{
		"title": "Second dragonkin journal",
		"quantity": 1,
		"price": null,
		"rarity": "Common",
		"droprate": null,
		"type": "Journals",
		"img": "/img/rs3/second_dragonkin_journal.png",
		"game": "rs3",
		"boss": "Queen Black Dragon",
		"npc": "Queen Black Dragon"
	},
	{
		"title": "Third dragonkin journal",
		"quantity": 1,
		"price": null,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "Journals",
		"img": "/img/rs3/third_dragonkin_journal.png",
		"game": "rs3",
		"boss": "Queen Black Dragon",
		"npc": "Queen Black Dragon"
	},
	{
		"title": "Fourth dragonkin journal",
		"quantity": 1,
		"price": null,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "Journals",
		"img": "/img/rs3/fourth_dragonkin_journal.png",
		"game": "rs3",
		"boss": "Queen Black Dragon",
		"npc": "Queen Black Dragon"
	},
	{
		"title": "Royal torsion spring",
		"quantity": 1,
		"price": 89916,
		"rarity": "Rare",
		"droprate": null,
		"type": "Unique",
		"img": "/img/rs3/royal_torsion_spring.png",
		"game": "rs3",
		"boss": "Queen Black Dragon",
		"npc": "Queen Black Dragon"
	},
	{
		"title": "Royal sight",
		"quantity": 1,
		"price": 90489,
		"rarity": "Rare",
		"droprate": null,
		"type": "Unique",
		"img": "/img/rs3/royal_sight.png",
		"game": "rs3",
		"boss": "Queen Black Dragon",
		"npc": "Queen Black Dragon"
	},
	{
		"title": "Royal frame",
		"quantity": 1,
		"price": 90910,
		"rarity": "Rare",
		"droprate": null,
		"type": "Unique",
		"img": "/img/rs3/royal_frame.png",
		"game": "rs3",
		"boss": "Queen Black Dragon",
		"npc": "Queen Black Dragon"
	},
	{
		"title": "Royal bolt stabiliser",
		"quantity": 1,
		"price": 92445,
		"rarity": "Rare",
		"droprate": null,
		"type": "Unique",
		"img": "/img/rs3/royal_bolt_stabiliser.png",
		"game": "rs3",
		"boss": "Queen Black Dragon",
		"npc": "Queen Black Dragon"
	},
	{
		"title": "Dragon kiteshield",
		"quantity": 1,
		"price": 336042,
		"rarity": "Rare",
		"droprate": 192,
		"type": "Unique",
		"img": "/img/rs3/dragon_kiteshield.png",
		"game": "rs3",
		"boss": "Queen Black Dragon",
		"npc": "Queen Black Dragon"
	},
	{
		"title": "Dragonbone upgrade kit",
		"quantity": 1,
		"price": 11335,
		"rarity": "Rare",
		"droprate": 104,
		"type": "Unique",
		"img": "/img/rs3/dragonbone_upgrade_kit.png",
		"game": "rs3",
		"boss": "Queen Black Dragon",
		"npc": "Queen Black Dragon"
	},
	{
		"title": "Queen black dragon scale",
		"quantity": 1,
		"price": null,
		"rarity": "Very rare",
		"droprate": 2500,
		"type": "Unique",
		"img": "/img/rs3/queen_black_dragon_scale.png",
		"game": "rs3",
		"boss": "Queen Black Dragon",
		"npc": "Queen Black Dragon"
	},
	{
		"title": "Rocktail",
		"quantity": 7,
		"price": 1779,
		"rarity": "Common",
		"droprate": null,
		"type": "Consumables",
		"img": "/img/rs3/rocktail.png",
		"game": "rs3",
		"boss": "Queen Black Dragon",
		"npc": "Queen Black Dragon"
	},
	{
		"title": "Saradomin brew (2)",
		"quantity": 7,
		"price": 4353,
		"rarity": "Common",
		"droprate": null,
		"type": "Consumables",
		"img": "/img/rs3/saradomin_brew_(2).png",
		"game": "rs3",
		"boss": "Queen Black Dragon",
		"npc": "Queen Black Dragon"
	},
	{
		"title": "Super restore (2)",
		"quantity": 7,
		"price": 1538,
		"rarity": "Common",
		"droprate": null,
		"type": "Consumables",
		"img": "/img/rs3/super_restore_(2).png",
		"game": "rs3",
		"boss": "Queen Black Dragon",
		"npc": "Queen Black Dragon"
	},
	{
		"title": "Runite ore",
		"quantity": 30,
		"price": 11053,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "Main Drops",
		"img": "/img/rs3/runite_ore.png",
		"game": "rs3",
		"boss": "Queen Black Dragon",
		"npc": "Queen Black Dragon"
	},
	{
		"title": "Coal",
		"quantity": 300,
		"price": 314,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "Main Drops",
		"img": "/img/rs3/coal.png",
		"game": "rs3",
		"boss": "Queen Black Dragon",
		"npc": "Queen Black Dragon"
	},
	{
		"title": "Adamantite ore",
		"quantity": 50,
		"price": 1401,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "Main Drops",
		"img": "/img/rs3/adamantite_ore.png",
		"game": "rs3",
		"boss": "Queen Black Dragon",
		"npc": "Queen Black Dragon"
	},
	{
		"title": "Uncut dragonstone",
		"quantity": 5,
		"price": 12768,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "Main Drops",
		"img": "/img/rs3/uncut_dragonstone.png",
		"game": "rs3",
		"boss": "Queen Black Dragon",
		"npc": "Queen Black Dragon"
	},
	{
		"title": "Yew logs",
		"quantity": 300,
		"price": 268,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "Main Drops",
		"img": "/img/rs3/yew_logs.png",
		"game": "rs3",
		"boss": "Queen Black Dragon",
		"npc": "Queen Black Dragon"
	},
	{
		"title": "Magic logs",
		"quantity": 120,
		"price": 908,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "Main Drops",
		"img": "/img/rs3/magic_logs.png",
		"game": "rs3",
		"boss": "Queen Black Dragon",
		"npc": "Queen Black Dragon"
	},
	{
		"title": "Onyx bolt tips",
		"quantity": 30,
		"price": 8092,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "Main Drops",
		"img": "/img/rs3/onyx_bolt_tips_5.png",
		"game": "rs3",
		"boss": "Queen Black Dragon",
		"npc": "Queen Black Dragon"
	},
	{
		"title": "Grimy torstol",
		"quantity": 10,
		"price": 5354,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "Main Drops",
		"img": "/img/rs3/grimy_torstol.png",
		"game": "rs3",
		"boss": "Queen Black Dragon",
		"npc": "Queen Black Dragon"
	},
	{
		"title": "Grimy lantadyme",
		"quantity": 50,
		"price": 5898,
		"rarity": "Rare",
		"droprate": null,
		"type": "Main Drops",
		"img": "/img/rs3/grimy_lantadyme.png",
		"game": "rs3",
		"boss": "Queen Black Dragon",
		"npc": "Queen Black Dragon"
	},
	{
		"title": "Snapdragon seed",
		"quantity": 5,
		"price": 514,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "Main Drops",
		"img": "/img/rs3/herb_seed_5.png",
		"game": "rs3",
		"boss": "Queen Black Dragon",
		"npc": "Queen Black Dragon"
	},
	{
		"title": "Lantadyme seed",
		"quantity": 1,
		"price": 9786,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "Main Drops",
		"img": "/img/rs3/herb_seed_1.png",
		"game": "rs3",
		"boss": "Queen Black Dragon",
		"npc": "Queen Black Dragon"
	},
	{
		"title": "Torstol seed",
		"quantity": 1,
		"price": 8505,
		"rarity": "Rare",
		"droprate": null,
		"type": "Main Drops",
		"img": "/img/rs3/herb_seed_1.png",
		"game": "rs3",
		"boss": "Queen Black Dragon",
		"npc": "Queen Black Dragon"
	},
	{
		"title": "Magic seed",
		"quantity": 1,
		"price": 148382,
		"rarity": "Rare",
		"droprate": null,
		"type": "Main Drops",
		"img": "/img/rs3/magic_seed_1.png",
		"game": "rs3",
		"boss": "Queen Black Dragon",
		"npc": "Queen Black Dragon"
	},
	{
		"title": "Coins",
		"quantity": 175000,
		"price": 1,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "Main Drops",
		"img": "/img/rs3/coins_10000.png",
		"game": "rs3",
		"boss": "Queen Black Dragon",
		"npc": "Queen Black Dragon"
	},
	{
		"title": "Raw shark",
		"quantity": 40,
		"price": 753,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "Main Drops",
		"img": "/img/rs3/raw_shark.png",
		"game": "rs3",
		"boss": "Queen Black Dragon",
		"npc": "Queen Black Dragon"
	},
	{
		"title": "Draconic visage",
		"quantity": 1,
		"price": 1290985,
		"rarity": "Rare",
		"droprate": null,
		"type": "Main Drops",
		"img": "/img/rs3/draconic_visage.png",
		"game": "rs3",
		"boss": "Queen Black Dragon",
		"npc": "Queen Black Dragon"
	},
	{
		"title": "Starved ancient effigy",
		"quantity": 1,
		"price": null,
		"rarity": "Rare",
		"droprate": null,
		"type": "Main Drops",
		"img": "/img/rs3/starved_ancient_effigy.png",
		"game": "rs3",
		"boss": "Queen Black Dragon",
		"npc": "Queen Black Dragon"
	}	
];




