/*
* RS3 Saradomin drops list made by Mokuin.
*/

SaradominDropsRs3 = [
	{
		"title": "Saradomin sword",
		"quantity": 1,
		"price": 121626,
		"rarity": "Rare",
		"droprate": 79,
		"type": "weapons",
		"img": "/img/rs3/saradomin_sword.png",
		"game": "rs3",
		"boss": "Saradomin",
		"npc": "Commander Zilyana"
	},
	{
		"title": "Armadyl crossbow",
		"quantity": 1,
		"price": 1365467,
		"rarity": "Rare",
		"droprate": null,
		"type": "weapons",
		"img": "/img/rs3/armadyl_crossbow.png",
		"game": "rs3",
		"boss": "Saradomin",
		"npc": "Commander Zilyana"
	},
	{
		"title": "Battlestaff",
		"quantity": 2,
		"price": 7156,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "weapons",
		"img": "/img/rs3/battlestaff.png",
		"game": "rs3",
		"boss": "Saradomin",
		"npc": "Commander Zilyana"
	},
	{
		"title": "Rune dart",
		"quantity": 38,
		"price": 100,
		"rarity": "Common",
		"droprate": null,
		"type": "weapons",
		"img": "/img/rs3/rune_dart.png",
		"game": "rs3",
		"boss": "Saradomin",
		"npc": "Commander Zilyana"
	},
	{
		"title": "Rune plateskirt",
		"quantity": 1,
		"price": 37294,
		"rarity": "Common",
		"droprate": null,
		"type": "Armour",
		"img": "/img/rs3/rune_plateskirt.png",
		"game": "rs3",
		"boss": "Saradomin",
		"npc": "Commander Zilyana"
	},
	{
		"title": "Adamant platebody",
		"quantity": 1,
		"price": 9443,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "Armour",
		"img": "/img/rs3/adamant_platebody.png",
		"game": "rs3",
		"boss": "Saradomin",
		"npc": "Commander Zilyana"
	},
	{
		"title": "Rune kiteshield",
		"quantity": 1,
		"price": 31651,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "Armour",
		"img": "/img/rs3/rune_kiteshield.png",
		"game": "rs3",
		"boss": "Saradomin",
		"npc": "Commander Zilyana"
	},
	{
		"title": "Saradomin's murmur",
		"quantity": 1,
		"price": 843748,
		"rarity": "Rare",
		"droprate": null,
		"type": "Armour",
		"img": "/img/rs3/saradomins_murmur.png",
		"game": "rs3",
		"boss": "Saradomin",
		"npc": "Commander Zilyana"
	},
	{
		"title": "Saradomin's hiss",
		"quantity": 1,
		"price": 110817,
		"rarity": "Rare",
		"droprate": null,
		"type": "Armour",
		"img": "/img/rs3/saradomins_hiss.png",
		"game": "rs3",
		"boss": "Saradomin",
		"npc": "Commander Zilyana"
	},
	{
		"title": "Saradomin's whisper",
		"quantity": 1,
		"price": 767292,
		"rarity": "Rare",
		"droprate": null,
		"type": "Armour",
		"img": "/img/rs3/saradomins_whisper.png",
		"game": "rs3",
		"boss": "Saradomin",
		"npc": "Commander Zilyana"
	},
	{
		"title": "Warpriest of Saradomin helm",
		"quantity": 1,
		"price": null,
		"rarity": "Varies",
		"droprate": null,
		"type": "Armour",
		"img": "/img/rs3/warpriest_of_saradomin_helm.png",
		"game": "rs3",
		"boss": "Saradomin",
		"npc": "Commander Zilyana"
	},
	{
		"title": "Warpriest of Saradomin cuirass",
		"quantity": 1,
		"price": null,
		"rarity": "Varies",
		"droprate": null,
		"type": "Armour",
		"img": "/img/rs3/warpriest_of_saradomin_cuirass.png",
		"game": "rs3",
		"boss": "Saradomin",
		"npc": "Commander Zilyana"
	},
	{
		"title": "Warpriest of Saradomin greaves",
		"quantity": 1,
		"price": null,
		"rarity": "Varies",
		"droprate": null,
		"type": "Armour",
		"img": "/img/rs3/warpriest_of_saradomin_greaves.png",
		"game": "rs3",
		"boss": "Saradomin",
		"npc": "Commander Zilyana"
	},
	{
		"title": "Warpriest of Saradomin gauntlets",
		"quantity": 1,
		"price": null,
		"rarity": "Varies",
		"droprate": null,
		"type": "Armour",
		"img": "/img/rs3/warpriest_of_saradomin_gauntlets.png",
		"game": "rs3",
		"boss": "Saradomin",
		"npc": "Commander Zilyana"
	},
	{
		"title": "Warpriest of Saradomin boots",
		"quantity": 1,
		"price": null,
		"rarity": "Varies",
		"droprate": null,
		"type": "Armour",
		"img": "/img/rs3/warpriest_of_saradomin_boots.png",
		"game": "rs3",
		"boss": "Saradomin",
		"npc": "Commander Zilyana"
	},
	{
		"title": "Warpriest of Saradomin cape",
		"quantity": 1,
		"price": null,
		"rarity": "Varies",
		"droprate": null,
		"type": "Armour",
		"img": "/img/rs3/warpriest_of_saradomin_cape.png",
		"game": "rs3",
		"boss": "Saradomin",
		"npc": "Commander Zilyana"
	},
	{
		"title": "Grimy ranarr",
		"quantity": 5,
		"price": 2299,
		"rarity": "Common",
		"droprate": null,
		"type": "herb",
		"img": "/img/rs3/grimy_ranarr.png",
		"game": "rs3",
		"boss": "Saradomin",
		"npc": "Commander Zilyana"
	},
	{
		"title": "Ranarr seed",
		"quantity": 2,
		"price": 796,
		"rarity": "Common",
		"droprate": null,
		"type": "seed",
		"img": "/img/rs3/ranarr_seed.png",
		"game": "rs3",
		"boss": "Saradomin",
		"npc": "Commander Zilyana"
	},
	{
		"title": "	Super magic potion (3)",
		"quantity": 3,
		"price": 5726,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "potion",
		"img": "/img/rs3/super_magic_potion_3.png",
		"game": "rs3",
		"boss": "Saradomin",
		"npc": "Commander Zilyana"
	},
	{
		"title": "prayer potion (4)",
		"quantity": 3,
		"price": 2922,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "potion",
		"img": "/img/rs3/prayer_potion_4.png",
		"game": "rs3",
		"boss": "Saradomin",
		"npc": "Commander Zilyana"
	},
	{
		"title": "Saradomin brew (3)",
		"quantity": 3,
		"price": 6627,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "potion",
		"img": "/img/rs3/saradomin_brew_3.png",
		"game": "rs3",
		"boss": "Saradomin",
		"npc": "Commander Zilyana"
	},
	{
		"title": "Super defence (4)",
		"quantity": 3,
		"price": 3964,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "potion",
		"img": "/img/rs3/super_defence_4.png",
		"game": "rs3",
		"boss": "Saradomin",
		"npc": "Commander Zilyana"
	},
	{
		"title": "super restore (4)",
		"quantity": 3,
		"price": 3476,
		"rarity": "Common",
		"droprate": null,
		"type": "potion",
		"img": "/img/rs3/super_restore_4.png",
		"game": "rs3",
		"boss": "Saradomin",
		"npc": "Commander Zilyana"
	},
	{
		"title": "Magic seed",
		"quantity": 1,
		"price": 148382,
		"rarity": "Rare",
		"droprate": null,
		"type": "seed",
		"img": "/img/rs3/magic_seed.png",
		"game": "rs3",
		"boss": "Saradomin",
		"npc": "Commander Zilyana"
	},
	{
		"title": "Coins",
		"quantity": 19500,
		"price": 1,
		"rarity": "Common",
		"droprate": null,
		"type": "Other",
		"img": "/img/rs3/coins.png",
		"game": "rs3",
		"boss": "Saradomin",
		"npc": "Commander Zilyana"
	},
	{
		"title": "Diamond",
		"quantity": 6,
		"price": 1846,
		"rarity": "Rare",
		"droprate": null,
		"type": "Other",
		"img": "/img/rs3/diamond.png",
		"game": "rs3",
		"boss": "Saradomin",
		"npc": "Commander Zilyana"
	},
	{
		"title": "Starved ancient effigy",
		"quantity": 1,
		"price": null,
		"rarity": "Rare",
		"droprate": null,
		"type": "Other",
		"img": "/img/rs3/starved_ancient_effigy.png",
		"game": "rs3",
		"boss": "Saradomin",
		"npc": "Commander Zilyana"
	},
	{
		"title": "Godsword shard 1",
		"quantity": 1,
		"price": 147141,
		"rarity": "Rare",
		"droprate": "480",
		"type": "Other",
		"img": "/img/rs3/godsword_shard_1.png",
		"game": "rs3",
		"boss": "Saradomin",
		"npc": "Commander Zilyana"
	},
	{
		"title": "Godsword shard 2",
		"quantity": 1,
		"price": 146960,
		"rarity": "Rare",
		"droprate": 654,
		"type": "Other",
		"img": "/img/rs3/godsword_shard_2.png",
		"game": "rs3",
		"boss": "Saradomin",
		"npc": "Commander Zilyana"
	},
	{
		"title": "Godsword shard 3",
		"quantity": 1,
		"price": 147075,
		"rarity": "Rare",
		"droprate": 553,
		"type": "Other",
		"img": "/img/rs3/godsword_shard_3.png",
		"game": "rs3",
		"boss": "Saradomin",
		"npc": "Commander Zilyana"
	},
	{
		"title": "Saradomin hilt",
		"quantity": 1,
		"price": 10763313,
		"rarity": "Rare",
		"droprate": 480,
		"type": "Other",
		"img": "/img/rs3/saradomin_hilt.png",
		"game": "rs3",
		"boss": "Saradomin",
		"npc": "Commander Zilyana"
	},
	{
		"title": "Auburn lock",
		"quantity": 1,
		"price": null,
		"rarity": "Very rare",
		"droprate": null,
		"type": "Other",
		"img": "/img/rs3/auburn_lock.png",
		"game": "rs3",
		"boss": "Saradomin",
		"npc": "Commander Zilyana"
	},
	{
		"title": "Clue scroll (hard)",
		"quantity": 1,
		"price": null,
		"rarity": "Rare",
		"droprate": null,
		"type": "Other",
		"img": "/img/rs3/clue_scroll_hard.png",
		"game": "rs3",
		"boss": "Saradomin",
		"npc": "Commander Zilyana"
	},
	{
		"title": "Clue scroll (elite)",
		"quantity": 1,
		"price": null,
		"rarity": "Rare",
		"droprate": null,
		"type": "Other",
		"img": "/img/rs3/clue_scroll_elite.png",
		"game": "rs3",
		"boss": "Saradomin",
		"npc": "Commander Zilyana"
	}
];

