/*
* OSRS Scorpia drops list made by Mokuin.
*/

ScorpiaDrops = [
	{
		"title": "Phoenix necklace",
		"quantity": 1,
		"price": 2365,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "armour",
		"img": "/img/osrs/phoenix_necklace.png",
		"game": "osrs",
		"boss": "Scorpia",
		"npc": "Scorpia"
	},
	{
		"title": "Rune chainbody",
		"quantity": 1,
		"price": 32461,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "armour",
		"img": "/img/osrs/rune_chainbody.png",
		"game": "osrs",
		"boss": "Scorpia",
		"npc": "Scorpia"
	},
	{
		"title": "Rune sq shield",
		"quantity": 1,
		"price": 24673,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "armour",
		"img": "/img/osrs/rune_sq_shield.png",
		"game": "osrs",
		"boss": "Scorpia",
		"npc": "Scorpia"
	},
	{
		"title": "Rune pickaxe",
		"quantity": 1,
		"price": 19775,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "weapons",
		"img": "/img/osrs/rune_pickaxe.png",
		"game": "osrs",
		"boss": "Scorpia",
		"npc": "Scorpia"
	},
	{
		"title": "Rune scimitar",
		"quantity": 1,
		"price": 17254,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "weapons",
		"img": "/img/osrs/rune_scimitar.png",
		"game": "osrs",
		"boss": "Scorpia",
		"npc": "Scorpia"
	},
	{
		"title": "Rune spear",
		"quantity": 1,
		"price": 12766,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "weapons",
		"img": "/img/osrs/rune_spear.png",
		"game": "osrs",
		"boss": "Scorpia",
		"npc": "Scorpia"
	},
	{
		"title": "Rune sword",
		"quantity": 1,
		"price": 13313,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "weapons",
		"img": "/img/osrs/rune_sword.png",
		"game": "osrs",
		"boss": "Scorpia",
		"npc": "Scorpia"
	},
	{
		"title": "Rune warhammer",
		"quantity": 1,
		"price": 26565,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "weapons",
		"img": "/img/osrs/rune_warhammer.png",
		"game": "osrs",
		"boss": "Scorpia",
		"npc": "Scorpia"
	},
	{
		"title": "Rune 2h sword",
		"quantity": 1,
		"price": 41695,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "weapons",
		"img": "/img/osrs/rune_2h_sword.png",
		"game": "osrs",
		"boss": "Scorpia",
		"npc": "Scorpia"
	},
	{
		"title": "Dragon scimitar",
		"quantity": 1,
		"price": 68048,
		"rarity": "Rare",
		"droprate": null,
		"type": "weapons",
		"img": "/img/osrs/dragon_scimitar.png",
		"game": "osrs",
		"boss": "Scorpia",
		"npc": "Scorpia"
	},
	{
		"title": "Coins",
		"quantity": 2000,
		"price": 1,
		"rarity": "Common",
		"droprate": null,
		"type": "other",
		"img": "/img/osrs/coins.png",
		"game": "osrs",
		"boss": "Scorpia",
		"npc": "Scorpia"
	},
	{
		"title": "Admiral pie",
		"quantity": 3,
		"price": 1693,
		"rarity": "Common",
		"droprate": null,
		"type": "other",
		"img": "/img/osrs/admiral_pie.png",
		"game": "osrs",
		"boss": "Scorpia",
		"npc": "Scorpia"
	},
	{
		"title": "Anchovy pizza",
		"quantity": 8,
		"price": 853,
		"rarity": "Common",
		"droprate": null,
		"type": "other",
		"img": "/img/osrs/anchovy_pizza.png",
		"game": "osrs",
		"boss": "Scorpia",
		"npc": "Scorpia"
	},
	{
		"title": "Bucket of sand",
		"quantity": 25,
		"price": 40,
		"rarity": "Common",
		"droprate": null,
		"type": "other",
		"img": "/img/osrs/bucket_of_sand.png",
		"game": "osrs",
		"boss": "Scorpia",
		"npc": "Scorpia"
	},
	{
		"title": "Cactus spine",
		"quantity": 10,
		"price": 4117,
		"rarity": "Common",
		"droprate": null,
		"type": "other",
		"img": "/img/osrs/cactus_spine.png",
		"game": "osrs",
		"boss": "Scorpia",
		"npc": "Scorpia"
	},
	{
		"title": "Prayer potion (4)",
		"quantity": 1,
		"price": 7666,
		"rarity": "Common",
		"droprate": null,
		"type": "other",
		"img": "/img/osrs/prayer_potion_4.png",
		"game": "osrs",
		"boss": "Scorpia",
		"npc": "Scorpia"
	},
	{
		"title": "Shark",
		"quantity": 1,
		"price": 906,
		"rarity": "Common",
		"droprate": null,
		"type": "other",
		"img": "/img/osrs/shark.png",
		"game": "osrs",
		"boss": "Scorpia",
		"npc": "Scorpia"
	},
	{
		"title": "Uncut sapphire",
		"quantity": 4,
		"price": 585,
		"rarity": "Common",
		"droprate": null,
		"type": "other",
		"img": "/img/osrs/uncut_sapphire.png",
		"game": "osrs",
		"boss": "Scorpia",
		"npc": "Scorpia"
	},
	{
		"title": "Uncut emerald",
		"quantity": 6,
		"price": 1380,
		"rarity": "Common",
		"droprate": null,
		"type": "other",
		"img": "/img/osrs/uncut_emerald.png",
		"game": "osrs",
		"boss": "Scorpia",
		"npc": "Scorpia"
	},
	{
		"title": "Dust rune",
		"quantity": 30,
		"price": 16,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "other",
		"img": "/img/osrs/dust_rune.png",
		"game": "osrs",
		"boss": "Scorpia",
		"npc": "Scorpia"
	},
	{
		"title": "Kwuarm",
		"quantity": 4,
		"price": 2527,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "other",
		"img": "/img/osrs/kwuarm.png",
		"game": "osrs",
		"boss": "Scorpia",
		"npc": "Scorpia"
	},
	{
		"title": "Super antipoison (4)",
		"quantity": 4,
		"price": 1892,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "other",
		"img": "/img/osrs/super_antipoison_4.png",
		"game": "osrs",
		"boss": "Scorpia",
		"npc": "Scorpia"
	},
	{
		"title": "Mysterious emblem",
		"quantity": 1,
		"price": null,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "other",
		"img": "/img/osrs/mysterious_emblem.png",
		"game": "osrs",
		"boss": "Scorpia",
		"npc": "Scorpia"
	},
	{
		"title": "Odium shard 3",
		"quantity": 1,
		"price": 6165016,
		"rarity": "Rare",
		"droprate": null,
		"type": "other",
		"img": "/img/osrs/odium_shard_3.png",
		"game": "osrs",
		"boss": "Scorpia",
		"npc": "Scorpia"
	},
	{
		"title": "Malediction shard 3",
		"quantity": 1,
		"price": 2879094,
		"rarity": "Rare",
		"droprate": null,
		"type": "other",
		"img": "/img/osrs/malediction_shard_3.png",
		"game": "osrs",
		"boss": "Scorpia",
		"npc": "Scorpia"
	},
	{
		"title": "Clue scroll (hard)",
		"quantity": 1,
		"price": null,
		"rarity": "Rare",
		"droprate": null,
		"type": "other",
		"img": "/img/osrs/clue_scroll_hard.png",
		"game": "osrs",
		"boss": "Scorpia",
		"npc": "Scorpia"
	},
	{
		"title": "Scorpia's offspring",
		"quantity": 1,
		"price": null,
		"rarity": "Very rare",
		"droprate": 2000,
		"type": "other",
		"img": "/img/osrs/scorpias_offspring.png",
		"game": "osrs",
		"boss": "Scorpia",
		"npc": "Scorpia"
	}
];

