/*
* Tormented Demon drops list made by Aimer.
*/

TormentedDemonDropsRS3 = [
	{
		"title": "Adamant battleaxe",
		"quantity": 1,
		"price": 1960,
		"rarity": "Common",
		"droprate": null,
		"type": "Weapons",
		"img": "/img/rs3/adamant_battleaxe.png",
		"game": "rs3",
		"boss": "Tormented Demon",
		"npc": "Tormented Demon"
	},
	{
		"title": "Rune mace",
		"quantity": 1,
		"price": 7963,
		"rarity": "Common",
		"droprate": null,
		"type": "Weapons",
		"img": "/img/rs3/rune_mace.png",
		"game": "rs3",
		"boss": "Tormented Demon",
		"npc": "Tormented Demon"
	},
	{
		"title": "Rune sword",
		"quantity": 1,
		"price": 12068,
		"rarity": "Common",
		"droprate": null,
		"type": "Weapons",
		"img": "/img/rs3/rune_sword.png",
		"game": "rs3",
		"boss": "Tormented Demon",
		"npc": "Tormented Demon"
	},
	{
		"title": "Dragon claws",
		"quantity": 1,
		"price": 235000,
		"rarity": "rare",
		"droprate": null,
		"type": "Weapons",
		"img": "/img/rs3/dragon_claws.png",
		"game": "rs3",
		"boss": "Tormented Demon",
		"npc": "Tormented Demon"
	},
	{
		"title": "Rune sq shield",
		"quantity": 1,
		"price": 21982,
		"rarity": "Common",
		"droprate": null,
		"type": "armour",
		"img": "/img/rs3/rune_sq_shield.png",
		"game": "rs3",
		"boss": "Tormented Demon",
		"npc": "Tormented Demon"
	},
	{
		"title": "Rune chainbody",
		"quantity": 1,
		"price": 29286,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "armour",
		"img": "/img/rs3/rune_chainbody.png",
		"game": "rs3",
		"boss": "Tormented Demon",
		"npc": "Tormented Demon"
	},
	{
		"title": "Rune full helm",
		"quantity": 1,
		"price": 20204,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "armour",
		"img": "/img/rs3/rune_full_helm.png",
		"game": "rs3",
		"boss": "Tormented Demon",
		"npc": "Tormented Demon"
	},
	{
		"title": "Avantoe seed",
		"quantity": 1,
		"price": 435,
		"rarity": "Common",
		"droprate": null,
		"type": "Seeds",
		"img": "/img/rs3/avantoe_seed.png",
		"game": "rs3",
		"boss": "Tormented Demon",
		"npc": "Tormented Demon"
	},
	{
		"title": "Belladonna seed",
		"quantity": 1,
		"price": 104,
		"rarity": "Common",
		"droprate": null,
		"type": "Seeds",
		"img": "/img/rs3/belladonna_seed.png",
		"game": "rs3",
		"boss": "Tormented Demon",
		"npc": "Tormented Demon"
	},
	{
		"title": "Bittercap mushroom spore",
		"quantity": 1,
		"price": 16,
		"rarity": "Common",
		"droprate": null,
		"type": "Seeds",
		"img": "/img/rs3/bittercap_mushroom_spore.png",
		"game": "rs3",
		"boss": "Tormented Demon",
		"npc": "Tormented Demon"
	},
	{
		"title": "Cactus seed",
		"quantity": 7,
		"price": 93,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "Seeds",
		"img": "/img/rs3/cactus_seed.png",
		"game": "rs3",
		"boss": "Tormented Demon",
		"npc": "Tormented Demon"
	},
	{
		"title": "Cadantine seed",
		"quantity": 2,
		"price": 462,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "Seeds",
		"img": "/img/rs3/cadantine_seed.png",
		"game": "rs3",
		"boss": "Tormented Demon",
		"npc": "Tormented Demon"
	},
	{
		"title": "Dwarf weed seed",
		"quantity": 1,
		"price": 15624,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "Seeds",
		"img": "/img/rs3/dwarf_weed_seed.png",
		"game": "rs3",
		"boss": "Tormented Demon",
		"npc": "Tormented Demon"
	},
	{
		"title": "Grapevine seed",
		"quantity": 3,
		"price": 3806,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "Seeds",
		"img": "/img/rs3/grapevine_seed.png",
		"game": "rs3",
		"boss": "Tormented Demon",
		"npc": "Tormented Demon"
	},
	{
		"title": "Harralander seed",
		"quantity": 1,
		"price": 9,
		"rarity": "Common",
		"droprate": null,
		"type": "Seeds",
		"img": "/img/rs3/harralander_seed.png",
		"game": "rs3",
		"boss": "Tormented Demon",
		"npc": "Tormented Demon"
	},
	{
		"title": "Jangerberry seed",
		"quantity": 2,
		"price": 1,
		"rarity": "Common",
		"droprate": null,
		"type": "Seeds",
		"img": "/img/rs3/jangerberry_seed.png",
		"game": "rs3",
		"boss": "Tormented Demon",
		"npc": "Tormented Demon"
	},
	{
		"title": "Kwuarm seed",
		"quantity": 1,
		"price": 746,
		"rarity": "Common",
		"droprate": null,
		"type": "Seeds",
		"img": "/img/rs3/kwuarm_seed.png",
		"game": "rs3",
		"boss": "Tormented Demon",
		"npc": "Tormented Demon"
	},
	{
		"title": "Lantadyme seed",
		"quantity": 1,
		"price": 9786,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "Seeds",
		"img": "/img/rs3/lantadyme_seed.png",
		"game": "rs3",
		"boss": "Tormented Demon",
		"npc": "Tormented Demon"
	},
	{
		"title": "Limpwurt seed",
		"quantity": 1,
		"price": 798,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "Seeds",
		"img": "/img/rs3/limpwurt_seed.png",
		"game": "rs3",
		"boss": "Tormented Demon",
		"npc": "Tormented Demon"
	},
	{
		"title": "Marrentill seed",
		"quantity": 1,
		"price": 9,
		"rarity": "Common",
		"droprate": null,
		"type": "Seeds",
		"img": "/img/rs3/marrentill_seed.png",
		"game": "rs3",
		"boss": "Tormented Demon",
		"npc": "Tormented Demon"
	},
	{
		"title": "Ranarr seed",
		"quantity": 2,
		"price": 796,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "Seeds",
		"img": "/img/rs3/ranarr_seed.png",
		"game": "rs3",
		"boss": "Tormented Demon",
		"npc": "Tormented Demon"
	},
	{
		"title": "Spirit weed seed",
		"quantity": 1,
		"price": 532,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "Seeds",
		"img": "/img/rs3/spirit_weed_seed.png",
		"game": "rs3",
		"boss": "Tormented Demon",
		"npc": "Tormented Demon"
	},
	{
		"title": "Strawberry seed",
		"quantity": 3,
		"price": 344,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "Seeds",
		"img": "/img/rs3/strawberry_seed.png",
		"game": "rs3",
		"boss": "Tormented Demon",
		"npc": "Tormented Demon"
	},
	{
		"title": "Toadflax seed",
		"quantity": 1,
		"price": 1025,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "Seeds",
		"img": "/img/rs3/toadflax_seed.png",
		"game": "rs3",
		"boss": "Tormented Demon",
		"npc": "Tormented Demon"
	},
	{
		"title": "Whiteberry seed",
		"quantity": 2,
		"price": 12,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "Seeds",
		"img": "/img/rs3/whiteberry_seed.png",
		"game": "rs3",
		"boss": "Tormented Demon",
		"npc": "Tormented Demon"
	},
	{
		"title": "Wildblood seed",
		"quantity": 2,
		"price": 96,
		"rarity": "Common",
		"droprate": null,
		"type": "Seeds",
		"img": "/img/rs3/wildblood_seed.png",
		"game": "rs3",
		"boss": "Tormented Demon",
		"npc": "Tormented Demon"
	},
	{
		"title": "Grimy guam",
		"quantity": 6,
		"price": 339,
		"rarity": "Common",
		"droprate": null,
		"type": "herbs",
		"img": "/img/rs3/grimy_guam.png",
		"game": "rs3",
		"boss": "Tormented Demon",
		"npc": "Tormented Demon"
	},
	{
		"title": "Grimy marrentill",
		"quantity": 6,
		"price": 175,
		"rarity": "Common",
		"droprate": null,
		"type": "herbs",
		"img": "/img/rs3/grimy_marrentill.png",
		"game": "rs3",
		"boss": "Tormented Demon",
		"npc": "Tormented Demon"
	},
	{
		"title": "Grimy tarromin",
		"quantity": 6,
		"price": 33,
		"rarity": "Common",
		"droprate": null,
		"type": "herbs",
		"img": "/img/rs3/grimy_tarromin.png",
		"game": "rs3",
		"boss": "Tormented Demon",
		"npc": "Tormented Demon"
	},
	{
		"title": "Grimy harralander",
		"quantity": 6,
		"price": 95,
		"rarity": "Common",
		"droprate": null,
		"type": "herbs",
		"img": "/img/rs3/grimy_harralander.png",
		"game": "rs3",
		"boss": "Tormented Demon",
		"npc": "Tormented Demon"
	},
	{
		"title": "Grimy irit",
		"quantity": 6,
		"price": 2172,
		"rarity": "Common",
		"droprate": null,
		"type": "herbs",
		"img": "/img/rs3/grimy_irit.png",
		"game": "rs3",
		"boss": "Tormented Demon",
		"npc": "Tormented Demon"
	},
	{
		"title": "Grimy avantoe",
		"quantity": 6,
		"price": 4023,
		"rarity": "Common",
		"droprate": null,
		"type": "herbs",
		"img": "/img/rs3/grimy_avantoe.png",
		"game": "rs3",
		"boss": "Tormented Demon",
		"npc": "Tormented Demon"
	},
	{
		"title": "Grimy kwuarm",
		"quantity": 6,
		"price": 4903,
		"rarity": "Common",
		"droprate": null,
		"type": "herbs",
		"img": "/img/rs3/grimy_kwuarm.png",
		"game": "rs3",
		"boss": "Tormented Demon",
		"npc": "Tormented Demon"
	},
	{
		"title": "Grimy cadantine",
		"quantity": 6,
		"price": 3763,
		"rarity": "Common",
		"droprate": null,
		"type": "herbs",
		"img": "/img/rs3/grimy_cadantine.png",
		"game": "rs3",
		"boss": "Tormented Demon",
		"npc": "Tormented Demon"
	},
	{
		"title": "Grimy lantadyme",
		"quantity": 6,
		"price": 5898,
		"rarity": "Common",
		"droprate": null,
		"type": "herbs",
		"img": "/img/rs3/grimy_lantadyme.png",
		"game": "rs3",
		"boss": "Tormented Demon",
		"npc": "Tormented Demon"
	},
	{
		"title": "Grimy ranarr",
		"quantity": 6,
		"price": 2299,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "herbs",
		"img": "/img/rs3/grimy_ranarr.png",
		"game": "rs3",
		"boss": "Tormented Demon",
		"npc": "Tormented Demon"
	},
	{
		"title": "Grimy dwarf weed",
		"quantity": 6,
		"price": 6334,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "herbs",
		"img": "/img/rs3/grimy_dwarf_weed.png",
		"game": "rs3",
		"boss": "Tormented Demon",
		"npc": "Tormented Demon"
	},
	{
		"title": "Diamond",
		"quantity": 4,
		"price": 1846,
		"rarity": "Common",
		"droprate": null,
		"type": "Gems and Bars",
		"img": "/img/rs3/diamond.png",
		"game": "rs3",
		"boss": "Tormented Demon",
		"npc": "Tormented Demon"
	},
	{
		"title": "Adamant bar",
		"quantity": 4,
		"price": 3150,
		"rarity": "Common",
		"droprate": null,
		"type": "Gems and Bars",
		"img": "/img/rs3/adamant_bar.png",
		"game": "rs3",
		"boss": "Tormented Demon",
		"npc": "Tormented Demon"
	},
	{
		"title": "Death rune",
		"quantity": 30,
		"price": 351,
		"rarity": "Common",
		"droprate": null,
		"type": "Runes and Talismans",
		"img": "/img/rs3/death_rune.png",
		"game": "rs3",
		"boss": "Tormented Demon",
		"npc": "Tormented Demon"
	},
	{
		"title": "Law rune",
		"quantity": 35,
		"price": 232,
		"rarity": "Common",
		"droprate": null,
		"type": "Runes and Talismans",
		"img": "/img/rs3/law_rune.png",
		"game": "rs3",
		"boss": "Tormented Demon",
		"npc": "Tormented Demon"
	},
	{
		"title": "Fire talisman",
		"quantity": 4,
		"price": 2920,
		"rarity": "Common",
		"droprate": null,
		"type": "Runes and Talismans",
		"img": "/img/rs3/fire_talisman.png",
		"game": "rs3",
		"boss": "Tormented Demon",
		"npc": "Tormented Demon"
	},
	{
		"title": "Blood rune",
		"quantity": 25,
		"price": 456,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "Runes and Talismans",
		"img": "/img/rs3/blood_rune.png",
		"game": "rs3",
		"boss": "Tormented Demon",
		"npc": "Tormented Demon"
	},
	{
		"title": "Coins",
		"quantity": 9000,
		"price": 1,
		"rarity": "Common",
		"droprate": null,
		"type": "Other drops",
		"img": "/img/rs3/coins.png",
		"game": "rs3",
		"boss": "Tormented Demon",
		"npc": "Tormented Demon"
	},
	{
		"title": "Clue scroll (hard)",
		"quantity": 1,
		"price": null,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "Other drops",
		"img": "/img/rs3/clue_scroll_(hard).png",
		"game": "rs3",
		"boss": "Tormented Demon",
		"npc": "Tormented Demon"
	},
	{
		"title": "Ruined dragon armour slice",
		"quantity": 1,
		"price": 271267,
		"rarity": "Very rare",
		"droprate": null,
		"type": "Other drops",
		"img": "/img/rs3/ruined_dragon_armour_slice.png",
		"game": "rs3",
		"boss": "Tormented Demon",
		"npc": "Tormented Demon"
	},
	{
		"title": "Ruined dragon armour lump",
		"quantity": 1,
		"price": 299433,
		"rarity": "Very rare",
		"droprate": null,
		"type": "Other drops",
		"img": "/img/rs3/ruined_dragon_armour_lump.png",
		"game": "rs3",
		"boss": "Tormented Demon",
		"npc": "Tormented Demon"
	},
	{
		"title": "Ruined dragon armour shard",
		"quantity": 1,
		"price": 272400,
		"rarity": "Very rare",
		"droprate": null,
		"type": "Other drops",
		"img": "/img/rs3/ruined_dragon_armour_shard.png",
		"game": "rs3",
		"boss": "Tormented Demon",
		"npc": "Tormented Demon"
	},
	{
		"title": "Dragon limbs",
		"quantity": 1,
		"price": 9727128,
		"rarity": "rare",
		"droprate": null,
		"type": "Other drops",
		"img": "/img/rs3/dragon_limbs.png",
		"game": "rs3",
		"boss": "Tormented Demon",
		"npc": "Tormented Demon"
	},
	{
		"title": "Starved ancient effigy",
		"quantity": 1,
		"price": null,
		"rarity": "rare",
		"droprate": null,
		"type": "Other drops",
		"img": "/img/rs3/starved_ancient_effigy.png",
		"game": "rs3",
		"boss": "Tormented Demon",
		"npc": "Tormented Demon"
	},
	{
		"title": "Clue scroll (elite)",
		"quantity": 1,
		"price": null,
		"rarity": "Very rare",
		"droprate": null,
		"type": "Other drops",
		"img": "/img/rs3/clue_scroll_(elite).png",
		"game": "rs3",
		"boss": "Tormented Demon",
		"npc": "Tormented Demon"
	}
];