/*
* OSRS Venenatis drops list made by Mokuin.
*/

VenenatisDrops = [
	{
		"title": "Rune pickaxe",
		"quantity": 1,
		"price": 19627,
		"rarity": "Common",
		"droprate": null,
		"type": "weapons",
		"img": "/img/osrs/rune_pickaxe.png",
		"game": "osrs",
		"boss": "Venenatis",
		"npc": "Venenatis"
	},
	{
		"title": "Diamond bolts (e)",
		"quantity": 100,
		"price": 476,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "weapons",
		"img": "/img/osrs/diamond_bolts_e.png",
		"game": "osrs",
		"boss": "Venenatis",
		"npc": "Venenatis"
	},
	{
		"title": "Rune 2h sword",
		"quantity": 1,
		"price": 41593,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "weapons",
		"img": "/img/osrs/rune_2h_sword.png",
		"game": "osrs",
		"boss": "Venenatis",
		"npc": "Venenatis"
	},
	{
		"title": "Dragon pickaxe",
		"quantity": 1,
		"price": 1930220,
		"rarity": "Rare",
		"droprate": 256,
		"type": "weapons",
		"img": "/img/osrs/dragon_pickaxe.png",
		"game": "osrs",
		"boss": "Venenatis",
		"npc": "Venenatis"
	},
	{
		"title": "Dragon 2h sword",
		"quantity": 1,
		"price": 158534,
		"rarity": "Rare",
		"droprate": 256,
		"type": "weapons",
		"img": "/img/osrs/dragon_2h_sword.png",
		"game": "osrs",
		"boss": "Venenatis",
		"npc": "Venenatis"
	},
	{
		"title": "Treasonous ring",
		"quantity": 1,
		"price": 2985851,
		"rarity": "Rare",
		"droprate": 512,
		"type": "armour",
		"img": "/img/osrs/treasonous_ring.png",
		"game": "osrs",
		"boss": "Venenatis",
		"npc": "Venenatis"
	},
	{
		"title": "Death rune",
		"quantity": 300,
		"price": 221,
		"rarity": "Common",
		"droprate": null,
		"type": "runes",
		"img": "/img/osrs/death_rune.png",
		"game": "osrs",
		"boss": "Venenatis",
		"npc": "Venenatis"
	},
	{
		"title": "Chaos rune",
		"quantity": 400,
		"price": 100,
		"rarity": "Common",
		"droprate": null,
		"type": "runes",
		"img": "/img/osrs/chaos_rune.png",
		"game": "osrs",
		"boss": "Venenatis",
		"npc": "Venenatis"
	},
	{
		"title": "Blood rune",
		"quantity": 200,
		"price": 316,
		"rarity": "Common",
		"droprate": null,
		"type": "runes",
		"img": "/img/osrs/blood_rune.png",
		"game": "osrs",
		"boss": "Venenatis",
		"npc": "Venenatis"
	},
	{
		"title": "Yew seed",
		"quantity": 1,
		"price": 76784,
		"rarity": "Rare",
		"droprate": null,
		"type": "seeds",
		"img": "/img/osrs/yew_seed.png",
		"game": "osrs",
		"boss": "Venenatis",
		"npc": "Venenatis"
	},
	{
		"title": "Magic seed",
		"quantity": 1,
		"price": 84581,
		"rarity": "Rare",
		"droprate": null,
		"type": "seeds",
		"img": "/img/osrs/magic_seed.png",
		"game": "osrs",
		"boss": "Venenatis",
		"npc": "Venenatis"
	},
	{
		"title": "Palm tree seed",
		"quantity": 1,
		"price": 21058,
		"rarity": "Rare",
		"droprate": null,
		"type": "seeds",
		"img": "/img/osrs/palm_tree_seed.png",
		"game": "osrs",
		"boss": "Venenatis",
		"npc": "Venenatis"
	},
	{
		"title": "Coins",
		"quantity": 18000,
		"price": 1,
		"rarity": "Common",
		"droprate": null,
		"type": "Others",
		"img": "/img/osrs/coins.png",
		"game": "osrs",
		"boss": "Venenatis",
		"npc": "Venenatis"
	},
	{
		"title": "Unicorn horn",
		"quantity": 100,
		"price": 732,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "Others",
		"img": "/img/osrs/unicorn_horn.png",
		"game": "osrs",
		"boss": "Venenatis",
		"npc": "Venenatis"
	},
	{
		"title": "8 Dark crab + 3 Super restore (4)",
		"quantity": 1,
		"price": 37982,
		"rarity": "Common",
		"droprate": null,
		"type": "Others",
		"img": "/img/osrs/callisto_potion.png",
		"game": "osrs",
		"boss": "Venenatis",
		"npc": "Venenatis"
	},
	{
		"title": "20 Uncut ruby + 10 Uncut diamond",
		"quantity": 1,
		"price": 62460,
		"rarity": "Common",
		"droprate": null,
		"type": "Others",
		"img": "/img/osrs/callisto_gems.png",
		"game": "osrs",
		"boss": "Venenatis",
		"npc": "Venenatis"
	},
	{
		"title": "Red spiders' eggs",
		"quantity": 500,
		"price": 61,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "Others",
		"img": "/img/osrs/red_spiders_eggs.png",
		"game": "osrs",
		"boss": "Venenatis",
		"npc": "Venenatis"
	},
	{
		"title": "Limpwurt root",
		"quantity": 50,
		"price": 1090,
		"rarity": "Rare",
		"droprate": null,
		"type": "Others",
		"img": "/img/osrs/limpwurt_root.png",
		"game": "osrs",
		"boss": "Venenatis",
		"npc": "Venenatis"
	},
	{
		"title": "Grimy snapdragon",
		"quantity": 100,
		"price": 5917,
		"rarity": "Rare",
		"droprate": 128,
		"type": "Others",
		"img": "/img/osrs/grimy_snapdragon.png",
		"game": "osrs",
		"boss": "Venenatis",
		"npc": "Venenatis"
	},
	{
		"title": "Gold ore",
		"quantity": 300,
		"price": 268,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "Others",
		"img": "/img/osrs/gold_ore.png",
		"game": "osrs",
		"boss": "Venenatis",
		"npc": "Venenatis"
	},
	{
		"title": "Onyx bolt tips",
		"quantity": 60,
		"price": 8415,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "Others",
		"img": "/img/osrs/onyx_bolt_tips.png",
		"game": "osrs",
		"boss": "Venenatis",
		"npc": "Venenatis"
	},
	{
		"title": "Cannonball",
		"quantity": 250,
		"price": 186,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "Others",
		"img": "/img/osrs/cannonball.png",
		"game": "osrs",
		"boss": "Venenatis",
		"npc": "Venenatis"
	},
	{
		"title": "Magic logs",
		"quantity": 100,
		"price": 1228,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "Others",
		"img": "/img/osrs/magic_logs.png",
		"game": "osrs",
		"boss": "Venenatis",
		"npc": "Venenatis"
	},
	{
		"title": "Mysterious emblem",
		"quantity": 1,
		"price": null,
		"rarity": "Uncommon",
		"droprate": 12,
		"type": "Others",
		"img": "/img/osrs/mysterious_emblem.png",
		"game": "osrs",
		"boss": "Venenatis",
		"npc": "Venenatis"
	},
	{
		"title": "Uncut dragonstone",
		"quantity": 1,
		"price": 17401,
		"rarity": "Rare",
		"droprate": null,
		"type": "Others",
		"img": "/img/osrs/uncut_dragonstone.png",
		"game": "osrs",
		"boss": "Venenatis",
		"npc": "Venenatis"
	},
	{
		"title": "Dark fishing bait",
		"quantity": 375,
		"price": 53,
		"rarity": "Rare",
		"droprate": null,
		"type": "Others",
		"img": "/img/osrs/dark_fishing_bait.png",
		"game": "osrs",
		"boss": "Venenatis",
		"npc": "Venenatis"
	},
	{
		"title": "Antipoison++ (4)",
		"quantity": 10,
		"price": null,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "Others",
		"img": "/img/osrs/antipoison_pp_4.png",
		"game": "osrs",
		"boss": "Venenatis",
		"npc": "Venenatis"
	},
	{
		"title": "Clue scroll (elite)",
		"quantity": 1,
		"price": null,
		"rarity": "Rare",
		"droprate": 100,
		"type": "Others",
		"img": "/img/osrs/clue_scroll_elite.png",
		"game": "osrs",
		"boss": "Venenatis",
		"npc": "Venenatis"
	},
	{
		"title": "Venenatis spiderling",
		"quantity": 1,
		"price": null,
		"rarity": "Very rare",
		"droprate": 2000,
		"type": "Others",
		"img": "/img/osrs/venenatis_spiderling.png",
		"game": "osrs",
		"boss": "Venenatis",
		"npc": "Venenatis"
	}
];

