/*
* OSRS Vet'ion drops list made by Mokuin.
*/

VetionDrops = [
	{
		"title": "Rune pickaxe",
		"quantity": 1,
		"price": 19627,
		"rarity": "Common",
		"droprate": null,
		"type": "weapons",
		"img": "/img/osrs/rune_pickaxe.png",
		"game": "osrs",
		"boss": "Vet'ion",
		"npc": "Vet'ion"
	},
	{
		"title": "Ancient staff",
		"quantity": 1,
		"price": 87139,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "weapons",
		"img": "/img/osrs/ancient_staff.png",
		"game": "osrs",
		"boss": "Vet'ion",
		"npc": "Vet'ion"
	},
	{
		"title": "Rune 2h sword",
		"quantity": 1,
		"price": 41593,
		"rarity": "Rare",
		"droprate": null,
		"type": "weapons",
		"img": "/img/osrs/rune_2h_sword.png",
		"game": "osrs",
		"boss": "Vet'ion",
		"npc": "Vet'ion"
	},
	{
		"title": "Dragon pickaxe",
		"quantity": 1,
		"price": 1930220,
		"rarity": "Rare",
		"droprate": 256,
		"type": "weapons",
		"img": "/img/osrs/dragon_pickaxe.png",
		"game": "osrs",
		"boss": "Vet'ion",
		"npc": "Vet'ion"
	},
	{
		"title": "Dragon 2h sword",
		"quantity": 1,
		"price": 158534,
		"rarity": "Rare",
		"droprate": 256,
		"type": "weapons",
		"img": "/img/osrs/dragon_2h_sword.png",
		"game": "osrs",
		"boss": "Vet'ion",
		"npc": "Vet'ion"
	},
	{
		"title": "Ring of the gods",
		"quantity": 1,
		"price": 7378435,
		"rarity": "Rare",
		"droprate": 512,
		"type": "armour",
		"img": "/img/osrs/ring_of_the_gods.png",
		"game": "osrs",
		"boss": "Vet'ion",
		"npc": "Vet'ion"
	},
	{
		"title": "Death rune",
		"quantity": 300,
		"price": 221,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "runes",
		"img": "/img/osrs/death_rune.png",
		"game": "osrs",
		"boss": "Vet'ion",
		"npc": "Vet'ion"
	},
	{
		"title": "Chaos rune",
		"quantity": 400,
		"price": 100,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "runes",
		"img": "/img/osrs/chaos_rune.png",
		"game": "osrs",
		"boss": "Vet'ion",
		"npc": "Vet'ion"
	},
	{
		"title": "Blood rune",
		"quantity": 200,
		"price": 316,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "runes",
		"img": "/img/osrs/blood_rune.png",
		"game": "osrs",
		"boss": "Vet'ion",
		"npc": "Vet'ion"
	},
	{
		"title": "Yew seed",
		"quantity": 1,
		"price": 76784,
		"rarity": "Rare",
		"droprate": null,
		"type": "seeds",
		"img": "/img/osrs/yew_seed.png",
		"game": "osrs",
		"boss": "Vet'ion",
		"npc": "Vet'ion"
	},
	{
		"title": "Magic seed",
		"quantity": 1,
		"price": 84581,
		"rarity": "Rare",
		"droprate": null,
		"type": "seeds",
		"img": "/img/osrs/magic_seed.png",
		"game": "osrs",
		"boss": "Vet'ion",
		"npc": "Vet'ion"
	},
	{
		"title": "Palm tree seed",
		"quantity": 1,
		"price": 21058,
		"rarity": "Rare",
		"droprate": null,
		"type": "seeds",
		"img": "/img/osrs/palm_tree_seed.png",
		"game": "osrs",
		"boss": "Vet'ion",
		"npc": "Vet'ion"
	},
	{
		"title": "Coins",
		"quantity": 18000,
		"price": 1,
		"rarity": "Common",
		"droprate": null,
		"type": "Others",
		"img": "/img/osrs/coins.png",
		"game": "osrs",
		"boss": "Vet'ion",
		"npc": "Vet'ion"
	},
	{
		"title": "Sanfew serum (4)",
		"quantity": 10,
		"price": 12251,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "Others",
		"img": "/img/osrs/sanfew_serum_4.png",
		"game": "osrs",
		"boss": "Vet'ion",
		"npc": "Vet'ion"
	},
	{
		"title": "8 Dark crab + 3 Super restore (4)",
		"quantity": 1,
		"price": 37982,
		"rarity": "Common",
		"droprate": null,
		"type": "Others",
		"img": "/img/osrs/callisto_potion.png",
		"game": "osrs",
		"boss": "Vet'ion",
		"npc": "Vet'ion"
	},

	{
		"title": "20 Uncut ruby + 10 Uncut diamond",
		"quantity": 1,
		"price": 62460,
		"rarity": "Common",
		"droprate": null,
		"type": "Others",
		"img": "/img/osrs/callisto_gems.png",
		"game": "osrs",
		"boss": "Vet'ion",
		"npc": "Vet'ion"
	},
	{
		"title": "Ogre coffin key",
		"quantity": 10,
		"price": 44915,
		"rarity": "Common",
		"droprate": null,
		"type": "Others",
		"img": "/img/osrs/ogre_coffin_key.png",
		"game": "osrs",
		"boss": "Vet'ion",
		"npc": "Vet'ion"
	},
	{
		"title": "Limpwurt root",
		"quantity": 50,
		"price": 1090,
		"rarity": "Common",
		"droprate": null,
		"type": "Others",
		"img": "/img/osrs/limpwurt_root.png",
		"game": "osrs",
		"boss": "Vet'ion",
		"npc": "Vet'ion"
	},
	{
		"title": "Supercompost",
		"quantity": 100,
		"price": 705,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "Others",
		"img": "/img/osrs/supercompost.png",
		"game": "osrs",
		"boss": "Vet'ion",
		"npc": "Vet'ion"
	},
	{
		"title": "Gold ore",
		"quantity": 300,
		"price": 268,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "Others",
		"img": "/img/osrs/gold_ore.png",
		"game": "osrs",
		"boss": "Vet'ion",
		"npc": "Vet'ion"
	},
	{
		"title": "Dragon bones",
		"quantity": 100,
		"price": 2545,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "Others",
		"img": "/img/osrs/dragon_bones.png",
		"game": "osrs",
		"boss": "Vet'ion",
		"npc": "Vet'ion"
	},
	{
		"title": "Cannonball",
		"quantity": 250,
		"price": 186,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "Others",
		"img": "/img/osrs/cannonball.png",
		"game": "osrs",
		"boss": "Vet'ion",
		"npc": "Vet'ion"
	},
	{
		"title": "Magic logs",
		"quantity": 100,
		"price": 1228,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "Others",
		"img": "/img/osrs/magic_logs.png",
		"game": "osrs",
		"boss": "Vet'ion",
		"npc": "Vet'ion"
	},
	{
		"title": "Mysterious emblem",
		"quantity": 1,
		"price": null,
		"rarity": "Uncommon",
		"droprate": 12,
		"type": "Others",
		"img": "/img/osrs/mysterious_emblem.png",
		"game": "osrs",
		"boss": "Vet'ion",
		"npc": "Vet'ion"
	},
	{
		"title": "Uncut dragonstone",
		"quantity": 1,
		"price": 17401,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "Others",
		"img": "/img/osrs/uncut_dragonstone.png",
		"game": "osrs",
		"boss": "Vet'ion",
		"npc": "Vet'ion"
	},
	{
		"title": "Grimy ranarr weed",
		"quantity": 100,
		"price": 5628,
		"rarity": "Rare",
		"droprate": null,
		"type": "Others",
		"img": "/img/osrs/grimy_ranarr_weed.png",
		"game": "osrs",
		"boss": "Vet'ion",
		"npc": "Vet'ion"
	},
	{
		"title": "Oak plank",
		"quantity": 300,
		"price": 435,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "Others",
		"img": "/img/osrs/oak_plank.png",
		"game": "osrs",
		"boss": "Vet'ion",
		"npc": "Vet'ion"
	},
	{
		"title": "Mort myre fungus",
		"quantity": 200,
		"price": 120,
		"rarity": "Rare",
		"droprate": null,
		"type": "Others",
		"img": "/img/osrs/mort_myre_fungus.png",
		"game": "osrs",
		"boss": "Vet'ion",
		"npc": "Vet'ion"
	},
	{
		"title": "Dark fishing bait",
		"quantity": 375,
		"price": 53,
		"rarity": "Rare",
		"droprate": null,
		"type": "Others",
		"img": "/img/osrs/dark_fishing_bait.png",
		"game": "osrs",
		"boss": "Vet'ion",
		"npc": "Vet'ion"
	},
	{
		"title": "Clue scroll (elite)",
		"quantity": 1,
		"price": null,
		"rarity": "Rare",
		"droprate": 100,
		"type": "Others",
		"img": "/img/osrs/clue_scroll_elite.png",
		"game": "osrs",
		"boss": "Vet'ion",
		"npc": "Vet'ion"
	},
	{
		"title": "Vet'ion jr.",
		"quantity": 1,
		"price": null,
		"rarity": "Very rare",
		"droprate": 2000,
		"type": "Others",
		"img": "/img/osrs/vetion_jr.png",
		"game": "osrs",
		"boss": "Vet'ion",
		"npc": "Vet'ion"
	}
];

