/*
* R3 Zamorak drops list made by Mokuin.
*/

ZamorakDropsRs3 = [
	{
		"title": "Rune scimitar",
		"quantity": 1,
		"price": 14888,
		"rarity": "Common",
		"droprate": null,
		"type": "weapons",
		"img": "/img/rs3/rune_scimitar.png",
		"game": "rs3",
		"boss": "Zamorak",
		"npc": "K'ril Tsutsaroth"
	},
	{
		"title": "Zamorakian spear",
		"quantity": 1,
		"price": 681964,
		"rarity": "Rare",
		"droprate": 72,
		"type": "weapons",
		"img": "/img/rs3/zamorakian_spear.png",
		"game": "rs3",
		"boss": "Zamorak",
		"npc": "K'ril Tsutsaroth"
	},
	{
		"title": "Steam battlestaff",
		"quantity": 1,
		"price": 15603,
		"rarity": "Rare",
		"droprate": null,
		"type": "weapons",
		"img": "/img/rs3/steam_battlestaff.png",
		"game": "rs3",
		"boss": "Zamorak",
		"npc": "K'ril Tsutsaroth"
	},
	{
		"title": "Adamant platebody",
		"quantity": 1,
		"price": 9443,
		"rarity": "Common",
		"droprate": null,
		"type": "Armour",
		"img": "/img/rs3/adamant_platebody.png",
		"game": "rs3",
		"boss": "Zamorak",
		"npc": "K'ril Tsutsaroth"
	},
	{
		"title": "Rune platelegs",
		"quantity": 1,
		"price": 37333,
		"rarity": "Common",
		"droprate": null,
		"type": "Armour",
		"img": "/img/rs3/rune_platelegs.png",
		"game": "rs3",
		"boss": "Zamorak",
		"npc": "K'ril Tsutsaroth"
	},
	{
		"title": "Hood of subjugation",
		"quantity": 1,
		"price": 130283,
		"rarity": "Rare",
		"droprate": null,
		"type": "Armour",
		"img": "/img/rs3/hood_of_subjugation.png",
		"game": "rs3",
		"boss": "Zamorak",
		"npc": "K'ril Tsutsaroth"
	},
	{
		"title": "Garb of subjugation",
		"quantity": 1,
		"price": 3059759,
		"rarity": "Rare",
		"droprate": null,
		"type": "Armour",
		"img": "/img/rs3/garb_of_subjugation.png",
		"game": "rs3",
		"boss": "Zamorak",
		"npc": "K'ril Tsutsaroth"
	},
	{
		"title": "Boots of subjugation",
		"quantity": 1,
		"price": 808024,
		"rarity": "Rare",
		"droprate": null,
		"type": "Armour",
		"img": "/img/rs3/boots_of_subjugation.png",
		"game": "rs3",
		"boss": "Zamorak",
		"npc": "K'ril Tsutsaroth"
	},
	{
		"title": "Gloves of subjugation",
		"quantity": 1,
		"price": 461685,
		"rarity": "Rare",
		"droprate": null,
		"type": "Armour",
		"img": "/img/rs3/gloves_of_subjugation.png",
		"game": "rs3",
		"boss": "Zamorak",
		"npc": "K'ril Tsutsaroth"
	},
	{
		"title": "Gown of subjugation",
		"quantity": 1,
		"price": 3142258,
		"rarity": "Rare",
		"droprate": null,
		"type": "Armour",
		"img": "/img/rs3/gown_of_subjugation.png",
		"game": "rs3",
		"boss": "Zamorak",
		"npc": "K'ril Tsutsaroth"
	},
	{
		"title": "Ward of subjugation",
		"quantity": 1,
		"price": 24958,
		"rarity": "Rare",
		"droprate": null,
		"type": "Armour",
		"img": "/img/rs3/ward_of_subjugation.png",
		"game": "rs3",
		"boss": "Zamorak",
		"npc": "K'ril Tsutsaroth"
	},
	{
		"title": "Warpriest of Zamorak helm",
		"quantity": 1,
		"price": null,
		"rarity": "Varies",
		"droprate": null,
		"type": "Armour",
		"img": "/img/rs3/warpriest_of_zamorak_helm.png",
		"game": "rs3",
		"boss": "Zamorak",
		"npc": "K'ril Tsutsaroth"
	},
	{
		"title": "Warpriest of Zamorak cuirass",
		"quantity": 1,
		"price": null,
		"rarity": "Varies",
		"droprate": null,
		"type": "Armour",
		"img": "/img/rs3/warpriest_of_zamorak_cuirass.png",
		"game": "rs3",
		"boss": "Zamorak",
		"npc": "K'ril Tsutsaroth"
	},
	{
		"title": "Warpriest of Zamorak greaves",
		"quantity": 1,
		"price": null,
		"rarity": "Varies",
		"droprate": null,
		"type": "Armour",
		"img": "/img/rs3/warpriest_of_zamorak_greaves.png",
		"game": "rs3",
		"boss": "Zamorak",
		"npc": "K'ril Tsutsaroth"
	},
	{
		"title": "Warpriest of Zamorak gauntlets",
		"quantity": 1,
		"price": null,
		"rarity": "Varies",
		"droprate": null,
		"type": "Armour",
		"img": "/img/rs3/warpriest_of_zamorak_gauntlets.png",
		"game": "rs3",
		"boss": "Zamorak",
		"npc": "K'ril Tsutsaroth"
	},
	{
		"title": "Warpriest of Zamorak boots",
		"quantity": 1,
		"price": null,
		"rarity": "Varies",
		"droprate": null,
		"type": "Armour",
		"img": "/img/rs3/warpriest_of_zamorak_boots.png",
		"game": "rs3",
		"boss": "Zamorak",
		"npc": "K'ril Tsutsaroth"
	},
	{
		"title": "Warpriest of Zamorak cape",
		"quantity": 1,
		"price": null,
		"rarity": "Varies",
		"droprate": null,
		"type": "Armour",
		"img": "/img/rs3/warpriest_of_zamorak_cape.png",
		"game": "rs3",
		"boss": "Zamorak",
		"npc": "K'ril Tsutsaroth"
	},
	{
		"title": "Super attack (3)",
		"quantity": 3,
		"price": 1434,
		"rarity": "Common",
		"droprate": null,
		"type": "Potion",
		"img": "/img/rs3/super_attack_3.png",
		"game": "rs3",
		"boss": "Zamorak",
		"npc": "K'ril Tsutsaroth"
	},
	{
		"title": "Super strength (3)",
		"quantity": 3,
		"price": 4709,
		"rarity": "Common",
		"droprate": null,
		"type": "Potion",
		"img": "/img/rs3/super_strength_3.png",
		"game": "rs3",
		"boss": "Zamorak",
		"npc": "K'ril Tsutsaroth"
	},
	{
		"title": "Super restore (3)",
		"quantity": 3,
		"price": 2504,
		"rarity": "Common",
		"droprate": null,
		"type": "Potion",
		"img": "/img/rs3/super_restore_3.png",
		"game": "rs3",
		"boss": "Zamorak",
		"npc": "K'ril Tsutsaroth"
	},
	{
		"title": "Zamorak brew (3)",
		"quantity": 3,
		"price": 294,
		"rarity": "Common",
		"droprate": null,
		"type": "Potion",
		"img": "/img/rs3/zamorak_brew_3.png",
		"game": "rs3",
		"boss": "Zamorak",
		"npc": "K'ril Tsutsaroth"
	},
	{
		"title": "Coins",
		"quantity": 20000,
		"price": 1,
		"rarity": "Common",
		"droprate": null,
		"type": "Other",
		"img": "/img/rs3/coins.png",
		"game": "rs3",
		"boss": "Zamorak",
		"npc": "K'ril Tsutsaroth"
	},
	{
		"title": "Lantadyme seed",
		"quantity": 3,
		"price": 9786,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "Other",
		"img": "/img/rs3/lantadyme_seed.png",
		"game": "rs3",
		"boss": "Zamorak",
		"npc": "K'ril Tsutsaroth"
	},
	{
		"title": "Grimy lantadyme",
		"quantity": 10,
		"price": 5898,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "Other",
		"img": "/img/rs3/grimy_lantadyme.png",
		"game": "rs3",
		"boss": "Zamorak",
		"npc": "K'ril Tsutsaroth"
	},
	{
		"title": "Runite ore",
		"quantity": 2,
		"price": 11053,
		"rarity": "Uncommon",
		"droprate": null,
		"type": "Other",
		"img": "/img/rs3/runite_ore.png",
		"game": "rs3",
		"boss": "Zamorak",
		"npc": "K'ril Tsutsaroth"
	},
	{
		"title": "Starved ancient effigy",
		"quantity": 1,
		"price": null,
		"rarity": "Rare",
		"droprate": null,
		"type": "Other",
		"img": "/img/rs3/starved_ancient_effigy.png",
		"game": "rs3",
		"boss": "Zamorak",
		"npc": "K'ril Tsutsaroth"
	},
	{
		"title": "Godsword shard 1",
		"quantity": 1,
		"price": 147141,
		"rarity": "Rare",
		"droprate": "477",
		"type": "Other",
		"img": "/img/rs3/godsword_shard_1.png",
		"game": "rs3",
		"boss": "Zamorak",
		"npc": "K'ril Tsutsaroth"
	},
	{
		"title": "Godsword shard 2",
		"quantity": 1,
		"price": 146960,
		"rarity": "Rare",
		"droprate": "500",
		"type": "Other",
		"img": "/img/rs3/godsword_shard_2.png",
		"game": "rs3",
		"boss": "Zamorak",
		"npc": "K'ril Tsutsaroth"
	},
	{
		"title": "Godsword shard 3",
		"quantity": 1,
		"price": 147075,
		"rarity": "Rare",
		"droprate": 387,
		"type": "Other",
		"img": "/img/rs3/godsword_shard_3.png",
		"game": "rs3",
		"boss": "Zamorak",
		"npc": "K'ril Tsutsaroth"
	},
	{
		"title": "Zamorak hilt",
		"quantity": 1,
		"price": 297053,
		"rarity": "Rare",
		"droprate": 289,
		"type": "Other",
		"img": "/img/rs3/zamorak_hilt.png",
		"game": "rs3",
		"boss": "Zamorak",
		"npc": "K'ril Tsutsaroth"
	},
	{
		"title": "Razulei's tale",
		"quantity": 1,
		"price": null,
		"rarity": "Rare",
		"droprate": null,
		"type": "Other",
		"img": "/img/rs3/razuleis_tale.png",
		"game": "rs3",
		"boss": "Zamorak",
		"npc": "K'ril Tsutsaroth"
	},
	{
		"title": "Spirit sapphire",
		"quantity": 1,
		"price": null,
		"rarity": "Rare",
		"droprate": null,
		"type": "Other",
		"img": "/img/rs3/spirit_sapphire.png",
		"game": "rs3",
		"boss": "Zamorak",
		"npc": "K'ril Tsutsaroth"
	},
	{
		"title": "Spirit emerald",
		"quantity": 1,
		"price": null,
		"rarity": "Rare",
		"droprate": null,
		"type": "Other",
		"img": "/img/rs3/spirit_emerald.png",
		"game": "rs3",
		"boss": "Zamorak",
		"npc": "K'ril Tsutsaroth"
	},
	{
		"title": "Spirit ruby",
		"quantity": 1,
		"price": null,
		"rarity": "Rare",
		"droprate": null,
		"type": "Other",
		"img": "/img/rs3/spirit_ruby.png",
		"game": "rs3",
		"boss": "Zamorak",
		"npc": "K'ril Tsutsaroth"
	},
	{
		"title": "Clue scroll (hard)",
		"quantity": 1,
		"price": null,
		"rarity": "Rare",
		"droprate": null,
		"type": "Other",
		"img": "/img/rs3/clue_scroll_hard.png",
		"game": "rs3",
		"boss": "Zamorak",
		"npc": "K'ril Tsutsaroth"
	},
	{
		"title": "Clue scroll (elite)",
		"quantity": 1,
		"price": null,
		"rarity": "Rare",
		"droprate": null,
		"type": "Other",
		"img": "/img/rs3/clue_scroll_elite.png",
		"game": "rs3",
		"boss": "Zamorak",
		"npc": "K'ril Tsutsaroth"
	},
	{
		"title": "Severed hoof",
		"quantity": 1,
		"price": null,
		"rarity": "Very rare",
		"droprate": 5000,
		"type": "Other",
		"img": "/img/rs3/severed_hoof.png",
		"game": "rs3",
		"boss": "Zamorak",
		"npc": "K'ril Tsutsaroth"
	}	
];

