/*
* Zulrah drops list made by Questalion.
*/

ZulrahDrops = [
	{
		"title": "Zulrah's scales",
		"quantity": 200,
		"price": 54,
		"rarity": "Always",
		"droprate": "",
		"type": "100% drops",
		"img": "/img/osrs/zulrahs_scales.png",
		"game": "osrs",
		"boss": "Zulrah",
		"npc": "Zulrah"
	},
	{
		"title": "Tanzanite fang",
		"quantity": 1,
		"price": 16000000,
		"rarity": "Rare",
		"droprate": "1/512",
		"type": "Unique drop table",
		"img": "/img/osrs/tanzanite_fang.png",
		"game": "osrs",
		"boss": "Zulrah",
		"npc": "Zulrah"
	},
	{
		"title": "Magic fang",
		"quantity": 1,
		"price": 5000000,
		"rarity": "Rare",
		"droprate": "1/512",
		"type": "Unique drop table",
		"img": "/img/osrs/magic_fang.png",
		"game": "osrs",
		"boss": "Zulrah",
		"npc": "Zulrah"
	},
	{
		"title": "Uncut onyx",
		"quantity": 1,
		"price": 2500000,
		"rarity": "Rare",
		"droprate": "1/512",
		"type": "Unique drop table",
		"img": "/img/osrs/uncut_onyx.png",
		"game": "osrs",
		"boss": "Zulrah",
		"npc": "Zulrah"
	},
	{
		"title": "Dragon med helm",
		"quantity": 1,
		"price": 20000,
		"rarity": "Uncommon",
		"droprate": "",
		"type": "Armour and weapons",
		"img": "/img/osrs/dragon_med_helm.png",
		"game": "osrs",
		"boss": "Zulrah",
		"npc": "Zulrah"
	},
	{
		"title": "Dragon halberd",
		"quantity": 1,
		"price": 170000,
		"rarity": "Rare",
		"droprate": "",
		"type": "Armour and weapons",
		"img": "/img/osrs/dragon_halberd.png",
		"game": "osrs",
		"boss": "Zulrah",
		"npc": "Zulrah"
	},
	{
		"title": "Law rune",
		"quantity": 200,
		"price": 260,
		"rarity": "Common",
		"droprate": "",
		"type": "Runes",
		"img": "/img/osrs/law_rune.png",
		"game": "osrs",
		"boss": "Zulrah",
		"npc": "Zulrah"
	},
	{
		"title": "Death rune",
		"quantity": 300,
		"price": 280,
		"rarity": "Uncommon",
		"droprate": "",
		"type": "Runes",
		"img": "/img/osrs/death_rune.png",
		"game": "osrs",
		"boss": "Zulrah",
		"npc": "Zulrah"
	},
	{
		"title": "Chaos rune",
		"quantity": 500,
		"price": 110,
		"rarity": "Uncommon",
		"droprate": "",
		"type": "Runes",
		"img": "/img/osrs/chaos_rune.png",
		"game": "osrs",
		"boss": "Zulrah",
		"npc": "Zulrah"
	},
	{
		"title": "Pure essence",
		"quantity": 1500,
		"price": 16,
		"rarity": "Uncommon",
		"droprate": "",
		"type": "Runes",
		"img": "/img/osrs/pure_essence.png",
		"game": "osrs",
		"boss": "Zulrah",
		"npc": "Zulrah"
	},
	{
		"title": "Toadflax",
		"quantity": 20,
		"price": 1100,
		"rarity": "Rare",
		"droprate": "",
		"type": "Herbs",
		"img": "/img/osrs/toadflax.png",
		"game": "osrs",
		"boss": "Zulrah",
		"npc": "Zulrah"
	},
	{
		"title": "Snapdragon",
		"quantity": 20,
		"price": 7000,
		"rarity": "Rare",
		"droprate": "",
		"type": "Herbs",
		"img": "/img/osrs/snapdragon.png",
		"game": "osrs",
		"boss": "Zulrah",
		"npc": "Zulrah"
	},
	{
		"title": "Dwarf weed",
		"quantity": 20,
		"price": 2800,
		"rarity": "Rare",
		"droprate": "",
		"type": "Herbs",
		"img": "/img/osrs/dwarf_weed.png",
		"game": "osrs",
		"boss": "Zulrah",
		"npc": "Zulrah"
	},
	{
		"title": "Torstol",
		"quantity": 20,
		"price": 9000,
		"rarity": "Rare",
		"droprate": "",
		"type": "Herbs",
		"img": "/img/osrs/torstol.png",
		"game": "osrs",
		"boss": "Zulrah",
		"npc": "Zulrah"
	},
	{
		"title": "Flax",
		"quantity": 1000,
		"price": 25,
		"rarity": "Common",
		"droprate": "",
		"type": "Materials",
		"img": "/img/osrs/flax.png",
		"game": "osrs",
		"boss": "Zulrah",
		"npc": "Zulrah"
	},
	{
		"title": "Snakeskin",
		"quantity": 35,
		"price": 300,
		"rarity": "Common",
		"droprate": "",
		"type": "Materials",
		"img": "/img/osrs/snakeskin.png",
		"game": "osrs",
		"boss": "Zulrah",
		"npc": "Zulrah"
	},
	{
		"title": "Dragon bolt tips",
		"quantity": 12,
		"price": 1000,
		"rarity": "Common",
		"droprate": "",
		"type": "Materials",
		"img": "/img/osrs/dragon_bolt_tips.png",
		"game": "osrs",
		"boss": "Zulrah",
		"npc": "Zulrah"
	},
	{
		"title": "Magic logs",
		"quantity": 100,
		"price": 1150,
		"rarity": "Common",
		"droprate": "",
		"type": "Materials",
		"img": "/img/osrs/magic_logs.png",
		"game": "osrs",
		"boss": "Zulrah",
		"npc": "Zulrah"
	},
	{
		"title": "Coal",
		"quantity": 300,
		"price": 125,
		"rarity": "Uncommon",
		"droprate": "",
		"type": "Materials",
		"img": "/img/osrs/coal.png",
		"game": "osrs",
		"boss": "Zulrah",
		"npc": "Zulrah"
	},
	{
		"title": "Runite ore",
		"quantity": 10,
		"price": 11250,
		"rarity": "Uncommon",
		"droprate": "",
		"type": "Materials",
		"img": "/img/osrs/runite_ore.png",
		"game": "osrs",
		"boss": "Zulrah",
		"npc": "Zulrah"
	},
	{
		"title": "Magic seed",
		"quantity": 1,
		"price": 64500,
		"rarity": "Uncommon",
		"droprate": "",
		"type": "Seeds",
		"img": "/img/osrs/magic_seed.png",
		"game": "osrs",
		"boss": "Zulrah",
		"npc": "Zulrah"
	},
	{
		"title": "Calquat tree seed",
		"quantity": 2,
		"price": 5000,
		"rarity": "Uncommon",
		"droprate": "",
		"type": "Seeds",
		"img": "/img/osrs/calquat_tree_seed.png",
		"game": "osrs",
		"boss": "Zulrah",
		"npc": "Zulrah"
	},
	{
		"title": "Papaya tree seed",
		"quantity": 2,
		"price": 17000,
		"rarity": "Uncommon",
		"droprate": "",
		"type": "Seeds",
		"img": "/img/osrs/papaya_tree_seed.png",
		"game": "osrs",
		"boss": "Zulrah",
		"npc": "Zulrah"
	},
	{
		"title": "Palm tree seed",
		"quantity": 1,
		"price": 45000,
		"rarity": "Uncommon",
		"droprate": "",
		"type": "Seeds",
		"img": "/img/osrs/palm_tree_seed.png",
		"game": "osrs",
		"boss": "Zulrah",
		"npc": "Zulrah"
	},
	{
		"title": "Toadflax seed",
		"quantity": 2,
		"price": 1200,
		"rarity": "Rare",
		"droprate": "",
		"type": "Seeds",
		"img": "/img/osrs/herb_seed.png",
		"game": "osrs",
		"boss": "Zulrah",
		"npc": "Zulrah"
	},
	{
		"title": "Snapdragon seed",
		"quantity": 2,
		"price": 25000,
		"rarity": "Rare",
		"droprate": "",
		"type": "Seeds",
		"img": "/img/osrs/herb_seed.png",
		"game": "osrs",
		"boss": "Zulrah",
		"npc": "Zulrah"
	},
	{
		"title": "Dwarf weed seed",
		"quantity": 2,
		"price": 1200,
		"rarity": "Rare",
		"droprate": "",
		"type": "Seeds",
		"img": "/img/osrs/herb_seed.png",
		"game": "osrs",
		"boss": "Zulrah",
		"npc": "Zulrah"
	},
	{
		"title": "Torstol seed",
		"quantity": 2,
		"price": 50000,
		"rarity": "Rare",
		"droprate": "",
		"type": "Seeds",
		"img": "/img/osrs/herb_seed.png",
		"game": "osrs",
		"boss": "Zulrah",
		"npc": "Zulrah"
	},
	{
		"title": "Spirit seed",
		"quantity": 1,
		"price": null,
		"rarity": "Rare",
		"droprate": "1/256",
		"type": "Seeds",
		"img": "/img/osrs/spirit_seed.png",
		"game": "osrs",
		"boss": "Zulrah",
		"npc": "Zulrah"
	},
	{
		"title": "Crystal seed",
		"quantity": 1,
		"price": 25000,
		"rarity": "Rare",
		"droprate": "1/256",
		"type": "Seeds",
		"img": "/img/osrs/crystal_seed.png",
		"game": "osrs",
		"boss": "Zulrah",
		"npc": "Zulrah"
	},
	{
		"title": "Zul-andra teleport",
		"quantity": 20,
		"price": 640,
		"rarity": "Common",
		"droprate": "",
		"type": "Other",
		"img": "/img/osrs/zul-andra_teleport.png",
		"game": "osrs",
		"boss": "Zulrah",
		"npc": "Zulrah"
	},
	{
		"title": "Dragon bones",
		"quantity": 30,
		"price": 1900,
		"rarity": "Common",
		"droprate": "",
		"type": "Other",
		"img": "/img/osrs/dragon_bones.png",
		"game": "osrs",
		"boss": "Zulrah",
		"npc": "Zulrah"
	},
	{
		"title": "Coconut",
		"quantity": 20,
		"price": 500,
		"rarity": "Common",
		"droprate": "",
		"type": "Other",
		"img": "/img/osrs/coconut.png",
		"game": "osrs",
		"boss": "Zulrah",
		"npc": "Zulrah"
	},
	{
		"title": "Grapes",
		"quantity": 250,
		"price": 60,
		"rarity": "Common",
		"droprate": "",
		"type": "Other",
		"img": "/img/osrs/grapes.png",
		"game": "osrs",
		"boss": "Zulrah",
		"npc": "Zulrah"
	},
	{
		"title": "Zulrah's scales (500)",
		"quantity": 500,
		"price": 54,
		"rarity": "Uncommon",
		"droprate": "",
		"type": "Other",
		"img": "/img/osrs/zulrahs_scales.png",
		"game": "osrs",
		"boss": "Zulrah",
		"npc": "Zulrah"
	},
	{
		"title": "Battlestaff",
		"quantity": 10,
		"price": 7900,
		"rarity": "Uncommon",
		"droprate": "",
		"type": "Other",
		"img": "/img/osrs/battlestaff.png",
		"game": "osrs",
		"boss": "Zulrah",
		"npc": "Zulrah"
	},
	{
		"title": "Antidote++ (4)",
		"quantity": 10,
		"price": 5000,
		"rarity": "Uncommon",
		"droprate": "",
		"type": "Other",
		"img": "/img/osrs/antidote_pp_4.png",
		"game": "osrs",
		"boss": "Zulrah",
		"npc": "Zulrah"
	},
	{
		"title": "Raw shark",
		"quantity": 100,
		"price": 720,
		"rarity": "Uncommon",
		"droprate": "",
		"type": "Other",
		"img": "/img/osrs/raw_shark.png",
		"game": "osrs",
		"boss": "Zulrah",
		"npc": "Zulrah"
	},
	{
		"title": "Mahogany plank",
		"quantity": 50,
		"price": 1500,
		"rarity": "Uncommon",
		"droprate": "",
		"type": "Other",
		"img": "/img/osrs/mahogany_plank.png",
		"game": "osrs",
		"boss": "Zulrah",
		"npc": "Zulrah"
	},
	{
		"title": "Swamp tar",
		"quantity": 1000,
		"price": 25,
		"rarity": "Uncommon",
		"droprate": "",
		"type": "Other",
		"img": "/img/osrs/swamp_tar.png",
		"game": "osrs",
		"boss": "Zulrah",
		"npc": "Zulrah"
	},
	{
		"title": "Saradomin brew (4)",
		"quantity": 10,
		"price": 5000,
		"rarity": "Uncommon",
		"droprate": "",
		"type": "Other",
		"img": "/img/osrs/saradomin_brew_4.png",
		"game": "osrs",
		"boss": "Zulrah",
		"npc": "Zulrah"
	},
	{
		"title": "Adamantite bar",
		"quantity": 25,
		"price": 2200,
		"rarity": "Uncommon",
		"droprate": "",
		"type": "Other",
		"img": "/img/osrs/adamantite_bar.png",
		"game": "osrs",
		"boss": "Zulrah",
		"npc": "Zulrah"
	},
	{
		"title": "Crystal key",
		"quantity": 2,
		"price": 35000,
		"rarity": "Uncommon",
		"droprate": "",
		"type": "Other",
		"img": "/img/osrs/crystal_key.png",
		"game": "osrs",
		"boss": "Zulrah",
		"npc": "Zulrah"
	},
	{
		"title": "Clue scroll (elite)",
		"quantity": 1,
		"price": null,
		"rarity": "Uncommon",
		"droprate": "1/75",
		"type": "Other",
		"img": "/img/osrs/clue_scroll.png",
		"game": "osrs",
		"boss": "Zulrah",
		"npc": "Zulrah"
	},
	{
		"title": "Jar of swamp",
		"quantity": 1,
		"price": null,
		"rarity": "Very rare",
		"droprate": "1/3000",
		"type": "Other",
		"img": "/img/osrs/jar_of_swamp.png",
		"game": "osrs",
		"boss": "Zulrah",
		"npc": "Zulrah"
	},
	{
		"title": "Pet snakeling",
		"quantity": 1,
		"price": null,
		"rarity": "Very rare",
		"droprate": "1/4000",
		"type": "Other",
		"img": "/img/osrs/pet_snakeling.png",
		"game": "osrs",
		"boss": "Zulrah",
		"npc": "Zulrah"
	}
];





